/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IDENavigableItem, NSString;

@interface _IDEGeniusResultsContext : NSObject
{
    NSString *_geniusCategory;
    IDENavigableItem *_geniusRootNavigableItem;
}

@property(copy) NSString *geniusCategory; // @synthesize geniusCategory=_geniusCategory;
@property IDENavigableItem *geniusRootNavigableItem; // @synthesize geniusRootNavigableItem=_geniusRootNavigableItem;

@end

