/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEActionForwardingResponder.h>

@class IDEWorkspaceTabController;

@interface _IDEEditorNavigatorForwardingResponder : IDEActionForwardingResponder
{
    IDEWorkspaceTabController *_workspaceTabController;
}

- (id)initWithWorkspaceTabController:(id)arg1;
- (id)targetForAction:(SEL)arg1;

@end

