/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTExtension, NSMapTable, NSString;

@interface _IDENavigableItemExtraInfo : NSObject
{
    DVTExtension *_representedExtension;
    NSMapTable *_navigableItemsByRepresentedObject;
    NSString *_childItemsKeyPath;
}

@property(copy) NSString *childItemsKeyPath; // @synthesize childItemsKeyPath=_childItemsKeyPath;
- (id)init;
@property(readonly) NSMapTable *navigableItemsByRepresentedObject; // @synthesize navigableItemsByRepresentedObject=_navigableItemsByRepresentedObject;
@property DVTExtension *representedExtension; // @synthesize representedExtension=_representedExtension;

@end

