/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSMenuDelegate-Protocol.h"

@interface _IDEApplicationControllerMenuDelegateForwarder : NSObject <NSMenuDelegate>
{
    id <NSMenuDelegate> _menuDelegate;
    BOOL _delegateRespondsToNeedsUpdate;
    BOOL _delegateRespondsToWillOpen;
    BOOL _delegateRespondsToDidClose;
}

- (id)description;
- (id)initWithMenuDelegate:(id)arg1;
- (void)menuDidClose:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)menuWillOpen:(id)arg1;

@end

