/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEActionForwardingResponder.h>

@class DVTViewController;

@interface _IDEWindowToTabActionForwardingResponder : IDEActionForwardingResponder
{
    DVTViewController *_targetedViewController;
}

@property DVTViewController *targetedViewController; // @synthesize targetedViewController=_targetedViewController;
- (id)targetForAction:(SEL)arg1;

@end

