/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation-Protocol.h"

@class DVTStackBacktrace;

@interface _IDESourceControlOperationInfoInvalidationToken : NSObject <DVTInvalidation>
{
    BOOL _isInvalidated;
    id _invalidationBacktrace;
    id <DVTInvalidation> _currentConflictDetectionToken;
}

@property id <DVTInvalidation> currentConflictDetectionToken; // @synthesize currentConflictDetectionToken=_currentConflictDetectionToken;
- (void)invalidate;
@property(readonly) DVTStackBacktrace *invalidationBacktrace; // @synthesize invalidationBacktrace=_invalidationBacktrace;
@property(readonly, getter=isValid) BOOL valid;

@end

