/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct NSObject {
    Class _field1;
};

struct _IDEKeyBindingFieldCellFlags {
    unsigned int delegateRespondsToKeyboardShortcutIsPrefix:1;
    unsigned int delegateRespondsToAllowsMultipleKeyboardShortcut:1;
    unsigned int delegateRespondsToAlternateKeyBindings:1;
    unsigned int delegateRespondsToValidatedKeyboardShortcut:1;
    unsigned int delegateRespondsToDidEndEditing:1;
    unsigned int delegateRespondsToDidAddKeyboardShortcut:1;
    unsigned int delegateRespondsToWillRemoveKeyboardShortcut:1;
    unsigned int suppressTabAlignment:1;
    unsigned int RESERVED:24;
};

struct _IDEKeyBindingFlags {
    unsigned int isAlternate:1;
    unsigned int isGroupedAlternate:1;
    unsigned int isNavigation:1;
    unsigned int isConflicted:1;
    unsigned int isConflictedWithHotKey:1;
    unsigned int isShiftModifierMaskLocked:1;
    unsigned int isAlternateModifierMaskLocked:1;
    unsigned int isCommandModifierMaskLocked:1;
    unsigned int isControlModifierMaskLocked:1;
    unsigned int disablesPostingKeyboardShortcutsDidChangeNotification:1;
    unsigned int RESERVED:23;
};

struct _IDEKeyBindingSetFlags {
    unsigned int needsUpdateDictionary:1;
    unsigned int updatingDictionary:1;
    unsigned int RESERVED:30;
};

struct _IDEOutlineViewGroupInfo {
    struct _NSRange _field1;
    id _field2;
    struct _IDEOutlineViewGroupInfo *_field3;
};

struct _NSRange {
    unsigned long long location;
    unsigned long long length;
};

struct __va_list_tag {
    unsigned int _field1;
    unsigned int _field2;
    void *_field3;
    void *_field4;
};

#pragma mark Typedef'd Structures

typedef struct {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
} CDStruct_d2b197d1;

