/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTDocumentLocation.h"

@interface DVTDocumentLocation (IDESourceControlDocumentLocationAdditions)
+ (id)fileDataTypeForFileDataType:(id)arg1;
- (id)exportDocumentUsingTemplateDocument:(id)arg1 completionBlock:(id)arg2 primaryBehavior:(void)arg3;
@end

