/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTDevice.h"

@class NSImage, NSString;

@interface DVTDevice (IDEDeviceActivityReporterAdditions)
@property(readonly) NSImage *activityImage;
@property(readonly) long long activityProgress;
@property(readonly) NSString *activityTitle;
@end

