/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@class DVTCustomDataSpecifier, NSImage, NSString;

@protocol DVTPreferenceSet <NSObject>
+ (id)builtInPreferenceSetsDirectoryURL;
+ (id)defaultKeyForCurrentPreferenceSet;
+ (id)defaultKeyForExcludedBuiltInPreferenceSets;
+ (id)preferenceSetGroupingName;
+ (id)preferenceSetsFileExtension;
+ (id)preferenceSetsListHeader;
+ (id)preferenceSetsManager;
+ (id)systemPreferenceSet;
+ (id)titleForNewPreferenceSetFromTemplate;
@property BOOL contentNeedsSaving;
@property DVTCustomDataSpecifier *customDataSpecifier;
- (id)dataRepresentationWithError:(id *)arg1;
@property NSImage *image;
- (id)initWithCustomDataSpecifier:(id)arg1 basePreferenceSet:(id)arg2;
- (id)initWithName:(id)arg1 dataURL:(id)arg2;
@property(readonly, getter=isBuiltIn) BOOL builtIn;
@property(readonly) NSString *localizedName;
@property(readonly) NSString *name;
@end

