/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTSourceModelItem.h"

@interface DVTSourceModelItem (IBDVTFoundationAdditions)
- (id)allDescendantItemsConformingToSpecification:(id)arg1;
- (unsigned long long)ancestorContextMask;
- (id)containingObjCClassItem;
- (unsigned long long)contextMask;
- (unsigned long long)contextMaskUsingContextArray:(id)arg1;
- (id)firstDescendantItemConformingToSpecification:(id)arg1;
- (id)firstItemInLineageOfType:(id)arg1;
- (id)followingSiblingItem;
- (BOOL)isARCTypeQualifierInSourceModel:(id)arg1;
- (BOOL)isActionKeywordInSourceModel:(id)arg1;
- (BOOL)isClassIdentifier;
- (BOOL)isFoldedInTextStorage:(id)arg1;
- (BOOL)isKeyword;
- (BOOL)isKeyword:(id)arg1 inSourceModel:(id)arg2;
- (BOOL)isObjCAtEndKeywordInSourceModel:(id)arg1;
- (BOOL)isObjCAtPrivateKeywordInSourceModel:(id)arg1;
- (BOOL)isObjCAtPropertyKeywordInSourceModel:(id)arg1;
- (BOOL)isObjCAtProtectedKeywordInSourceModel:(id)arg1;
- (BOOL)isObjCAtPublicKeywordInSourceModel:(id)arg1;
- (BOOL)isObjCBlockItem;
- (BOOL)isObjCBracketExpressionItem;
- (BOOL)isObjCCategoryImplementationItem;
- (BOOL)isObjCCategoryInterfaceItem;
- (BOOL)isObjCCategoryOpenParenItem;
- (BOOL)isObjCClassExtensionItem;
- (BOOL)isObjCClassMethodDeclarationItem;
- (BOOL)isObjCClassMethodImplementationItem;
- (BOOL)isObjCGenericClassMethodItem;
- (BOOL)isObjCGenericInstanceMethodItem;
- (BOOL)isObjCGenericMethodItem;
- (BOOL)isObjCIdentifierItem;
- (BOOL)isObjCImplementationDeclaratorItem;
- (BOOL)isObjCImplementationItem;
- (BOOL)isObjCInstanceMethodDeclarationItem;
- (BOOL)isObjCInstanceMethodImplementationItem;
- (BOOL)isObjCInterfaceDeclaratorItem;
- (BOOL)isObjCInterfaceItem;
- (BOOL)isObjCNamedCategoryImplementationDeclaratorItem;
- (BOOL)isObjCNamedCategoryInterfaceDeclaratorItem;
- (BOOL)isObjCPropertyDeclarationItem;
- (BOOL)isObjCStrictImplementationItem;
- (BOOL)isObjCStrictInterfaceItem;
- (BOOL)isObjCSuperKeywordInSourceModel:(id)arg1;
- (BOOL)isOutletCollectionKeywordInSourceModel:(id)arg1;
- (BOOL)isOutletKeywordInSourceModel:(id)arg1;
- (BOOL)isTypeIdentifier;
- (id)nameInSourceModel:(id)arg1;
- (id)objCCategoryItemNameInSourceModel:(id)arg1;
- (id)objCClassItemNameInSourceModel:(id)arg1;
- (id)precedingSiblingItem;
- (id)specification;
- (id)specificationIdentifier;
@end

