/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@class DVTDiffDescriptor, DVTDiffSession, NSURL;

@protocol DVTSourceCodeComparisonAnnotationContext <NSObject>
@property(readonly) int dataSourceType;
@property(readonly) DVTDiffDescriptor *diffDescriptor;
@property(readonly) DVTDiffSession *diffSession;
@property(readonly) NSURL *documentURL;
@end

