/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSTableViewDelegate-Protocol.h"

@protocol DVTTableViewDelegate <NSTableViewDelegate>

@optional
- (void)tableView:(id)arg1 concludeDragOperation:(id)arg2;
- (BOOL)tableView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (void)tableView:(id)arg1 draggingDidEnd:(id)arg2;
- (void)tableView:(id)arg1 draggingDidEnter:(id)arg2;
- (void)tableView:(id)arg1 draggingDidUpdate:(id)arg2;
- (unsigned long long)tableView:(id)arg1 draggingSourceOperationMaskForLocal:(BOOL)arg2;
@end

