/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@class NSDocument<DVTTabbedWindowCreation>, NSString;

@protocol DVTTabbedWindowTabContentControlling <NSObject>
@property NSDocument<DVTTabbedWindowCreation> *document;
@property(copy) NSString *userDefinedTabLabel;
@property(readonly) NSString *tabLabel;
@end

