/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSView.h"

@class IDEActivityView, IDEWorkspaceWindowController;

@interface IDEActivityPlaceholderView : NSView
{
    IDEWorkspaceWindowController *_workspaceWindowController;
    IDEActivityView *_activityView;
}

- (id)hitTest:(struct CGPoint)arg1;
@property IDEWorkspaceWindowController *workspaceWindowController; // @synthesize workspaceWindowController=_workspaceWindowController;
- (void)sizeAndPositionActivityView;
- (void)sizeToFitToolbarDisplayMode:(unsigned long long)arg1 sizeMode:(unsigned long long)arg2;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)arg1;

@end

