/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSMutableArray, NSMutableSet, NSSet;

@interface IDEActivityReportFileIOCoordinator : NSObject
{
    NSMutableArray *_activityReports;
    NSMutableSet *_runningThrottleableActivityReports;
    NSMutableSet *_runningUnthrottleableActivityReports;
    BOOL _isAddingReports;
}

+ (void)initialize;
+ (id)sharedActivityReportFileIOCoordinator;
- (id)_activityReportPriorityComparator;
- (unsigned long long)_allowedConcurrentActivities;
- (id)_init;
- (void)_insertSortedActivityReport:(id)arg1;
- (BOOL)_removeSortedActivityReport:(id)arg1;
- (void)_startObservingReport:(id)arg1;
- (void)_stopObservingReport:(id)arg1;
- (void)_throttleActivityReport:(id)arg1 throttleFactor:(double)arg2;
- (void)_updateRunningActivityReports;
@property(readonly) NSArray *activityReports; // @synthesize activityReports=_activityReports;
- (id)init;
@property(readonly) NSSet *runningThrottleableActivityReports; // @synthesize runningThrottleableActivityReports=_runningThrottleableActivityReports;
@property(readonly) NSSet *runningUnthrottleableActivityReports; // @synthesize runningUnthrottleableActivityReports=_runningUnthrottleableActivityReports;
- (void)updateWithAddedActivityReports:(id)arg1 deletedActivityReports:(id)arg2;

@end

