/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEARCConversionAssistant.h>

#import "NSOutlineViewDataSource-Protocol.h"
#import "NSOutlineViewDelegate-Protocol.h"

@class DVTBorderedView, DVTOutlineView, IDEFilterControlBar, NSArray, NSImageView, NSMutableIndexSet, NSString, NSTextField, NSTreeController;

@interface IDEARCConversionTargetChooserAssistant : IDEARCConversionAssistant <NSOutlineViewDataSource, NSOutlineViewDelegate>
{
    NSArray *_targetChooserItems;
    NSString *_searchString;
    NSMutableIndexSet *_expandedRowIndexes;
    IDEFilterControlBar *_filterControlBar;
    DVTBorderedView *_scopeBarBorderedView;
    DVTOutlineView *_outlineView;
    DVTBorderedView *_borderedView;
    NSImageView *_warningIconImageView;
    NSTextField *_warningTextField;
    NSTreeController *_targetChooserItemsController;
}

+ (id)keyPathsForValuesAffectingCanFinish;
- (id)_effectiveSelectedRowIndexes;
- (id)_filterBuildFiles:(id)arg1 withSearchString:(id)arg2;
- (id)_filterTargets:(id)arg1 withSearchString:(id)arg2;
- (unsigned long long)_numberOfCheckedItemsAtIndexes:(id)arg1;
- (void)_setChecked:(BOOL)arg1 forTargetChooserItemAtIndexes:(id)arg2;
- (BOOL)alwaysShowFinish;
- (BOOL)canCheckSelection;
- (BOOL)canFinish;
- (BOOL)canUncheckSelection;
- (void)checkSelection:(id)arg1;
- (id)filterButtonMenu;
- (id)filterDefinitionIdentifier;
- (void)finishWithCompletionBlock:(id)arg1;
- (void)loadView;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
@property(copy) NSString *searchString; // @synthesize searchString=_searchString;
- (void)setAssistantContext:(id)arg1;
@property(copy) NSArray *targetChooserItems; // @synthesize targetChooserItems=_targetChooserItems;
- (void)uncheckSelection:(id)arg1;
- (void)updateTargetChooserItems;
- (BOOL)validateMenuItem:(id)arg1;

@end

