/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEARCConversionTargetChooserItem.h>

@class NSMapTable;

@interface IDEARCConversionTargetChooserTargetItem : IDEARCConversionTargetChooserItem
{
    long long _numChildrenInOnState;
    NSMapTable *_childItemsToTokens;
}

+ (id)keyPathsForValuesAffectingIconImage;
+ (id)keyPathsForValuesAffectingIsEnabled;
+ (id)keyPathsForValuesAffectingState;
+ (id)keyPathsForValuesAffectingTitle;
+ (id)keyPathsForValuesAffectingWarningMessage;
- (void)childItemWasAdded:(id)arg1;
- (void)childItemWasRemoved:(id)arg1;
- (id)iconImage;
- (id)initWithRepresentedObject:(id)arg1;
- (BOOL)isEnabled;
@property long long numChildrenInOnState; // @synthesize numChildrenInOnState=_numChildrenInOnState;
- (double)rowHeight;
- (void)setState:(long long)arg1;
- (long long)state;
- (id)title;
- (id)warningMessage;

@end

