/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSWindowController.h"

#import "DVTInvalidation-Protocol.h"

@class DVTStackBacktrace, IDEActivityPopUpContentView, IDEActivityView, IDEWorkspaceDocument, NSArray;

@interface IDEActivityPopUpWindowController : NSWindowController <DVTInvalidation>
{
    NSArray *_notificationsToClosePopUpTokens;
    IDEActivityPopUpContentView *_contentView;
    DVTStackBacktrace *_invalidationBacktrace;
    IDEWorkspaceDocument *_workspaceDocument;
    IDEActivityView *_activityView;
    double _targetHeight;
    id _localEventHandler;
    BOOL _isInvalidated;
    BOOL _isClosed;
    BOOL _isOpen;
}

+ (id)activityPopUpWindowForActivityView:(id)arg1;
@property(readonly) IDEActivityView *activityView; // @synthesize activityView=_activityView;
- (struct CGRect)activityViewScreenRect;
- (void)animateOpen;
- (void)animateToHeight:(double)arg1;
- (void)closeAndAnimate:(BOOL)arg1;
- (id)initWithActivityView:(id)arg1 initialDataSource:(id)arg2;
- (void)invalidate;
@property(readonly) DVTStackBacktrace *invalidationBacktrace; // @synthesize invalidationBacktrace=_invalidationBacktrace;
@property(readonly, getter=isValid) BOOL valid;
- (void)navigateToIssuesView;
- (struct CGRect)popUpScreenRectOverActivityViewTakingIntoAccountContentInset;
- (void)startMonitoringForEventsToClosePopUp;
- (void)stopMonitoringForEventsToClosePopUp;
@property(readonly) IDEWorkspaceDocument *workspaceDocument; // @synthesize workspaceDocument=_workspaceDocument;
- (id)workspaceTabControllerForNavigation;

@end

