/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@class IDEActivityIssuesContainerLabelLayer, NSArray, NSMapTable, NSString;

@interface IDEActivityIssuesContainerLayer : CALayer
{
    id _issueCategoryClickHandler;
    IDEActivityIssuesContainerLabelLayer *_labelLayer;
    NSMapTable *_issueCategoryToHidingValidatorMap;
    NSMapTable *_issueCategoryToLayerMap;
    NSString *_rootContainerLabel;
    NSArray *_issueCategories;
}

- (void)addLayerForCategory:(id)arg1;
- (void)categoryDidChangeCount:(id)arg1;
- (id)effectiveIssuesContextLabel;
- (id)hidingValidatorForCategory:(id)arg1;
- (id)init;
@property(copy) NSArray *issueCategories; // @synthesize issueCategories=_issueCategories;
@property(copy) id issueCategoryClickHandler; // @synthesize issueCategoryClickHandler=_issueCategoryClickHandler;
- (id)layerForCategory:(id)arg1;
- (void)layoutSublayers;
- (id)makeLayerForCategory:(id)arg1;
- (id)orderedIssueCategoryLayers;
- (void)removeLayerForCategory:(id)arg1;
@property(copy) NSString *rootContainerLabel; // @synthesize rootContainerLabel=_rootContainerLabel;
- (void)startObservingCategory:(id)arg1;
- (void)stopObservingCategory:(id)arg1;
- (void)updateClickHandlerDisableState:(BOOL)arg1;

@end

