/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEARCConversionTargetChooserItem.h>

@interface IDEARCConversionTargetChooserBuildFileItem : IDEARCConversionTargetChooserItem
{
}

+ (BOOL)automaticallyNotifiesObserversOfState;
+ (id)keyPathsForValuesAffectingIconImage;
+ (id)keyPathsForValuesAffectingIsEnabled;
+ (id)keyPathsForValuesAffectingState;
+ (id)keyPathsForValuesAffectingTitle;
- (id)iconImage;
- (id)initWithRepresentedObject:(id)arg1;
- (BOOL)isEnabled;
- (double)rowHeight;
- (void)setState:(long long)arg1;
- (long long)state;
- (id)title;
- (id)warningMessage;

@end

