/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTClickableLayer.h"

@class CALayer, CATextLayer, NSAttributedString, NSImage, NSString;

@interface IDEActivityIssueCategoryLayer : DVTClickableLayer
{
    NSAttributedString *_cachedAttributedCountString;
    NSString *_issueTypeDisplayName;
    CATextLayer *_textLayer;
    CALayer *_imageLayer;
    long long _count;
}

- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)attributedCountString;
@property long long count; // @synthesize count=_count;
@property NSImage *image;
- (id)init;
@property(copy) NSString *issueTypeDisplayName; // @synthesize issueTypeDisplayName=_issueTypeDisplayName;
- (void)layoutSublayers;
- (id)textAttributes;

@end

