/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol IDEActivityPopUpContentLayerDelegate <NSObject>

@optional
- (void)doneButtonWasClickedInPopUpContentLayer:(id)arg1;
- (void)popUpContentLayer:(id)arg1 didChangePreferredHeightTo:(double)arg2;
- (void)popUpContentLayerDidRequestNavigationToIssuesView:(id)arg1;
@end

