/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTProgressReporting-Protocol.h"

@class NSArray, NSDictionary, NSImage, NSString;

@interface IDEActivityReport : NSObject <DVTProgressReporting>
{
    NSArray *_completionSummaryStringSegments;
    NSString *_completionSummaryString;
    int _options;
    long long _progress;
    double _timestamp;
    NSArray *_titleSegments;
    NSString *_title;
    NSImage *_image;
    unsigned long long _fileIOPriority;
    id _fileIOCoordinatorBlock;
    double _fileIOThrottleFactor;
}

+ (BOOL)automaticallyNotifiesObserversOfFileIOThrottleFactor;
+ (id)keyPathsForValuesAffectingCompleted;
- (void)_setFileIOThrottleFactor:(double)arg1;
@property(copy) NSString *completionSummaryString; // @synthesize completionSummaryString=_completionSummaryString;
@property(copy) NSArray *completionSummaryStringSegments; // @synthesize completionSummaryStringSegments=_completionSummaryStringSegments;
- (id)description;
@property(readonly) NSDictionary *dictionaryRepresentation;
@property(readonly) BOOL disableTitleAnimation;
@property(readonly) id fileIOCoordinatorBlock; // @synthesize fileIOCoordinatorBlock=_fileIOCoordinatorBlock;
@property unsigned long long fileIOPriority; // @synthesize fileIOPriority=_fileIOPriority;
@property(readonly) double fileIOThrottleFactor; // @synthesize fileIOThrottleFactor=_fileIOThrottleFactor;
@property(readonly) BOOL hidesProgress;
@property(readonly) NSImage *image; // @synthesize image=_image;
- (id)init;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (id)initWithOptions:(int)arg1 image:(id)arg2 fileIOPriority:(unsigned long long)arg3 fileIOCoordinatorBlock:(id)arg4;
@property(readonly, getter=isCancelable) BOOL cancelable;
@property(readonly, getter=isCompleted) BOOL completed;
@property(readonly, getter=isFileIOIntensive) BOOL fileIOIntensive;
@property(readonly, getter=isPersistent) BOOL persistent;
@property(readonly, getter=isSchemeBased) BOOL schemeBased;
@property(readonly, getter=isUserRequested) BOOL userRequested;
@property(readonly) int options; // @synthesize options=_options;
@property long long progress; // @synthesize progress=_progress;
- (void)setProgressAsNSNumber:(id)arg1;
@property(copy) NSString *title; // @synthesize title=_title;
@property(copy) NSArray *titleSegments; // @synthesize titleSegments=_titleSegments;
@property(readonly) BOOL shouldDisplayImmediately;
@property(readonly) NSString *stringValue;
@property(readonly) double timestamp; // @synthesize timestamp=_timestamp;

@end

