/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSImage, NSString;

@interface IDEActivityIssueCategory : NSObject
{
    NSString *_title;
    long long _count;
    NSImage *_image;
}

@property long long count; // @synthesize count=_count;
- (id)description;
@property(readonly) NSImage *image; // @synthesize image=_image;
- (id)initWithTitle:(id)arg1 image:(id)arg2;
@property(readonly) NSString *title; // @synthesize title=_title;

@end

