/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class IDEAssistantWindowController, IDEWorkspace, IDEWorkspaceTabController, NSWindow;

@interface IDEAssistantContext : NSObject <NSCopying>
{
    IDEWorkspaceTabController *_workspaceTabController;
    IDEAssistantWindowController *_assistantWindowController;
}

@property IDEAssistantWindowController *assistantWindowController; // @synthesize assistantWindowController=_assistantWindowController;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property IDEWorkspaceTabController *workspaceTabController; // @synthesize workspaceTabController=_workspaceTabController;
@property(readonly) IDEWorkspace *workspace;
@property(readonly) NSWindow *workspaceWindow;

@end

