/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEAssistantContext.h>

@class NSArray, NSMutableArray;

@interface IDEARCConversionAssistantContext : IDEAssistantContext
{
    NSMutableArray *_targets;
    NSMutableArray *_selectedTargets;
    unsigned long long _currentConversionStage;
    long long _numIncompatibilityErrors;
    BOOL _wasContinueBuildingAfterErrors;
    BOOL _shouldRemoveContinueBuildingAfterErrors;
}

+ (void)initialize;
- (void)beginPerformingContextTask;
- (id)buildActionEntries;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property unsigned long long currentConversionStage; // @synthesize currentConversionStage=_currentConversionStage;
- (void)endPerformingContextTask;
- (id)init;
@property long long numberOfIncompatibilityErrors; // @synthesize numberOfIncompatibilityErrors=_numIncompatibilityErrors;
- (id)runContext;
- (id)runPhase;
- (void)setWorkspaceTabController:(id)arg1;
@property(readonly) NSArray *targets; // @synthesize targets=_targets;

// Remaining properties
@property(readonly) NSMutableArray *mutableSelectedTargets; // @dynamic mutableSelectedTargets;
@property(copy) NSArray *selectedTargets; // @dynamic selectedTargets;

@end

