/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSMenuDelegate-Protocol.h"

@interface IDEActivityTestingMenuDelegate : NSObject <NSMenuDelegate>
{
}

- (void)doActionFromMenuItem:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)stopAllActivitiesFromMenuItem:(id)arg1;
- (id)workspace;

@end

