/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTViewController.h"

@class NSString, NSUserDefaultsController;

@interface IDEAppPrefPaneController : DVTViewController
{
    NSUserDefaultsController *defaultsController;
}

@property NSUserDefaultsController *defaultsController; // @synthesize defaultsController;
- (void)loadView;
@property(readonly) NSString *modifiedClickLabel;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

@end

