/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSWindowController.h"

#import "DVTReplacementViewDelegate-Protocol.h"

@class DVTBorderedView, DVTReplacementView, DVTStackView, IDEAssistant, IDEAssistantContext, NSButton, NSImageView, NSMutableArray, NSString, NSTextField, NSView;

@interface IDEAssistantWindowController : NSWindowController <DVTReplacementViewDelegate>
{
    DVTReplacementView *_replacementView;
    DVTBorderedView *_borderedView;
    DVTBorderedView *_sourceListBorderedView;
    DVTStackView *_buttonStackView;
    NSMutableArray *_assistantHistory;
    NSButton *_nextButton;
    NSButton *_backButton;
    NSButton *_cancelButton;
    NSTextField *_titleField;
    IDEAssistant *_currentAssistant;
    IDEAssistantContext *_assistantContext;
    id _currentCompletionBlock;
    double _lastAnimationDirection;
    NSImageView *_replacementImageView;
    NSImageView *_titleFieldImageView;
    NSImageView *_cancelButtonImageView;
    NSImageView *_sourceListImageView;
    NSString *_windowDefaultsName;
    NSView *_nextKeyView;
    NSMutableArray *_allAnimations;
    BOOL _backtrackingFromOverlayAssistant;
}

+ (id)keyPathsForValuesAffectingAssistantTitle;
+ (id)keyPathsForValuesAffectingCanGoForwardOrFinish;
+ (id)keyPathsForValuesAffectingForwardOrFinishButtonTitle;
+ (id)keyPathsForValuesAffectingOnFirstAssistant;
- (void)_clearAssistantHistoryStack;
- (void)_finishWithAction:(id)arg1;
- (id)_popAssistantHistoryStack;
- (void)_pushAssistantOntoHistoryStack:(id)arg1;
- (void)addAnimationForKey:(id)arg1 toView:(id)arg2;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (id)assistantTitle;
- (id)assistantWithIdentifier:(id)arg1;
- (void)beginSessionForWorkspaceWindow:(id)arg1;
- (void)beginSessionWithAssistantIdentifier:(id)arg1 context:(id)arg2 completionBlock:(id)arg3;
- (BOOL)canGoBack;
- (BOOL)canGoForwardOrFinish;
- (void)cancelSession;
- (void)cleanUpAnimationForView:(id)arg1;
- (void)close;
@property IDEAssistant *currentAssistant; // @synthesize currentAssistant=_currentAssistant;
- (void)endAssistantSessionWithResult:(int)arg1 error:(id)arg2;
- (void)ensureImageViewsConfigured;
- (id)forwardOrFinishButtonTitle;
- (void)goBack:(id)arg1;
- (void)goNextOrFinish:(id)arg1;
- (id)imageForView:(id)arg1 bordered:(BOOL)arg2;
- (id)init;
- (BOOL)onFirstAssistant;
- (void)replacementView:(id)arg1 didInstallViewController:(id)arg2;
- (void)replacementView:(id)arg1 willCloseViewController:(id)arg2;
- (void)replacementView:(id)arg1 willInstallViewController:(id)arg2;
- (void)setAnimationDuration;
- (void)setUpAnimationImageViewWithDirection:(double)arg1 actionBlock:(id)arg2;
- (void)setUpOverlayForAssistantWithIdentifier:(id)arg1;
- (void)setupAccessoriesForAssistant:(id)arg1 animated:(BOOL)arg2;
- (id)skipAheadIfPossibleAndReturnAssistantIdentifier;
- (void)windowDidLoad;

@end

