/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEExplorationContext.h>

@class IDEActivityLogAnalyzerResultMessage, IDEIssue;

@interface IDEAnalyzerResultExplorationContext : IDEExplorationContext
{
    IDEActivityLogAnalyzerResultMessage *_message;
    IDEIssue *_step;
}

- (int)explorationType;
- (id)initWithAnalyzerResultMessage:(id)arg1 stepIssue:(id)arg2;
@property(readonly) IDEActivityLogAnalyzerResultMessage *message; // @synthesize message=_message;
@property(readonly) IDEIssue *step; // @synthesize step=_step;

@end

