/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

@class IDEArchiveSchemeAction, IDEScheme, IDEWorkspace, NSBox, NSMenuItem, NSPopUpButton, NSString, NSTextField;

@interface IDEArchiveRunPhaseSheetController : IDEViewController
{
    IDEScheme *_scheme;
    IDEWorkspace *_workspace;
    IDEArchiveSchemeAction *_schemeAction;
    NSTextField *_archiveNameTextField;
    NSPopUpButton *_packagingPopUp;
    NSPopUpButton *_identityPopUp;
    NSBox *_box;
    NSMenuItem *_packagingPopUpItemToRemove;
    id customArchiveNameObservingToken;
}

+ (void)initialize;
- (id)_applicationPlatform;
- (id)_applicationProducts;
- (id)_applicationToArchiveBundleIdentifiers;
@property(copy) NSString *customArchiveName;
- (id)dvtExtraBindings;
- (void)invalidate;
- (void)loadView;
@property IDEScheme *scheme; // @synthesize scheme=_scheme;
@property IDEArchiveSchemeAction *schemeAction; // @synthesize schemeAction=_schemeAction;
@property IDEWorkspace *workspace;
- (void)updateBoundContent;
- (void)updateBoundIDERunContextBinding;
- (void)updateBoundIDEWorkspaceBinding;

@end

