/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@class CABasicAnimation, DVTDelayedValidator, NSImage;

@interface IDEActivityProgressIndicatorLayer : CALayer
{
    CABasicAnimation *_indeterminateDiagonalsAnimation;
    unsigned long long _progressStyle;
    NSImage *_indeterminateDiagonalsLayerContents;
    DVTDelayedValidator *_progressValidator;
    CALayer *_indeterminateDiagonalsLayer;
    CALayer *_indeterminateContainerLayer;
    CALayer *_progressContainerLayer;
    NSImage *_containerLayerContents;
    NSImage *_progressLayerContents;
    NSImage *_shadowLayerContents;
    CALayer *_containerLayer;
    CALayer *_progressLayer;
    CALayer *_shadowLayer;
    double _doubleValue;
    double _minValue;
    double _maxValue;
    struct {
        unsigned int indeterminate:1;
        unsigned int willGoBackwards:1;
        unsigned int _reserved:6;
    } _flags;
}

+ (id)defaultActionForKey:(id)arg1;
+ (void)initialize;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)arg1;
- (BOOL)accessibilityIsIgnored;
@property double doubleValue; // @synthesize doubleValue=_doubleValue;
- (id)dvtExtraBindings;
- (id)effectiveContainerLayerContents;
- (id)effectiveIndeterminateDiagonalsLayerContents;
- (id)effectiveInnerShadow;
- (double)effectivePercentage;
- (struct CGRect)effectiveProgressContainerLayerBounds;
- (struct CGPoint)effectiveProgressContainerLayerPosition;
- (struct CGRect)effectiveProgressLayerBounds;
- (id)effectiveProgressLayerContents;
- (id)effectiveProgressLayerGradient;
- (id)effectiveShadowLayerContents;
- (id)init;
- (void)invalidateProgressState;
@property(getter=isIndeterminate) BOOL indeterminate;
@property double maxValue; // @synthesize maxValue=_maxValue;
@property double minValue; // @synthesize minValue=_minValue;
@property unsigned long long progressStyle; // @synthesize progressStyle=_progressStyle;
- (void)reflectIndeterminateState;
- (void)reflectStyle;
- (void)setBounds:(struct CGRect)arg1;
- (void)setHidden:(BOOL)arg1;
- (void)setupLayers;
- (void)updateBoundValue;
- (void)updateProgressLayer;
- (void)validateProgressStateIfNeeded;

@end

