/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTViewController.h"

@class IDEAssistantContext, NSString, NSView;

@interface IDEAssistant : DVTViewController
{
    IDEAssistantContext *_assistantContext;
    NSString *_nextAssistantIdentifier;
}

+ (BOOL)wantsOverlayEffect;
@property(readonly) BOOL alwaysShowFinish;
@property(retain) IDEAssistantContext *assistantContext; // @synthesize assistantContext=_assistantContext;
@property(readonly) NSString *assistantTitle;
- (BOOL)canBecomeMainViewController;
@property(readonly) BOOL canFinish;
@property(readonly) BOOL canGoBack;
@property(readonly) BOOL canGoForward;
@property(readonly) BOOL expandsAssistantView;
- (id)finishButtonTitle;
- (void)finishWithCompletionBlock:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property NSString *nextAssistantIdentifier; // @synthesize nextAssistantIdentifier=_nextAssistantIdentifier;
@property(readonly) NSView *sourceListView;

@end

