/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@class IDEActivityProgressIndicatorLayer, IDEActivityReport, IDEActivityScrollingTextLayer, NSMutableArray;

@interface IDEActivityReportLayer : CALayer
{
    IDEActivityProgressIndicatorLayer *_progressIndicatorLayer;
    IDEActivityScrollingTextLayer *_scrollingTextLayer;
    long long _displayStyle;
    IDEActivityReport *_activityReport;
    CALayer *_imageLayer;
    NSMutableArray *_stringSegments;
    BOOL _paused;
    id <DVTObservingToken> _kvoActivityReportTitleSegmentsToken;
    id <DVTObservingToken> _kvoActivityReportProgressToken;
    id <DVTObservingToken> _kvoActivityReportTitleToken;
    id <DVTObservingToken> _kvoActivityReportThrottleFactorToken;
}

+ (id)activityReportLayerForDisplayStyle:(long long)arg1;
+ (struct CGSize)defaultSizeForPopUpStyle;
- (void)_addPausedSegment;
- (id)_pausedAttributes;
- (void)_removePausedSegment;
- (void)_updatePaused:(BOOL)arg1;
- (void)_updateStringSegments:(id)arg1;
@property IDEActivityReport *activityReport; // @synthesize activityReport=_activityReport;
- (id)defaultCompletionSummary;
- (id)defaultIdleTitle;
- (id)defaultReportTitle;
- (id)description;
@property long long displayStyle; // @synthesize displayStyle=_displayStyle;
- (struct CGPoint)imageLayerPosition;
- (id)init;
- (struct CGRect)progressIndicatorLayerFrame;
- (struct CGRect)scrollingTextLayerFrame;
- (void)sizeToFit;
- (void)startObservingActivityReport;
- (void)stopObservingActivityReport;
- (void)updateImageLayer;
- (void)updateScrollingTextFieldStringValue;
- (void)updateVisibilityForTextFieldAndAdjustLayoutIfNeeded;

@end

