/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IDEARCConversionTarget, IDEFileReference, NSImage, NSString;

@interface IDEARCConversionBuildFile : NSObject
{
    IDEFileReference *_fileReference;
    IDEARCConversionTarget *_target;
    NSImage *_iconImage;
    BOOL _enablesARC;
}

- (void)_setEnablesARC:(BOOL)arg1 overridingOnly:(BOOL)arg2;
- (id)_treeControllerChildren;
- (id)_treeControllerWarningMessage;
- (void)disableOverridingBuildSettings;
@property(readonly) NSString *displayName;
- (void)enableOverridingBuildSettings;
@property BOOL enablesARC; // @synthesize enablesARC=_enablesARC;
@property(readonly) IDEFileReference *fileReference; // @synthesize fileReference=_fileReference;
@property(readonly) NSImage *iconImage; // @synthesize iconImage=_iconImage;
- (id)initWithFileReference:(id)arg1 target:(id)arg2;
@property(readonly) IDEARCConversionTarget *target; // @synthesize target=_target;
- (void)updateBuildSettings;

@end

