/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTApplication.h"

#import "NSMenuDelegate-Protocol.h"

@class IDEWorkspaceWindow;

@interface IDEApplication : DVTApplication <NSMenuDelegate>
{
    id _ideEventDelegate;
}

- (void)_enableFloatingDebugger;
- (void)_errorAlert:(id)arg1 wasPresentedWithResult:(long long)arg2 inContext:(id)arg3;
- (id)_findDebuggingWorkspaceWindowOrFrontmostWorkspaceWindow;
- (void)addWindowsItem:(id)arg1 title:(id)arg2 filename:(BOOL)arg3;
- (void)beginSheet:(id)arg1 modalForWindow:(id)arg2 modalDelegate:(id)arg3 didEndSelector:(SEL)arg4 contextInfo:(void *)arg5;
- (void)changeWindowsItem:(id)arg1 title:(id)arg2 filename:(BOOL)arg3;
- (void)closeAll:(id)arg1;
- (void)endSheet:(id)arg1 returnCode:(long long)arg2;
@property id <IDEApplicationEventDelegate> eventDelegate; // @synthesize eventDelegate=_ideEventDelegate;
- (void)insertInSdefSupport_projects:(id)arg1 atIndex:(long long)arg2;
- (void)insertInSdefSupport_workspaceDocuments:(id)arg1;
@property(readonly) IDEWorkspaceWindow *keyWorkspaceWindow;
@property(readonly) IDEWorkspaceWindow *lastActiveWorkspaceWindow;
- (void)menuNeedsUpdate:(id)arg1;
- (id)newScriptingObjectOfClass:(Class)arg1 forValueForKey:(id)arg2 withContentsValue:(id)arg3 properties:(id)arg4;
- (void)removeWindowsItem:(id)arg1;
- (void)reportException:(id)arg1;
- (id)sdefSupport_activeWorkspaceDocument;
- (id)sdefSupport_breakpoints;
- (id)sdefSupport_classModelDocuments;
- (id)sdefSupport_fileBreakpoints;
- (id)sdefSupport_newWorkspaceDocument:(id)arg1;
- (id)sdefSupport_symbolicBreakpoints;
- (id)sdefSupport_workspaceDocuments;
- (BOOL)sendAction:(SEL)arg1 to:(id)arg2 from:(id)arg3;
- (void)sendEvent:(id)arg1;
- (void)setSdefSupport_activeWorkspaceDocument:(id)arg1;
- (void)setWindowsMenu:(id)arg1;
- (void)terminate:(id)arg1;
- (void)updateWindowsItem:(id)arg1;

@end

