/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEActivityReportStringSegment.h>

@class NSDate;

@interface IDEActivityReportDateStringSegment : IDEActivityReportStringSegment
{
    unsigned long long _dateStyle;
    unsigned long long _timeStyle;
    NSDate *_date;
}

@property(readonly) NSDate *date; // @synthesize date=_date;
@property(readonly) unsigned long long dateStyle; // @synthesize dateStyle=_dateStyle;
- (id)dictionaryRepresentation;
- (id)initWithDate:(id)arg1 priority:(double)arg2 dateStyle:(unsigned long long)arg3 timeStyle:(unsigned long long)arg4;
- (id)initWithDate:(id)arg1 priority:(double)arg2 frontSeparator:(id)arg3 backSeparator:(id)arg4 dateStyle:(unsigned long long)arg5 timeStyle:(unsigned long long)arg6;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (long long)segmentType;
- (id)stringValue;
@property(readonly) unsigned long long timeStyle; // @synthesize timeStyle=_timeStyle;

@end

