/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEARCConversionAssistant.h>

@class NSTextView;

@interface IDEARCConversionApprovalAssistant : IDEARCConversionAssistant
{
    NSTextView *_textView;
}

- (id)_messageContentsURL;
- (BOOL)canGoForward;
- (void)loadView;
- (id)nextAssistantIdentifier;

@end

