/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSImage, NSMutableArray, NSString;

@interface IDEARCConversionTargetChooserItem : NSObject
{
    id _representedObject;
    NSMutableArray *_childItems;
}

- (id)_childItems;
- (void)childItemWasAdded:(id)arg1;
- (void)childItemWasRemoved:(id)arg1;
@property(readonly) NSArray *childItems;
@property(readonly) NSImage *iconImage;
- (id)initWithRepresentedObject:(id)arg1;
- (void)insertObject:(id)arg1 inChildItemsAtIndex:(unsigned long long)arg2;
@property(readonly) BOOL isEnabled;
@property(readonly) NSMutableArray *mutableChildItems;
- (void)removeObjectFromChildItemsAtIndex:(unsigned long long)arg1;
@property(readonly) id representedObject; // @synthesize representedObject=_representedObject;
@property(readonly) double rowHeight;
@property long long state;
@property(readonly) NSString *title;
@property(readonly) NSString *warningMessage;

@end

