/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDEAttachToProcessSheetDelegate-Protocol.h"

@class IDEWorkspaceTabController;

@interface IDEAttachToProcessHelper : NSObject <IDEAttachToProcessSheetDelegate>
{
    IDEWorkspaceTabController *_workspaceTabController;
}

+ (id)_archNameForExecutableArchitecture:(int)arg1;
+ (id)_archtiectureForTarget:(id)arg1;
+ (void)askUserForProcessIdentifierAndAttachToItFromWorkspaceTabController:(id)arg1;
+ (void)attachToProcess:(id)arg1 fromWorkspaceTabController:(id)arg2;
- (void)_attachToPID:(int)arg1 usingDebugger:(id)arg2 displayName:(id)arg3 processPath:(id)arg4 targetArchitecture:(id)arg5 launchStyle:(int)arg6;
- (void)_attachToProcess:(id)arg1 usingDebugger:(id)arg2;
- (void)_attachToProcessID:(id)arg1 usingDebugger:(id)arg2;
- (void)_attachToProcessName:(id)arg1 usingDebugger:(id)arg2;
- (id)_initWithWorkspaceTabController:(id)arg1;
- (void)_showAlertForNonDebuggableArchitecture:(id)arg1;
- (void)processIDEntered:(id)arg1 debuggerToUse:(id)arg2;
- (void)processInformationSelected:(id)arg1 debuggerToUse:(id)arg2;
- (void)processNameEntered:(id)arg1 debuggerToUse:(id)arg2;

@end

