/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "IDECapsuleViewController-Protocol.h"
#import "IDECapsuleViewDelegate-Protocol.h"

@class IDEExecutionAction, NSImage, NSString;

@interface IDEActionSliceViewController : IDEViewController <IDECapsuleViewController, IDECapsuleViewDelegate>
{
    IDEExecutionAction *_action;
    id <IDEActionSliceViewControllerDelegate> _delegate;
}

@property(readonly) IDEExecutionAction *action; // @synthesize action=_action;
@property BOOL canRemoveItems;
@property(readonly) BOOL canUndisclose;
- (void)capsuleView:(id)arg1 setTitle:(id)arg2;
- (BOOL)capsuleViewCanBeRemoved:(id)arg1;
- (BOOL)capsuleViewCanBeRenamed:(id)arg1;
- (void)capsuleViewDidClickRemoveButton:(id)arg1;
- (id)capsuleViewTitleForEditing:(id)arg1;
@property id <IDEActionSliceViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithAction:(id)arg1;
@property(readonly) NSString *titleForDisplay;

// Remaining properties
@property BOOL canAddItems;
@property(readonly) BOOL canRemove;
@property(readonly) BOOL canRename;
@property(readonly) BOOL disclosedByDefault;
@property(readonly) NSString *footerLabel;
@property(readonly) NSImage *icon;

@end

