/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEExplorationContext.h>

@class NSString;

@interface IDEActionExplorationContext : IDEExplorationContext
{
    NSString *_actionIdentifier;
}

@property(readonly) NSString *actionIdentifier; // @synthesize actionIdentifier=_actionIdentifier;
- (int)explorationType;
- (id)initWithAction:(id)arg1;

@end

