/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEFileNavigableItem.h>

@interface IDEBaseDocumentNavigableItem : IDEFileNavigableItem
{
    id _dirtyNotificationToken;
}

- (void)_updateEditorDocument:(id)arg1;
- (void)invalidateImage;

@end

