/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSButtonCell.h"

@class IDEBreakpointIcon;

@interface IDEBreakpointCell : NSButtonCell
{
    BOOL _breakpointsActivated;
    BOOL _breakpointEnabled;
    BOOL _mouseDown;
    IDEBreakpointIcon *_icon;
    double _width;
    double _height;
    double _topPad;
    double _leftPad;
    double _bottomPad;
    double _rightPad;
}

@property BOOL breakpointEnabled; // @synthesize breakpointEnabled=_breakpointEnabled;
@property BOOL breakpointsActivated; // @synthesize breakpointsActivated=_breakpointsActivated;
- (struct CGSize)cellSize;
- (BOOL)continueTracking:(struct CGPoint)arg1 at:(struct CGPoint)arg2 inView:(id)arg3;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)initWithHeight:(double)arg1 topAndBottomPad:(double)arg2;
- (BOOL)startTrackingAt:(struct CGPoint)arg1 inView:(id)arg2;
- (void)stopTracking:(struct CGPoint)arg1 at:(struct CGPoint)arg2 inView:(id)arg3 mouseIsUp:(BOOL)arg4;

@end

