/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEBuildable-Protocol.h"

@class DVTFileDataType, DVTFilePath, IDEBuildableProductFileMap, NSDictionary, NSString;

@protocol IDEBuildableProduct <IDEBuildable>
@property(readonly) IDEBuildableProductFileMap *buildableProductFileMap;
- (id)buildableProductFileMapForWorkspaceArenaSnapshot:(id)arg1;
@property(readonly) DVTFileDataType *fileDataType;
@property(readonly) DVTFilePath *filePath;
- (id)filePathForBuildParameters:(id)arg1;
- (id)filePathForBuildableProductFileMapForWorkspaceArenaSnapshot:(id)arg1;
@property(readonly) NSString *infoPlistIconPath;
@property(readonly) BOOL productIsExecutable;
@property(readonly) NSDictionary *productSettings;
- (id)productTypeIdentifier;
@end

