/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEBuildIssueProvider.h"

@interface IDEBuildIssueProvider (IDEKitAdditions)
- (id)alternateDocumentLocationForIssue:(id)arg1;
- (id)alternateDocumentTypeForIssue:(id)arg1;
@end

