/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTBorderedView.h"

@class DVTGradientImageButton, IDEComparisonEditor, IDEPathControl;

@interface IDEComparisonEditorTimelineNavBar : DVTBorderedView
{
    IDEComparisonEditor *_comparisonEditor;
    IDEPathControl *_primaryPathControl;
    IDEPathControl *_secondaryPathControl;
    DVTGradientImageButton *_timelineActivationButton;
    BOOL _hideTimelineButton;
    BOOL _hideSecondaryPathControl;
}

- (void)_dvt_commonInit;
@property IDEComparisonEditor *comparisonEditor; // @synthesize comparisonEditor=_comparisonEditor;
@property BOOL hideSecondaryPathControl;
@property BOOL hideTimelineButton;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutTopDown;
@property IDEPathControl *primaryPathControl; // @synthesize primaryPathControl=_primaryPathControl;
@property IDEPathControl *secondaryPathControl; // @synthesize secondaryPathControl=_secondaryPathControl;
@property DVTGradientImageButton *timelineActivationButton; // @synthesize timelineActivationButton=_timelineActivationButton;

@end

