/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@class CATextLayer, IDEComparisonNavTimelineView, NSDate, NSString;

// Not exported
@interface IDEComparisonLineLayer : CALayer
{
    CATextLayer *_labelLayer;
    NSString *_revisionLabel;
    int _selection;
    double _magnification;
    IDEComparisonNavTimelineView *_owner;
    id _representedObject;
    NSDate *_date;
    int _lineLayerStyle;
    BOOL _mouseOver;
    BOOL _validated;
}

+ (void)initialize;
+ (id)layer;
+ (id)layerWithOwner:(id)arg1;
+ (struct CGImage *)tickFillImageRef;
+ (struct CGImage *)tickLeftEndcapImageRef;
+ (struct CGImage *)tickRightEndcapImageRef;
@property NSDate *date; // @synthesize date=_date;
- (void)drawInContext:(struct CGContext *)arg1;
- (double)elasticCenterY;
- (int)hoverIndicator;
- (id)init;
- (id)initWithOwner:(id)arg1;
@property int lineLayerStyle; // @synthesize lineLayerStyle=_lineLayerStyle;
@property double magnification; // @synthesize magnification=_magnification;
@property BOOL mouseOver; // @synthesize mouseOver=_mouseOver;
@property IDEComparisonNavTimelineView *owner; // @synthesize owner=_owner;
- (double)preferredHeight;
@property id representedObject; // @synthesize representedObject=_representedObject;
@property NSString *revisionLabel;
@property(readonly) BOOL selectable;
@property int selection; // @synthesize selection=_selection;
@property BOOL validated; // @synthesize validated=_validated;
@property(readonly) double tickAlpha;
- (void)updateMagnification:(BOOL)arg1;

@end

