/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol IDEContainerErrorPresenter
- (int)handleSaveError:(id)arg1 forContainer:(id)arg2 withAction:(int)arg3;
- (BOOL)presentError:(id)arg1;
@end

