/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTDownloadable, DVTDownloadableOperation, IDEComponentDownloadsPrefPaneController, NSImage, NSMutableSet, NSString;

@interface IDEComponentDownloadsPrefPaneItem : NSObject
{
    DVTDownloadable *_downloadable;
    int _state;
    DVTDownloadableOperation *_downloadOperation;
    long long _downloadProgress;
    NSString *_fileSizeForDisplay;
    id _downloadCompletionBlock;
    BOOL _cancelable;
    IDEComponentDownloadsPrefPaneController *_controller;
    id <DVTObservingToken> _downloadCancelledToken;
    id <DVTObservingToken> _downloadFinishedToken;
    NSMutableSet *_downloadOperationObservationTokens;
}

+ (id)itemWithDownloadable:(id)arg1 state:(int)arg2 downloadOperation:(id)arg3 controller:(id)arg4;
- (void)_updateCancelable;
- (void)cancelDownload;
@property(readonly) BOOL cancelable; // @synthesize cancelable=_cancelable;
@property(readonly) IDEComponentDownloadsPrefPaneController *controller; // @synthesize controller=_controller;
- (id)description;
@property DVTDownloadableOperation *downloadOperation; // @synthesize downloadOperation=_downloadOperation;
@property(readonly) long long downloadProgress; // @synthesize downloadProgress=_downloadProgress;
- (BOOL)downloadWithError:(id *)arg1 downloadCompletionBlock:(id)arg2;
@property(readonly) DVTDownloadable *downloadable; // @synthesize downloadable=_downloadable;
@property(readonly) NSString *fileSizeForDisplay; // @synthesize fileSizeForDisplay=_fileSizeForDisplay;
@property(readonly) NSImage *image;
@property int state; // @synthesize state=_state;

@end

