/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTDisclosureView.h"

#import "NSTextFieldDelegate-Protocol.h"

@class IDECapsuleFooterView, IDEViewController<IDECapsuleViewController>, NSTrackingArea;

@interface IDECapsuleView : DVTDisclosureView <NSTextFieldDelegate>
{
    IDECapsuleFooterView *_footerView;
    id <IDECapsuleViewDelegate> _delegate;
    NSTrackingArea *_titleCursorArea;
    IDEViewController<IDECapsuleViewController> *_viewController;
    id _frameChangedObserver;
    id <DVTObservingToken> _disclosedObserver;
    struct {
        unsigned int supportedDragTypes:1;
        unsigned int acceptDrop:1;
        unsigned int validateDrop:1;
        unsigned int drawBorderBelowHeader:1;
        unsigned int canRemove:1;
        unsigned int canRename:1;
        unsigned int clickedRemoveButton:1;
        unsigned int titleForEditing:1;
        unsigned int setTitle:1;
    } _delegateRespondsTo;
    BOOL _selected;
}

- (void)_addTrackingArea;
- (struct CGRect)_footerRect;
- (struct CGRect)_headerRect;
@property(readonly) BOOL _removable;
- (void)_remove:(id)arg1;
@property(readonly) BOOL _renamable;
- (void)_rename:(id)arg1;
- (void)_titleForDisplayChanged:(id)arg1;
- (void)_toggleSubviewVisibility:(id)arg1;
- (BOOL)_willDrawBorderBelowHeader;
- (BOOL)_willDrawContent;
- (BOOL)_willDrawFooter;
- (BOOL)acceptsFirstResponder;
- (BOOL)becomeFirstResponder;
@property(readonly) struct CGRect capsuleBounds;
- (void)controlTextDidEndEditing:(id)arg1;
- (void)cursorUpdate:(id)arg1;
@property id <IDECapsuleViewDelegate> delegate; // @synthesize delegate=_delegate;
- (unsigned long long)draggingEntered:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
@property IDECapsuleFooterView *footerView; // @synthesize footerView=_footerView;
- (id)initWithCapsuleViewController:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutBottomUp;
- (void)layoutTopDown;
- (BOOL)performDragOperation:(id)arg1;
- (BOOL)resignFirstResponder;
@property BOOL selected; // @synthesize selected=_selected;
- (void)setContentView:(id)arg1;
- (void)setDisclosed:(BOOL)arg1;
- (void)updateTrackingAreas;

@end

