/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTDisclosureHeaderView.h"

@interface IDECapsuleHeaderView : DVTDisclosureHeaderView
{
}

- (void)_endEditingTitleField;
- (void)_startEditingTitleFieldWithTitle:(id)arg1;
- (void)mouseDown:(id)arg1;

@end

