/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDEStructureEditingDropTarget-Protocol.h"
#import "IDEStructureEditingGroupingTarget-Protocol.h"
#import "IDEStructureEditingRemoveSubitemsTarget-Protocol.h"

@class IDEGroup;

@interface IDEContainerItemStructureEditingTarget : NSObject <IDEStructureEditingDropTarget, IDEStructureEditingGroupingTarget, IDEStructureEditingRemoveSubitemsTarget>
{
    IDEGroup *_targetGroup;
    id <DVTObservingToken> _targetGroupValidObservationToken;
}

+ (BOOL)_acceptDropAtIndex:(long long)arg1 withContext:(id)arg2;
+ (BOOL)_acceptDropAtIndex:(long long)arg1 withContext:(id)arg2 containerItems:(id)arg3;
+ (BOOL)_acceptDropAtIndex:(long long)arg1 withContext:(id)arg2 fileURLs:(id)arg3;
+ (void)_addFileURLsForContainerItem:(id)arg1 to:(id)arg2;
+ (id)_containerAddingItemsAssistantExtensionForContainer:(id)arg1;
+ (BOOL)_structureEditingAcceptDropWithContext:(id)arg1 index:(long long)arg2;
+ (id)_targetForStructureEditingOperation:(int)arg1 proposedNavigableItem:(id)arg2 proposedChildIndex:(long long)arg3 actualNavigableItem:(id *)arg4 actualChildIndex:(long long *)arg5;
- (BOOL)_acceptTemplateDropWithContext:(id)arg1 atIndex:(long long)arg2;
- (BOOL)_addNewSubgroupAtIndex:(unsigned long long)arg1 newGroupBlock:(id)arg2;
- (BOOL)_canGroupSubitemsAtIndexes:(id)arg1 groupIndex:(long long *)arg2 shouldGroup:(BOOL)arg3;
- (id)_initWithTargetGroup:(id)arg1;
- (BOOL)_structureEditingValidateDropWithContext:(id)arg1 atIndex:(long long)arg2;
- (BOOL)_testOrAddNewGroupAtChildIndex:(long long)arg1 shouldAdd:(BOOL)arg2;
- (unsigned long long)_validateTemplateDropWithContext:(id)arg1 atIndex:(long long)arg2;
- (unsigned long long)hash;
- (id)init;
- (id)insertSubitemsAssistantContext;
- (BOOL)isEqual:(id)arg1;
- (BOOL)structureEditingAcceptInsertionOfSubitemsForContext:(id)arg1 atIndex:(long long)arg2;
- (BOOL)structureEditingAddNewSubgroupAtIndex:(long long)arg1;
- (BOOL)structureEditingCanAddNewSubgroupAtIndex:(long long)arg1;
- (BOOL)structureEditingCanGroupSubitemsAtIndexes:(id)arg1;
- (BOOL)structureEditingCanRemoveSubitemsAtIndexes:(id)arg1;
- (id)structureEditingFileURLsForSubitemsAtIndexes:(id)arg1;
- (BOOL)structureEditingGroupSubitemsAtIndexes:(id)arg1 groupIndex:(long long *)arg2;
- (BOOL)structureEditingRemoveSubitemsAtIndexes:(id)arg1;
- (BOOL)structureEditingValidateInsertionOfSubitemsForContext:(id)arg1 atIndex:(long long)arg2;

@end

