/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IDEGroup, IDENavigableItem, IDENavigableItemCoordinator, IDEWorkspace, NSPopUpButton, NSSavePanel;

@interface IDECompletionDestinationManager : NSObject
{
    id <IDECompletionDestinationDelegate> _delegate;
    NSPopUpButton *_destinationPopUp;
    NSSavePanel *_savePanel;
    IDEWorkspace *_workspace;
    IDEGroup *_destinationGroup;
    IDENavigableItemCoordinator *_navigableItemCoordinator;
    IDENavigableItem *_workspaceNavigableItem;
}

- (void)activate;
- (void)addMenuItemsToPopUpButton:(id)arg1 menu:(id)arg2 forItem:(id)arg3 indentationLevel:(unsigned long long)arg4 items:(id)arg5;
- (void)deactivate;
@property id <IDECompletionDestinationDelegate> delegate; // @synthesize delegate=_delegate;
@property IDEGroup *destinationGroup; // @synthesize destinationGroup=_destinationGroup;
- (id)destinationGroupForMenuItem:(id)arg1;
@property NSPopUpButton *destinationPopUp; // @synthesize destinationPopUp=_destinationPopUp;
@property IDENavigableItemCoordinator *navigableItemCoordinator; // @synthesize navigableItemCoordinator=_navigableItemCoordinator;
- (void)populateDestinationGroupPopUp;
@property NSSavePanel *savePanel; // @synthesize savePanel=_savePanel;
- (void)selectedGroupDidChange:(id)arg1;
@property IDEWorkspace *workspace; // @synthesize workspace=_workspace;
- (BOOL)shouldAddItemToDestinationMenu:(id)arg1;
- (id)workspaceNavigableItem;

@end

