/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol IDECapsuleViewDelegate <NSObject>

@optional
- (BOOL)capsuleView:(id)arg1 acceptDrop:(id)arg2;
- (void)capsuleView:(id)arg1 setTitle:(id)arg2;
- (unsigned long long)capsuleView:(id)arg1 validateDrop:(id)arg2;
- (BOOL)capsuleViewCanBeRemoved:(id)arg1;
- (BOOL)capsuleViewCanBeRenamed:(id)arg1;
- (void)capsuleViewDidClickRemoveButton:(id)arg1;
- (id)capsuleViewTitleForEditing:(id)arg1;
- (BOOL)shouldDrawBorderBelowHeaderForCapsuleView:(id)arg1;
- (id)supportedDragTypes;
@end

