/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol IDEContainerUnlockingDelegate
- (void)container:(id)arg1 attemptToUnlockItems:(id)arg2 inWorkspaces:(id)arg3 completionQueue:(id)arg4 completionBlock:(id)arg5;
@end

