/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTStackView.h"

#import "DVTStatefulObject-Protocol.h"

@class DVTStateToken, IDECapsuleView, NSColor, NSString, NSTimer;

@interface IDECapsuleListView : DVTStackView <DVTStatefulObject>
{
    IDECapsuleView *_draggedView;
    id <IDECapsuleListViewDataSource> _dataSource;
    long long _dragDestinationIndex;
    NSTimer *_autoscrollTimer;
    NSColor *_backgroundColor;
    NSString *_emptyContentString;
    DVTStateToken *_stateToken;
    long long _selectedIndex;
    id _lastFirstResponder;
    BOOL _reloadAfterDrag;
    BOOL _restoringState;
    BOOL _togglingDisclosure;
    struct {
        unsigned int numberOfObjectsInCapsuleListView:1;
        unsigned int viewControllerForRow:1;
        unsigned int acceptDrop:1;
        unsigned int validateDrop:1;
        unsigned int writeRowWithIndex:1;
        unsigned int didCollapse:1;
        unsigned int didExpand:1;
        unsigned int didCompleteLayout:1;
    } _dataSourceRespondsTo;
}

+ (id)_subviewBottomShadow;
+ (id)_subviewTopShadow;
+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (long long)version;
- (void)_addBlockViewController:(id)arg1;
- (id)_animationForSubview:(id)arg1;
- (void)_autoscrollTimerCallback:(id)arg1;
- (BOOL)_dataSourceSupportsDragAndDrop;
- (id)_disclosedIndexes;
- (id)_frameRectsOfRearrangedSubviews;
- (BOOL)_isAnimatingSubview:(id)arg1;
- (BOOL)_isAnimationInProgress;
@property(readonly) BOOL _isDragging;
- (BOOL)_isMouseInCurrentEventOverSelf;
- (void)_layoutBottomUpWithAnimation:(BOOL)arg1;
- (id)_rearrangedSubviewsWhileDragging;
- (void)_reloadSubviews;
- (void)_setDisclosedIndexes:(id)arg1;
- (BOOL)_shouldAnimateLayout;
- (BOOL)_shouldFillEnclosingView;
- (void)_subviewFrameChanged:(id)arg1;
- (struct CGPoint)_swapThresholdForViewRect:(struct CGRect)arg1 draggingDown:(BOOL)arg2;
- (void)_updateSelectedIndex;
- (unsigned long long)_validateDropAtIndex:(long long)arg1 sender:(id)arg2;
- (BOOL)acceptsFirstResponder;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
@property NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (id)capsuleViewAtRow:(long long)arg1;
- (id)capsuleViewForCapsuleViewController:(id)arg1;
- (void)capsuleViewToggledDisclosure:(id)arg1;
- (void)capsuleViewToggledSelection:(id)arg1;
- (id)capsuleViews;
- (void)commitStateToDictionary:(id)arg1;
@property id <IDECapsuleListViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void)didCompleteLayout;
- (void)doCommandBySelector:(SEL)arg1;
- (void)draggingEnded:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingSourceOperationMaskForLocal:(BOOL)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
@property(copy) NSString *emptyContentString; // @synthesize emptyContentString=_emptyContentString;
- (BOOL)ignoreModifierKeysWhileDragging;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)isTopToBottom;
- (void)keyDown:(id)arg1;
- (void)layoutBottomUp;
- (void)mouseDown:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseUp:(id)arg1;
- (long long)numberOfRows;
- (BOOL)performDragOperation:(id)arg1;
- (BOOL)prepareForDragOperation:(id)arg1;
- (double)pulledSizeMagnitudeForSubview:(id)arg1;
- (struct CGPoint)pushedOriginForSubview:(id)arg1 position:(double)arg2;
- (struct CGSize)pushedSizeForSubview:(id)arg1;
- (void)reloadData;
- (void)revertStateWithDictionary:(id)arg1;
- (long long)rowForCapsuleView:(id)arg1;
- (void)scrollCapsuleViewToVisible:(id)arg1;
- (void)scrollRowToVisible:(long long)arg1;
@property long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property DVTStateToken *stateToken; // @synthesize stateToken=_stateToken;
- (struct CGSize)sizeForPulledSubviewMagnitude:(double)arg1;

@end

