/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@class NSImage, NSString;

@protocol IDECapsuleViewController <NSObject>
@property(readonly) NSString *titleForDisplay;

@optional
- (void)addItems:(id)arg1;
@property BOOL canAddItems;
@property(readonly) BOOL canRemove;
@property BOOL canRemoveItems;
@property(readonly) BOOL canRename;
@property(readonly) BOOL canUndisclose;
@property(readonly) BOOL disclosedByDefault;
@property(readonly) NSString *footerLabel;
@property(readonly) NSImage *icon;
- (void)remove:(id)arg1;
- (void)removeItems:(id)arg1;
- (void)setTitle:(id)arg1;
@end

