/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDEFontAndColorItem-Protocol.h"

@class NSString;

@interface IDEConsoleFontAndColorItem : NSObject <IDEFontAndColorItem>
{
    NSString *_colorPropertyName;
    NSString *_fontPropertyName;
    NSString *_displayName;
}

- (id)colorForTheme:(id)arg1;
- (id)displayName;
- (id)fontForTheme:(id)arg1;
- (id)initWithColorPropertyName:(id)arg1 fontPropertyName:(id)arg2 displayName:(id)arg3;
- (void)setColor:(id)arg1 forTheme:(id)arg2;
- (void)setFont:(id)arg1 forTheme:(id)arg2;

@end

