/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTCompletingTextView.h"

#import "DVTFindBarFindable-Protocol.h"
#import "DVTTextFindable-Protocol.h"

@class DVTTextCompletionDataSource, NSDictionary, NSMutableArray, NSString;

@interface IDEConsoleTextView : DVTCompletingTextView <DVTTextFindable, DVTFindBarFindable>
{
    id <IDEConsoleTextViewStandardIODelegate> _stdIODelegate;
    struct _NSRange _lastLineTextRange;
    long long _lastRemovableTextLocation;
    NSString *_promptString;
    DVTTextCompletionDataSource *_consoleTextViewcompletionsDataSource;
    NSDictionary *_debuggerPromptTextAttributes;
    NSDictionary *_debuggerInputTextAttributes;
    NSDictionary *_debuggerOutputTextAttributes;
    NSDictionary *_debuggedTargetInputTextAttributes;
    NSDictionary *_debuggedTargetOutputTextAttributes;
    NSDictionary *_textTypeToAttributes;
    NSMutableArray *_itemsToAppendAfterDelay;
    int _logMode;
}

+ (void)initialize;
- (void)_appendConsoleItem:(id)arg1;
- (void)_appendConsoleItemsWaitingToBeAppended;
- (void)_appendNonPromptConsoleItem:(id)arg1;
- (void)_appendPromptConsoleItem:(id)arg1;
- (void)_appendPromptString:(id)arg1;
- (id)_attributesForConsoleItem:(id)arg1;
- (void)_batchReplaceCharactersInRange:(struct _NSRange)arg1 withString:(id)arg2 attributes:(id)arg3 inRange:(struct _NSRange)arg4;
- (void)_commonInit;
- (struct _NSRange)_inputTextRange;
- (BOOL)_isValidForHistoryTracking;
- (void)_moveInsertionPointToEnd;
- (void)_processInputTextForCompleteLineAndSendToDelegate:(BOOL)arg1;
- (struct _NSRange)_rangeBeforeLastLineText;
- (id)_realString;
- (void)_reapplyAttributes;
- (void)_recreateAttributes;
- (void)_resetTypingAttributes;
- (void)_scrollToBottom;
- (void)_sendTextToTargetIfNecessary:(id)arg1;
- (BOOL)_shouldScrollToTheBottom;
- (void)_themeColorsUpdated;
- (void)appendConsoleItemAfterDelay:(id)arg1;
- (void)appendConsoleItemsAfterDelay:(id)arg1;
- (void)appendConsoleItemsImmediatlyWithoutScrolling:(id)arg1;
- (double)autoCompletionDelay;
- (void)awakeFromNib;
- (void)clearConsoleItems;
- (id)completionsDataSource;
- (void)dvtFindBar:(id)arg1 didUpdateCurrentResult:(id)arg2;
- (id)findStringMatchingDescriptor:(id)arg1 backwards:(BOOL)arg2 from:(id)arg3 to:(id)arg4;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)insertNewline:(id)arg1;
- (void)insertText:(id)arg1;
- (void)keyDown:(id)arg1;
@property struct _NSRange lastLineTextRange; // @synthesize lastLineTextRange=_lastLineTextRange;
@property int logMode; // @synthesize logMode=_logMode;
- (void)moveDown:(id)arg1;
- (void)moveToBeginningOfLineAndModifySelection:(id)arg1;
- (void)moveToBeginningOfParagraph:(id)arg1;
- (void)moveUp:(id)arg1;
- (void)paste:(id)arg1;
- (BOOL)readSelectionFromPasteboard:(id)arg1;
- (void)repeatInput:(id)arg1;
- (void)setCompletionStrategies:(id)arg1;
@property id <IDEConsoleTextViewStandardIODelegate> standardIODelegate; // @synthesize standardIODelegate=_stdIODelegate;
- (BOOL)shouldAutoCompleteAtLocation:(unsigned long long)arg1;
- (BOOL)shouldChangeTextInRange:(struct _NSRange)arg1 replacementString:(id)arg2;
- (id)startingLocationForFindBar:(id)arg1 findingBackwards:(BOOL)arg2;
- (id)userEnteredTextAfterPrompt;
- (id)userEnteredTextAfterPromptUpToLocation:(unsigned long long)arg1;
- (void)viewWillMoveToWindow:(id)arg1;
- (id)writablePasteboardTypes;

// Remaining properties
@property unsigned long long supportedMatchingOptions;

@end

