/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IDEWorkspace;

@interface IDEContextAutocreationController : NSObject
{
    IDEWorkspace *_workspace;
    id <DVTObservingToken> _loadingObservationToken;
    id <DVTObservingToken> _scanObservationToken;
    BOOL _batchAddingBlueprints;
    BOOL _needsBatchSchemeAutocreation;
}

+ (id)contextAutocreationControllerForWorkspace:(id)arg1;
+ (id)logAspect;
- (id)_configFromArray:(id)arg1 matchingPrefix:(id)arg2 preferringConfig:(id)arg3;
- (id)_newSchemeSpecifierForName:(id)arg1;
- (void)_setDefaultConfigurationsInScheme:(id)arg1 forBuildable:(id)arg2;
- (void)addBuildable:(id)arg1 toScheme:(id)arg2;
- (void)autocreateSchemesForcingAutocreate:(BOOL)arg1;
- (id)buildablesNotPartOfExistingContextAmongBuildables:(id)arg1;
- (id)buildablesToAutocreateSchemesForcedAutocreate:(BOOL)arg1;
- (id)candidateBuildablesForcedAutocreate:(BOOL)arg1;
- (id)createDefaultSchemeForBuildable:(id)arg1;
- (id)createSchemeForBuildable:(id)arg1 withName:(id)arg2;
- (void)didBatchAddMultipleBlueprints:(id)arg1;
- (id)initForWorkspace:(id)arg1;
- (BOOL)isAutocreationSuppressedForBuildable:(id)arg1;
- (id)parentBuildableForBuildable:(id)arg1;
- (void)suppressAutocreationForBuildables:(id)arg1;
- (void)willBatchAddMultipleBlueprints:(id)arg1;
@property(readonly) IDEWorkspace *workspace; // @synthesize workspace=_workspace;

@end

