/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEActivityReporter.h>

@interface IDECleanBuildFolderActivityReporter : IDEActivityReporter
{
    id <DVTObservingToken> _isCleaningObserver;
}

+ (void)initialize;
- (id)completionSummaryStringSegments;
- (id)initWithWorkspace:(id)arg1;
- (void)updateActivityReports;

@end

