/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTImageAndTextCell.h"

@interface IDEComponentDownloadsProgressCell : DVTImageAndTextCell
{
    BOOL _cancelable;
    id <_IDEComponentDownloadsButtonProvider> _buttonProvider;
}

- (void)_componentDownloadCell_commonInit;
- (BOOL)_showingProgress;
- (id)button;
- (struct CGRect)buttonCellRectForBounds:(struct CGRect)arg1;
@property id <_IDEComponentDownloadsButtonProvider> buttonProvider; // @synthesize buttonProvider=_buttonProvider;
@property BOOL cancelable; // @synthesize cancelable=_cancelable;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)init;
- (id)initTextCell:(id)arg1;
- (id)tooltipForPoint:(struct CGPoint)arg1 inRect:(struct CGRect)arg2;

@end

