/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEContainerItem.h"

@interface IDEContainerItem (IDEKit_ContainerItemSerialization)
+ (id)SE_PREFIX_containerItemsForContainerRelativeIdentifiers:(id)arg1;
+ (id)_SE_PREFIX_containerItemForContainer:(id)arg1 withContainerItemPathComponents:(id)arg2;
- (id)SE_PREFIX_containerRelativeIdentifier;
- (id)SE_PREFIX_itemIdentifier;
@end

