/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSDocumentController.h"

#import "IDEContainerErrorPresenter-Protocol.h"
#import "IDEContainerReloadingDelegate-Protocol.h"
#import "IDEContainerUnlockingDelegate-Protocol.h"
#import "IDEVersionedFileManagerDelegate-Protocol.h"

@class NSArray;

@interface IDEDocumentController : NSDocumentController <IDEVersionedFileManagerDelegate, IDEContainerErrorPresenter, IDEContainerReloadingDelegate, IDEContainerUnlockingDelegate>
{
    BOOL _isClosingAllDocuments;
}

+ (id)_THREAD_allEditorDocumentExtensions;
+ (id)_THREAD_allOrganizerSourceExtensions;
+ (id)_THREAD_bestEditorDocumentExtensionSupportingType:(id)arg1 withEditorCategories:(id)arg2;
+ (void)_THREAD_cacheBestEditorDocumentExtension:(id)arg1 forType:(id)arg2 withEditorCategory:(id)arg3;
+ (void)_THREAD_cacheDocumentClass:(Class)arg1 forExtension:(id)arg2;
+ (id)_THREAD_cachedBestEditorDocumentExtensionForType:(id)arg1 withEditorCategory:(id)arg2;
+ (Class)_THREAD_cachedDocumentClassForExtension:(id)arg1;
+ (Class)_THREAD_editorDocumentClassForType:(id)arg1 extension:(id *)arg2;
+ (id)_THREAD_editorDocumentExtensionForType:(id)arg1 withEditorCategories:(id)arg2;
+ (BOOL)_THREAD_type:(id)arg1 isPreferableToType:(id)arg2;
+ (id)_bestEditorDocumentExtensionForDocumentClass:(Class)arg1 supportingDocumentType:(id)arg2 withEditorCategories:(id)arg3;
+ (BOOL)_closeDocumentIfNeeded:(id)arg1;
+ (id)_documentExtensionForNavigableItem:(id)arg1;
+ (id)_editorDocumentExtensionsForOpenAsWhichSupportType:(id)arg1 editorCategories:(id)arg2;
+ (void)_enumerateDocumentExtensionsMatchingFileDataType:(id)arg1 withEditorCategories:(id)arg2 matchBlock:(id)arg3;
+ (BOOL)_isAllowedToCreateEditorDocumentForFileDataType:(id)arg1;
+ (BOOL)_isProjectDocumentURL:(id)arg1;
+ (BOOL)_isValidDocumentExtensionIdentifier:(id)arg1 supportingDocumentType:(id)arg2 withEditorCategories:(id)arg3;
+ (BOOL)_isValidDocumentExtensionIdentifier:(id)arg1 withEditorCategories:(id)arg2;
+ (BOOL)_isWorkspaceDocumentURL:(id)arg1;
+ (id)_openDocuments;
+ (id)_organizerSourceExtensionForDocumentType:(id)arg1;
+ (id)_readableTypesForDocumentClass:(Class)arg1;
+ (id)_retainedEditorDocumentForURL:(id)arg1 type:(id)arg2 error:(id *)arg3;
+ (id)_retainedNewEditorDocumentWithClass:(Class)arg1 forURL:(id)arg2 withContentsOfURL:(id)arg3 ofType:(id)arg4 extension:(id)arg5 error:(id *)arg6;
+ (void)_setOpenAsContextMenu:(id)arg1 withViewController:(id)arg2;
+ (id)_typeForContentsOfURL:(id)arg1;
+ (id)editorDocumentExtensionForFileDataType:(id)arg1 editorCategories:(id)arg2;
+ (id)editorDocumentExtensionForNavigableItem:(id)arg1 editorCategories:(id)arg2;
+ (id)editorDocumentForFilePath:(id)arg1;
+ (id)editorDocumentForNavigableItem:(id)arg1;
+ (id)editorDocumentForURL:(id)arg1;
+ (void)initialize;
+ (void)releaseEditorDocument:(id)arg1;
+ (void)retainEditorDocument:(id)arg1;
+ (id)retainedEditorDocumentForDocumentLocation:(id)arg1 error:(id *)arg2;
+ (id)retainedEditorDocumentForDocumentLocation:(id)arg1 forUseWithWorkspaceDocument:(id)arg2 error:(id *)arg3;
+ (id)retainedEditorDocumentForNavigableItem:(id)arg1 error:(id *)arg2;
+ (id)retainedEditorDocumentForNavigableItem:(id)arg1 forUseWithWorkspaceDocument:(id)arg2 error:(id *)arg3;
+ (id)sharedDocumentController;
- (Class)_THREAD_documentClassForType:(id)arg1 extension:(id *)arg2;
- (id)_addPath:(id)arg1 toChildrenOfWorkspace:(id)arg2;
- (BOOL)_applicationShouldTerminate;
- (void)_checkAndCloseAllDocumentsStartingWith:(id)arg1 shouldCloseDocuments:(BOOL)arg2 closeAllContext:(void *)arg3;
- (id)_containersForFilePaths:(id)arg1;
- (void)_dvt_closeAllDocumentsWithDelegate:(id)arg1 didCloseAllSelector:(SEL)arg2 shouldCloseAutosavingDocuments:(BOOL)arg3 contextInfo:(void *)arg4;
- (void)_editorDocument:(id)arg1 didPrint:(BOOL)arg2 contextInfo:(void *)arg3;
- (id)_frontmostSimpleFilesFocusedWorkspaceWindowForTopLevelFilePaths:(id)arg1;
- (id)_frontmostWorkspaceWindowForWorkspaces:(id)arg1 matched:(char *)arg2;
- (id)_getEditorDocumentsForFilePaths:(id)arg1 editedDocuments:(id *)arg2;
- (BOOL)_isWorkspaceWindow:(id)arg1 forWorkspaces:(id)arg2 matched:(char *)arg3;
- (void)_openAs:(id)arg1;
- (id)_openAsDocumentExtensionsForFileDataTypes:(id)arg1 editorCategories:(id)arg2;
- (id)_openDocumentsForURLs:(id)arg1 display:(BOOL)arg2 error:(id *)arg3;
- (id)_openProjectDocument:(id)arg1 displayDocument:(BOOL)arg2 error:(id *)arg3;
- (BOOL)_openProjectsAndWorkspaces:(id)arg1 documents:(id *)arg2 simpleFileURLs:(id *)arg3 display:(BOOL)arg4 error:(id *)arg5;
- (BOOL)_openSimpleFileURLs:(id)arg1 documents:(id *)arg2 display:(BOOL)arg3 error:(id *)arg4;
- (id)_openUntitledWorkspaceDocumentAndDisplay:(BOOL)arg1 simpleFilesFocused:(BOOL)arg2 editorDocumentURLOrNil:(id)arg3 error:(id *)arg4;
- (id)_openWorkspaceDocumentForWorkspace:(id)arg1 display:(BOOL)arg2 error:(id *)arg3;
- (void)_printDocumentsWithContentsOfURLs:(id)arg1 settings:(id)arg2 showPrintPanels:(BOOL)arg3 completionHandler:(id)arg4;
- (id)_recentEditorDocumentURLs;
- (id)_recentWorkspaceDocumentURLs;
- (void)_saveAllEditorDocuments:(id)arg1 includeReadOnly:(BOOL)arg2;
- (BOOL)_saveMultipleEditorDocuments:(id)arg1 withCancelButton:(BOOL)arg2 cancelButtonTitle:(id)arg3 dontSaveButton:(BOOL)arg4 title:(id)arg5;
- (BOOL)_saveMultipleEditorDocumentsWithCancelButton:(BOOL)arg1 cancelButtonTitle:(id)arg2 dontSaveButton:(BOOL)arg3 title:(id)arg4;
- (id)_setupOpenPanel;
- (BOOL)_workspace:(id)arg1 topLevelChildrenMatches:(id)arg2;
- (id)_workspaceOrProjectURLsInFolderURL:(id)arg1;
- (id)_workspacesForFileReferences:(id)arg1;
- (id)_wrappedWorkspacesForContainers:(id)arg1;
- (void)addDocument:(id)arg1;
- (BOOL)attemptRecoveryFromError:(id)arg1 optionIndex:(unsigned long long)arg2;
- (void)attemptRecoveryFromError:(id)arg1 optionIndex:(unsigned int)arg2 delegate:(id)arg3 didRecoverSelector:(SEL)arg4 contextInfo:(void *)arg5;
- (BOOL)canMoveItemsAtFilePaths:(id)arg1 toFilePaths:(id)arg2 completionBlockDispatchQueue:(struct dispatch_queue_s **)arg3 completionBlock:(id *)arg4;
- (BOOL)canRemoveItemsAtFilePaths:(id)arg1 completionBlockDispatchQueue:(struct dispatch_queue_s **)arg2 completionBlock:(id *)arg3;
- (void)closeAllDocumentsWithDelegate:(id)arg1 didCloseAllSelector:(SEL)arg2 contextInfo:(void *)arg3;
- (void)container:(id)arg1 attemptToUnlockItems:(id)arg2 inWorkspaces:(id)arg3 completionQueue:(id)arg4 completionBlock:(id)arg5;
- (id)currentDirectory;
- (id)defaultType;
- (id)displayNameForType:(id)arg1;
- (Class)documentClassForType:(id)arg1;
- (id)documentClassNames;
- (id)documentForURL:(id)arg1;
@property(readonly) NSArray *editedEditorDocuments;
@property(readonly) NSArray *editorDocuments;
@property(readonly) NSArray *editorDocumentsToManuallySave;
@property(readonly) NSArray *editorDocumentsToSave;
- (id)fileExtensionsFromType:(id)arg1;
- (int)handleSaveError:(id)arg1 forContainer:(id)arg2 withAction:(int)arg3;
- (id)init;
@property BOOL isClosingAllDocuments; // @synthesize isClosingAllDocuments=_isClosingAllDocuments;
- (id)makeDocumentWithContentsOfURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (void)menuNeedsUpdate:(id)arg1;
- (void)noteNewRecentDocumentURL:(id)arg1;
- (id)openDocumentLocation:(id)arg1 error:(id *)arg2;
- (id)openDocumentWithContentsOfURL:(id)arg1 display:(BOOL)arg2;
- (id)openDocumentWithContentsOfURL:(id)arg1 display:(BOOL)arg2 error:(id *)arg3;
- (id)openDocumentsWithContentsOfURLs:(id)arg1 display:(BOOL)arg2 error:(id *)arg3;
- (id)openUntitledWorkspaceDocumentAndDisplay:(BOOL)arg1 error:(id *)arg2;
- (void)removeDocument:(id)arg1;
- (int)responseToExternalChangesToBackingFileForContainer:(id)arg1 fileWasRemoved:(BOOL)arg2;
- (void)reviewUnsavedDocumentsWithAlertTitle:(id)arg1 cancellable:(BOOL)arg2 delegate:(id)arg3 didReviewAllSelector:(SEL)arg4 contextInfo:(void *)arg5;
- (void)runOpenPanelWithCompletionBlock:(id)arg1;
- (void)saveAllEditorDocuments:(id)arg1;
- (BOOL)saveAllEditorDocumentsBeforeActionWithTitle:(id)arg1 cancelButtonTitle:(id)arg2 allowNever:(BOOL)arg3;
- (BOOL)saveAllEditorDocumentsBeforeActionWithTitle:(id)arg1 cancelButtonTitle:(id)arg2 allowNever:(BOOL)arg3 allowDontSave:(BOOL)arg4;
- (BOOL)saveAllEditorDocumentsBeforeBuilding;
- (void)saveAllUnlockedEditorDocuments:(id)arg1;
- (void)saveEditorDocuments:(id)arg1;
- (void)saveMultipleEditorDocuments:(id)arg1;
- (BOOL)saveUntitledWorkspaceDocument:(id)arg1 forProjectDocument:(id)arg2 error:(id *)arg3;
- (id)typeForContentsOfURL:(id)arg1 error:(id *)arg2;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)willRemoveItemsAtFilePaths:(id)arg1;
@property(readonly) NSArray *workspaceDocuments;

@end

