/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEBaseDocumentNavigableItem.h>

@class DVTDocumentLocation;

@interface IDEDocumentURLNavigableItem : IDEBaseDocumentNavigableItem
{
    DVTDocumentLocation *_contentDocumentLocation;
}

- (id)_documentURL;
- (id)contentDocumentLocation;
- (id)documentType;
- (id)fileURL;
- (id)initWithRepresentedObject:(id)arg1;
- (id)name;
- (id)newImage;

@end

