/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEActivityReporter.h>

#import "IDEInitialization-Protocol.h"

@interface IDEDownloadablesActivityReporter : IDEActivityReporter <IDEInitialization>
{
}

+ (BOOL)ide_initializeWithOptions:(int)arg1 error:(id *)arg2;
+ (void)initialize;
- (id)initWithWorkspace:(id)arg1;

@end

