/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEDiagnosticItem.h"

@interface IDEDiagnosticItem (KitAdditions)
+ (id)keyPathsForValuesAffectingValid;
- (id)childExplorableItems;
- (id)exploredIssue;
- (BOOL)isNoteSeverity;
- (id)parentExplorableItem;
- (id)title;
- (BOOL)valid;
@end

