/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface IDEDeclarativeInspectorGenerator : NSObject
{
}

+ (id)generateInspectorInterfaceFromFile:(id)arg1 boundTo:(id)arg2;
+ (id)generateInspectorInterfaceFromXMLElement:(id)arg1 boundTo:(id)arg2;
+ (id)generateInterfaceFromXMLElement:(id)arg1 boundTo:(id)arg2;
+ (id)inspectorXMLElementsFromIncludeElement:(id)arg1 boundTo:(id)arg2;
+ (id)localizedStringForAttributeNamed:(id)arg1 inXMLElement:(id)arg2 fromInspectorController:(id)arg3;
+ (id)parseInterfaceXMLDocumentFromFile:(id)arg1;
+ (id)sectionHeaderTitleViewWithTitle:(id)arg1;
+ (id)standardBorderedView;

@end

