/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEExplorationContext.h>

@class IDEDiagnosticItem;

@interface IDEDiagnosticExplorationContext : IDEExplorationContext
{
    IDEDiagnosticItem *_diagnostic;
    BOOL _fixIt;
}

@property(readonly) IDEDiagnosticItem *diagnostic; // @synthesize diagnostic=_diagnostic;
- (int)explorationType;
- (id)initWithDiagnostic:(id)arg1 shouldFixIt:(BOOL)arg2;
@property BOOL shouldFixIt; // @synthesize shouldFixIt=_fixIt;

@end

