/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEDebugArea.h>

#import "DVTReplacementViewDelegate-Protocol.h"
#import "DVTSplitViewDelegate-Protocol.h"
#import "DVTStatefulObject-Protocol.h"

@class DVTExtension, DVTReplacementView, DVTSplitView, DVTSplitViewItem, DVTStateToken, IDEConsoleArea, NSImage, NSSegmentedControl;

@interface IDEDefaultDebugArea : IDEDebugArea <DVTReplacementViewDelegate, DVTSplitViewDelegate, DVTStatefulObject>
{
    DVTSplitView *_splitView;
    DVTReplacementView *_variablesReplacementView;
    DVTReplacementView *_consoleReplacementView;
    NSSegmentedControl *_variablesSwapButton;
    DVTExtension *_currentConsoleExtension;
    DVTExtension *_currentVariablesViewExtension;
    int _layoutMode;
    int _layoutFocusMode;
    double _variableViewWidthProportion;
    DVTSplitViewItem *_variablesViewSplitViewItem;
    DVTSplitViewItem *_consoleAreaSplitViewItem;
    int _restoreLayoutMode;
    int _restoreLayoutFocusMode;
    NSSegmentedControl *_consoleSwapButton;
    id <DVTObservingToken> _launchSessionObserver;
    id <DVTObservingToken> _miniDebuggerModeObserver;
    id <DVTObservingToken> _userMiniDebuggerModeObserver;
    NSImage *_consoleHasOutputImage;
    BOOL _consoleNotificationRegistered;
    BOOL _stillInMiniDebuggingMode;
}

+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (id)consoleHasOutputImage;
+ (id)consoleViewImage;
+ (id)splitImage;
+ (id)variablesViewImage;
+ (long long)version;
- (void)_adjustedHiddenSplitViewItemsMagitudeIfNeccessary;
- (void)_animateToLayoutMode:(int)arg1;
- (BOOL)_canShowBothViewsUsingWidth:(double)arg1;
- (double)_consoleAreaMinWidth;
- (void)_consoleHasOutput:(id)arg1;
- (double)_currentVariableViewWidthProportion;
- (void)_launchSessionChanged:(id)arg1;
- (int)_layoutModeForForcedCollapse;
- (void)_resizeBothVisibleSubviews;
- (void)_resizeOnlyVisibleSubview;
- (void)_setSideBySideModeEnabled:(BOOL)arg1;
- (void)_setupSwapSegmentedControl:(id)arg1;
- (void)_updateForDebuggingKVOChange;
- (void)_updateVisiblityOfVariablesViewSwapButton;
- (double)_variablesViewMinWidth;
- (void)activateConsole;
- (BOOL)canActivateConsole;
- (BOOL)canClearConsole;
- (void)clearConsole;
- (void)commitStateToDictionary:(id)arg1;
@property(readonly) IDEConsoleArea *consoleArea;
@property DVTExtension *currentConsoleExtension; // @dynamic currentConsoleExtension;
- (BOOL)delegateFirstResponder;
@property int layoutFocusMode; // @synthesize layoutFocusMode=_layoutFocusMode;
@property int layoutMode; // @synthesize layoutMode=_layoutMode;
- (void)loadView;
- (void)replacementView:(id)arg1 didInstallViewController:(id)arg2;
- (void)revertStateWithDictionary:(id)arg1;
@property BOOL shouldShowLayoutControl; // @dynamic shouldShowLayoutControl;
@property DVTStateToken *stateToken; // @dynamic stateToken;
- (void)setVariablesSwapControlHidden:(BOOL)arg1;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainSplitPosition:(double)arg2 ofSubviewAt:(long long)arg3;
- (void)splitView:(id)arg1 resizeSubviewsWithOldSize:(struct CGSize)arg2;
- (void)splitViewDidEndLiveResize:(id)arg1;
- (void)splitViewItemDidExpandOrCollapseBecauseUserDraggedDivider:(id)arg1;
- (void)splitViewWillStartLiveResize:(id)arg1;
- (id)stateSavingIdentifier;
- (void)toggleVariableConsoleView:(id)arg1;
- (void)viewDidInstall;
- (void)viewWillUninstall;
- (void)watchForConsoleOutput:(BOOL)arg1;

@end

