/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEDeclarativeInspectorDynamicVisibilityManager.h>

@class NSMapTable, NSView;

@interface IDEDeclarativeInspectorViewBasedDynamicVisibilityManager : IDEDeclarativeInspectorDynamicVisibilityManager
{
    NSMapTable *_identifierToBorderedViewsMap;
    BOOL _alternateBorderedViews;
    NSView *_view;
}

- (id)initWithView:(id)arg1 alternateSubViewBorderedViews:(BOOL)arg2 owner:(id)arg3;
- (void)reflowBorderedViews;
- (void)registerIdentifier:(id)arg1 forKeyPath:(id)arg2 withInstallBlock:(id)arg3 andUninstallBlock:(void)arg4;

@end

