/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

@class DVTFindBar, DVTScopeBarsManager, IDEEditorContext, IDEEditorDocument, IDEFileTextSettings, NSScrollView;

@interface IDEEditor : IDEViewController
{
    IDEEditorDocument *_document;
    IDEEditorDocument *_documentForNavBarStructure;
    IDEEditorContext *_editorContext;
    DVTFindBar *_findBar;
    id _documentForwarder;
    id <DVTTextFindable> _findableObject;
    id _documentDidChangeNotificationToken;
    id _documentForNavBarStructureDidChangeNotificationToken;
    IDEFileTextSettings *_fileTextSettings;
    id <IDEEditorDelegate> _delegate;
    BOOL _discardsFindResultsWhenContentChanges;
}

+ (BOOL)canProvideCurrentSelectedItems;
- (id)_getUndoManager:(BOOL)arg1;
- (id)_initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)createFindBar;
- (id)currentSelectedDocumentLocations;
- (id)currentSelectedItems;
@property id <IDEEditorDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didSetupEditor;
@property BOOL discardsFindResultsWhenContentChanges; // @synthesize discardsFindResultsWhenContentChanges=_discardsFindResultsWhenContentChanges;
@property(readonly) IDEEditorDocument *document; // @synthesize document=_document;
@property IDEEditorDocument *documentForNavBarStructure; // @synthesize documentForNavBarStructure=_documentForNavBarStructure;
- (id)documentForwarder;
@property IDEEditorContext *editorContext; // @synthesize editorContext=_editorContext;
- (void)editorContextDidHideFindBar;
@property IDEFileTextSettings *fileTextSettings; // @synthesize fileTextSettings=_fileTextSettings;
@property(readonly) DVTFindBar *findBar; // @synthesize findBar=_findBar;
@property(readonly) BOOL findBarSupported;
@property id <DVTTextFindable> findableObject; // @synthesize findableObject=_findableObject;
- (id)initUsingDefaultNib;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 document:(id)arg3;
- (void)invalidate;
@property(readonly, getter=isPrimaryEditor) BOOL primaryEditor;
@property(readonly) NSScrollView *mainScrollView;
- (void)navigateToAnnotationWithRepresentedObject:(id)arg1 wantsIndicatorAnimation:(BOOL)arg2 exploreAnnotationRepresentedObject:(id)arg3;
- (id)relatedMenuItemsForNavItem:(id)arg1;
@property(readonly) DVTScopeBarsManager *scopeBarsManager;
- (void)selectDocumentLocations:(id)arg1;
- (void)setNextResponder:(id)arg1;
- (void)setupContextMenuWithMenu:(id)arg1 withContext:(id)arg2;
- (void)takeFocus;
- (id)undoManager;

@end

