/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEActivityReporter.h>

@class NSMapTable;

@interface IDEExecutionActivityReporter : IDEActivityReporter
{
    id <DVTObservingToken> _launchSessionsStateObserverToken;
    NSMapTable *_reportForLaunchSessionTable;
}

+ (void)initialize;
- (id)_titleForLaunchSession:(id)arg1 prefix:(id)arg2;
- (id)initWithWorkspace:(id)arg1;
- (void)updateActivityReport:(id)arg1;

@end

