/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEViewController.h"

#import "IDEDebuggerBarEditorInfoProvider-Protocol.h"

@class DVTAutoLayoutView, DVTBorderedView, DVTReplacementView, DVTSplitView, DVTSplitViewItem, DVTStateToken, IDEDebugArea, IDEDebugBar, IDEEditorContext, IDEEditorDocument, IDEEditorModeViewController, IDENavigableItem, IDEWorkspaceTabControllerLayoutTree, NSMutableDictionary, NSView;

@interface IDEEditorArea : IDEViewController <IDEDebuggerBarEditorInfoProvider>
{
    NSView *_editorModeHostView;
    IDEEditorModeViewController *_editorModeViewController;
    int _editorMode;
    int _nonMiniDebuggingModeExtensionIdentifier;
    //id <DVTObservingToken> _workspaceActivityObserver;
    IDEEditorContext *_lastActiveEditorContext;
    IDEDebugBar *_activeDebuggerBar;
    IDEDebugArea *_activeDebuggerArea;
    NSMutableDictionary *_defaultPersistentRepresentations;
    DVTAutoLayoutView *_editorAreaAutoLayoutView;
    DVTAutoLayoutView *_debuggerAreaAutoLayoutView;
    DVTBorderedView *_debuggerBarBorderedView;
    DVTBorderedView *_debuggerAreaBorderedView;
    DVTReplacementView *_debuggerBarReplacementView;
    DVTReplacementView *_debuggerAreaReplacementView;
    DVTSplitView *_debuggerSplitView;
    DVTSplitViewItem *_debugAreaSplitViewItem;
    double _heightToReturnToDebuggerArea;
    id _launchSessionObserver;
  //  id <DVTObservingToken> _inMiniDebuggingModeObservingToken;
    IDEWorkspaceTabControllerLayoutTree *_layoutTreeForNavigationHUD;
    IDEWorkspaceTabControllerLayoutTree *_oldLayoutTreeFromStateSaving;
    BOOL _didInstall;
    BOOL _needsToRefreshContexts;
    BOOL _didRestoreState;
    BOOL _userWantsEditorVisible;
    BOOL _showDebuggerArea;
}

+ (BOOL)automaticallyNotifiesObserversOfLastActiveEditorContext;
+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (int)defaultEditorMode;
+ (id)keyPathsForValuesAffectingPrimaryEditorContext;
+ (id)keyPathsForValuesAffectingPrimaryEditorDocument;
+ (id)keyPathsForValuesAffectingSelectedMainNavigableItem;
+ (id)keyPathsForValuesAffectingShowEditor;
+ (long long)version;
- (void)_addAssistantEditor;
- (void)_addDebuggerBarToDebuggerArea;
- (void)_addDebuggerBarToEditorArea;
- (id)_addNewAssistantEditor;
- (void)_cacheDefaultPersistentRepresentation:(id)arg1 forDocumentExtensionIdentifier:(id)arg2 documentURL:(id)arg3;
- (BOOL)_canAddAssistantEditor;
- (BOOL)_canAddNewAssistantEditor;
- (BOOL)_canChangeAssistantEditorsLayout;
- (BOOL)_canRemoveAssistantEditor;
- (BOOL)_canResetEditor;
- (void)_clearDefaultPersistentRepresentationForDocumentExtensionIdentifier:(id)arg1 documentURL:(id)arg2;
- (void)_clearLayoutTreeForNavigationHUD;
- (id)_defaultPersistentRepresentationForDocumentExtensionIdentifier:(id)arg1 documentURL:(id)arg2;
- (void)_doRecordDebuggerSize;
- (id)_editorContexts;
- (id)_generateLayoutTreeForNavigationHUD;
- (void)_hideDebuggerBarAndResetSplitViewFrames;
- (void)_installDebugAreaWithExtensionID:(id)arg1 revertDebugAreaState:(BOOL)arg2;
- (void)_installDefaultDebugAreaAndRevertDebugAreaState:(BOOL)arg1;
- (void)_moveDebuggerBarToDebuggerArea;
- (void)_moveDebuggerBarToEditorArea;
- (void)_openEditorHistoryItem:(id)arg1 editorContext:(id)arg2 takeFocus:(BOOL)arg3;
- (void)_openEditorOpenSpecifier:(id)arg1 editorContext:(id)arg2 takeFocus:(BOOL)arg3;
- (void)_recordDebuggerSize;
- (void)_refreshEditorContextsAndPreserveCurrentEditorHistoryStack:(BOOL)arg1;
- (void)_removeAssistantEditor;
- (void)_resetEditor;
- (void)_resetSplitViewFrames;
- (void)_resizeSubviewsForHeightDecrease:(double)arg1;
- (void)_resizeSubviewsForHeightIncrease:(double)arg1;
- (void)_setAssistantEditorsLayout:(int)arg1;
- (void)_setEditorMode:(int)arg1;
- (void)_setEditorModeViewControllerWithPrimaryEditorContext:(id)arg1;
- (void)_setShowDebuggerArea:(BOOL)arg1 animate:(BOOL)arg2;
- (void)_updateDebuggerBarVisibility;
- (void)_updateStateSavingRegistrations;
- (void)activateConsole:(id)arg1;
@property(readonly) IDEDebugArea *activeDebuggerArea; // @synthesize activeDebuggerArea=_activeDebuggerArea;
@property(readonly) IDEDebugBar *activeDebuggerBar; // @synthesize activeDebuggerBar=_activeDebuggerBar;
- (BOOL)commitEditingForAction:(int)arg1 errors:(id)arg2;
- (void)commitStateToDictionary:(id)arg1;
@property(readonly) DVTReplacementView *debuggerAreaReplacementView; // @synthesize debuggerAreaReplacementView=_debuggerAreaReplacementView;
- (void)discardEditing;
- (void)editorContextDidBecomeLastActiveEditor:(id)arg1;
- (void)editorContextWasRemoved:(id)arg1;
@property(readonly) int editorMode; // @synthesize editorMode=_editorMode;
//@property IDEEditorModeViewController *editorModeViewController; // @synthesize editorModeViewController=_editorModeViewController;
- (void)installDebugAreaWithExtensionID:(id)arg1;
- (void)installDefaultDebugArea;
//@property IDEEditorContext *lastActiveEditorContext; // @synthesize lastActiveEditorContext=_lastActiveEditorContext;
//@property(readonly) IDEWorkspaceTabControllerLayoutTree *layoutTreeForNavigationHUD;
- (void)loadView;
@property(readonly) IDEEditorContext *primaryEditorContext;
@property(readonly) IDEEditorDocument *primaryEditorDocument;
- (void)revertStateWithDictionary:(id)arg1;
@property(readonly) IDENavigableItem *selectedMainNavigableItem;
- (void)setEditorMode:(int)arg1 completionBlock:(id)arg2;
- (void)setLayoutTreeForNavigationHUD:(id)arg1;
@property BOOL showDebuggerArea;
@property BOOL showEditor;
- (void)setStateSavingDefaultPersistentRepresentations:(id)arg1;
//@property DVTStateToken *stateToken; // @dynamic stateToken;
@property BOOL userWantsEditorVisible; // @synthesize userWantsEditorVisible=_userWantsEditorVisible;
- (void)showDebuggerArea:(id)arg1;
@property(readonly) BOOL showDebuggerBar;
- (struct CGRect)splitView:(id)arg1 additionalEffectiveRectOfDividerAtIndex:(long long)arg2;
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainSplitPosition:(double)arg2 ofSubviewAt:(long long)arg3;
- (struct CGRect)splitView:(id)arg1 effectiveRect:(struct CGRect)arg2 forDrawnRect:(struct CGRect)arg3 ofDividerAtIndex:(long long)arg4;
- (void)splitView:(id)arg1 resizeSubviewsWithOldSize:(struct CGSize)arg2;
- (id)stateSavingDefaultPersistentRepresentations;
- (void)toggleDebuggerVisibility:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)viewDidInstall;
- (void)viewWillUninstall;

@end

