/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEEditor.h>

@class DVTLozengeTextField, IDEFirstResponderView, NSProgressIndicator, NSString;

@interface IDEEditorEmpty : IDEEditor
{
    NSString *_emptyContentString;
    IDEFirstResponderView *_firstResponderView;
    DVTLozengeTextField *_lozengeTextField;
    NSProgressIndicator *_progressIndicator;
    id <DVTObservingToken> _workspaceActivityObserver;
    BOOL _hideWorkspaceLoadingProgressIndicator;
}

- (void)_centerViewInSuperView:(id)arg1;
- (void)_finishViewDidInstall;
@property BOOL hideWorkspaceLoadingProgressIndicator; // @synthesize hideWorkspaceLoadingProgressIndicator=_hideWorkspaceLoadingProgressIndicator;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 document:(id)arg3;
- (void)invalidate;
- (void)loadView;
- (void)setEmptyContentString:(id)arg1;
- (void)viewDidInstall;
- (void)viewWillUninstall;

@end

