/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTDelayedMenuGradientImageButton, NSArray, NSMutableArray;

@interface IDEEditorHistoryController : NSObject
{
    NSMutableArray *_previousHistoryItems;
    NSMutableArray *_nextHistoryItems;
    DVTDelayedMenuGradientImageButton *_backButton;
    DVTDelayedMenuGradientImageButton *_forwardButton;
    id <IDEEditorContextProtocol> _editorContext;
}

+ (id)_historyButtonWithImageNamed:(id)arg1 width:(double)arg2 height:(double)arg3;
+ (void)initialize;
+ (id)keyPathsForValuesAffectingCanGoBackByCommand;
+ (id)keyPathsForValuesAffectingCanGoForwardByCommand;
+ (id)keyPathsForValuesAffectingCanSelectBackButton;
+ (id)keyPathsForValuesAffectingCanSelectForwardButton;
- (void)_goByButtonClickGoingForward:(BOOL)arg1;
- (void)_goByMenuCommandGoingForward:(BOOL)arg1;
- (void)_goNowhere;
- (void)_goToEditorHistoryItem:(id)arg1;
- (id)_historyButtonMenuWithDirectionForward:(BOOL)arg1;
- (id)_lastHistoryItemNotMatchingDocumentURL:(id)arg1 goingForward:(BOOL)arg2 removeMatchingHistoryItems:(BOOL)arg3;
- (void)_removeUnreachableHistoryItemsGoingForward:(BOOL)arg1;
- (void)addHistoryEditorHistoryItem:(id)arg1 filterAdjacentEntriesWithIdenticalNavigableItems:(BOOL)arg2;
@property(readonly) DVTDelayedMenuGradientImageButton *backButton; // @synthesize backButton=_backButton;
@property(readonly) BOOL canGoBackByCommand;
@property(readonly) BOOL canGoForwardByCommand;
@property(readonly) BOOL canSelectBackButton;
- (BOOL)canSelectButtonGoingForward:(BOOL)arg1;
@property(readonly) BOOL canSelectForwardButton;
@property(readonly) DVTDelayedMenuGradientImageButton *forwardButton; // @synthesize forwardButton=_forwardButton;
- (void)goBackInHistoryByCommand:(id)arg1;
- (void)goBackInHistoryByCommandWithAlternate:(id)arg1;
- (void)goBackInHistoryByCommandWithShiftPlusAlternate:(id)arg1;
- (void)goBackInHistoryEntryByButtonClick:(id)arg1;
- (void)goBackInHistoryToThisEntry:(id)arg1;
- (id)goBackMenu;
- (void)goForwardInHistoryByButtonClick:(id)arg1;
- (void)goForwardInHistoryByCommand:(id)arg1;
- (void)goForwardInHistoryByCommandWithAlternate:(id)arg1;
- (void)goForwardInHistoryByCommandWithShiftPlusAlternate:(id)arg1;
- (void)goForwardInHistoryToThisEntry:(id)arg1;
- (id)goForwardMenu;
- (BOOL)goToHistoryItemInThisEditorContext:(id)arg1 forward:(BOOL)arg2 captureHistory:(BOOL)arg3;
- (id)initWithEditorContext:(id)arg1 navBarHeight:(double)arg2;
- (void)navigateAwayFromCurrentDocumentWithURL:(id)arg1;
- (BOOL)openExternalEditorHistoryItem:(id)arg1;

// Remaining properties
@property(readonly) NSMutableArray *mutableNextHistoryItems; // @dynamic mutableNextHistoryItems;
@property(readonly) NSMutableArray *mutablePreviousHistoryItems; // @dynamic mutablePreviousHistoryItems;
@property(copy) NSArray *nextHistoryItems; // @dynamic nextHistoryItems;
@property(copy) NSArray *previousHistoryItems; // @dynamic previousHistoryItems;

@end

