/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSDocument.h"

#import "IDEReadOnlyItem-Protocol.h"

@class DVTExtension, DVTFileDataType, DVTFilePath, DVTStackBacktrace, DVTUndoManager, NSDictionary, NSMutableArray, NSMutableSet, NSURL;

@interface IDEEditorDocument : NSDocument <IDEReadOnlyItem>
{
    DVTExtension *_extension;
    NSMutableSet *_documentEditors;
    NSMutableArray *_pendingChanges;
    DVTStackBacktrace *_creationBacktrace;
    DVTStackBacktrace *_invalidationBacktrace;
    int _readOnlyStatus;
    DVTFilePath *_filePath;
    DVTUndoManager *_dvtUndoManager;
    id _willUndoChangeNotificationToken;
    id _willRedoChangeNotificationToken;
    NSURL *_ide_representedURL;
    DVTFileDataType *_ide_hintedFileDataType;
    NSDictionary *_willCloseNotificationUserInfo;
    struct dispatch_semaphore_s *_saveWaiter;
    BOOL _inSetUndoManager;
    BOOL _isClosing;
    BOOL _isClosingForRevert;
    BOOL _isSaving;
    BOOL _isInvalidated;
    BOOL _wholeDocumentChanged;
    BOOL _trackFileSystemChanges;
    BOOL _calledEditorDocumentWillClose;
    BOOL _calledEditorDocumentDidClose;
    BOOL _didDisableAutomaticTermination;
    BOOL _isUnlockingDocument;
    BOOL _isUndoingAfterFailureToUnlockDocument;
    BOOL _ide_isRepresentationEditable;
    BOOL _ide_isTemporaryDocument;
}

+ (BOOL)_presentsVersionsUserInterface;
+ (BOOL)_shouldShowUtilititesAreaAtLoadForSimpleFilesFocusedWorkspace;
+ (void)_validateDocumentExtension:(id)arg1;
+ (BOOL)autosavesInPlace;
+ (id)editedFileContents;
+ (void)initialize;
+ (id)readableTypes;
+ (BOOL)shouldTrackFileSystemChanges;
+ (BOOL)shouldUnlockFileURLBeforeMakingChanges;
- (void)_assertImplementsBothOrNeitherInitMethod;
- (void)_changeWasDone:(id)arg1;
- (void)_changeWasUndone:(id)arg1;
- (BOOL)_checkAutosavingPossibilityAndReturnError:(id *)arg1;
- (id)_documentEditors;
- (void)_editorDocumentDidClose;
- (void)_editorDocumentWillClose;
- (void)_handleDocumentFileChanges:(id)arg1;
- (void)_invalidate;
- (BOOL)_isClosing;
- (void)_respondToFileChangeOnDiskWithFilePath:(id)arg1;
- (void)_sendOutDocumentUpdateLocation;
- (int)_underlyingFileReadOnlyStatus;
- (void)_unlockIfNeededCompletionBlock:(id)arg1;
- (BOOL)_windowForSheet:(id *)arg1 workspaceForSheet:(id *)arg2 editor:(id *)arg3;
- (BOOL)canRevert;
@property(readonly) BOOL canSave;
@property(readonly) BOOL canSaveAs;
- (BOOL)checkAutosavingSafetyAndReturnError:(id *)arg1;
- (void)close;
- (void)closeToRevert;
- (void)continueFileAccessUsingBlock:(id)arg1;
@property(readonly) DVTStackBacktrace *creationBacktrace; // @synthesize creationBacktrace=_creationBacktrace;
- (id)dataOfType:(id)arg1 error:(id *)arg2;
- (id)diffDataSource;
- (void)duplicateDocument:(id)arg1;
- (id)editedContents;
- (void)editorDocumentDidClose;
- (void)editorDocumentWillClose;
- (id)emptyPrivateCopy;
- (void)encodeRestorableStateWithCoder:(id)arg1;
@property DVTExtension *extension; // @synthesize extension=_extension;
- (id)fileNameExtensionForType:(id)arg1 saveOperation:(unsigned long long)arg2;
@property DVTFilePath *filePath; // @synthesize filePath=_filePath;
- (BOOL)hasBeenEditedSinceLastUserInitiatedSave;
- (void)ide_didFixupChangeCountWithWasEdited:(BOOL)arg1 didHaveEditsSinceLastUserInitiatedSave:(BOOL)arg2 changeString:(id)arg3;
- (id)ide_displayName;
- (void)ide_finishSaving:(BOOL)arg1 forSaveOperation:(unsigned long long)arg2 previousPath:(id)arg3;
@property DVTFileDataType *ide_hintedFileDataType;
@property BOOL ide_isRepresentationEditable;
@property BOOL ide_isTemporaryDocument;
@property(readonly) BOOL ide_isTextRepresentation;
@property(copy) NSURL *ide_representedURL;
- (void)ide_setUndoManager:(id)arg1;
- (id)init;
- (id)initForURL:(id)arg1 withContentsOfURL:(id)arg2 ofType:(id)arg3 error:(id *)arg4;
- (id)initWithContentsOfURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (id)initWithType:(id)arg1 error:(id *)arg2;
@property(readonly) DVTStackBacktrace *invalidationBacktrace; // @synthesize invalidationBacktrace=_invalidationBacktrace;
@property(readonly, getter=isClosed) BOOL closed;
- (BOOL)isClosingForRevert;
- (BOOL)makeWritableWithError:(id *)arg1;
- (id)newUndoManager;
- (id)printOperationWithSettings:(id)arg1 error:(id *)arg2;
- (id)privateCopy;
- (BOOL)readFromData:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
@property(readonly) NSURL *readOnlyItemURL;
@property int readOnlyStatus; // @synthesize readOnlyStatus=_readOnlyStatus;
- (void)registerDocumentEditor:(id)arg1;
- (void)restoreDocumentWindowWithIdentifier:(id)arg1 state:(id)arg2 completionHandler:(id)arg3;
- (void)restoreStateWithCoder:(id)arg1;
- (void)revertDocumentToSaved:(id)arg1;
- (BOOL)revertToContentsOfURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (void)saveDocument:(id)arg1;
- (void)saveDocumentAs:(id)arg1;
- (BOOL)saveForOperation:(unsigned long long)arg1 error:(id *)arg2;
- (void)saveForOperation:(unsigned long long)arg1 withCompletionHandler:(id)arg2;
- (void)saveToURL:(id)arg1 ofType:(id)arg2 forSaveOperation:(unsigned long long)arg3 completionHandler:(id)arg4;
- (id)sdefSupport_displayName;
- (void)setFileURL:(id)arg1;
- (void)setHasUndoManager:(BOOL)arg1;
- (void)setSdefSupport_displayName:(id)arg1;
@property BOOL trackFileSystemChanges; // @synthesize trackFileSystemChanges=_trackFileSystemChanges;
- (void)setUndoManager:(id)arg1;
- (void)setupUndoManager:(id)arg1;
- (void)teardownUndoManager:(id)arg1;
- (id)undoManager;
- (void)unregisterDocumentEditor:(id)arg1;
- (void)updateChangeCount:(unsigned long long)arg1;
- (void)updateChangeCountWithToken:(id)arg1 forSaveOperation:(unsigned long long)arg2;
- (void)updateChangedLocation:(id)arg1;
- (id)updatedLocationFromLocation:(id)arg1 toTimestamp:(double)arg2;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (id)windowForSheet;
- (BOOL)writeSafelyToURL:(id)arg1 ofType:(id)arg2 forSaveOperation:(unsigned long long)arg3 error:(id *)arg4;

@end

