/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol IDEEditorContextDelegate <NSObject>

@optional
- (void)_editorContext:(id)arg1 openingEmptyEditorInsteadOfNavigableItem:(id)arg2;
- (void)addSplitForEditorContext:(id)arg1;
- (BOOL)canCloseDocumentForEditorContext:(id)arg1;
- (void)editorContext:(id)arg1 didSetNavigableItem:(id)arg2;
- (void)editorContext:(id)arg1 didUpdateMenu:(id)arg2;
- (void)editorContext:(id)arg1 editorStateRepositoryDidChange:(id)arg2;
- (BOOL)editorContext:(id)arg1 emptyEditorRootNavigableItem:(id *)arg2 selectedNavigableItem:(id *)arg3;
- (id)editorContext:(id)arg1 navigableItemForEditingFromArchivedRepresentation:(id)arg2 error:(id *)arg3;
- (id)editorContext:(id)arg1 relatedMenuItemsForNavItem:(id)arg2;
- (void)editorContextDidBecomeLastActiveEditor:(id)arg1;
- (id)primaryEditorContext;
- (BOOL)provideWorkspaceStructureForEmptyEditorContext:(id)arg1;
- (void)removeSplitForEditorContext:(id)arg1;
- (id)workspaceForEditorContext:(id)arg1;
@end

