/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEEditorStepperView.h>

@class NSTextField;

@interface IDEEditorNumberStepperView : IDEEditorStepperView
{
    NSTextField *_countTextField;
}

+ (id)_countTextField;
- (struct CGSize)centerViewSizeInHeight:(double)arg1;
- (id)newCenterView;

@end

