/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDENavigableItem.h>

@class DVTFileDataType, NSImage, NSURL;

@interface IDEFileNavigableItem : IDENavigableItem
{
    id _document;
    NSImage *_image;
    id <DVTObservingToken> _documentObservingToken;
    BOOL _invalidatingTopLevelObjects;
}

- (void)_documentDidClose;
- (id)_editorDocument;
- (void)_updateEditorDocument:(id)arg1;
- (id)childRepresentedObjects;
- (id)contentDocumentLocation;
- (void)dispose;
@property(readonly) DVTFileDataType *documentType;
@property(readonly) NSURL *fileURL;
- (id)identifierForChildItem:(id)arg1;
- (id)image;
- (unsigned long long)indexOfChildItemForIdentifier:(id)arg1;
- (void)invalidateChildItems;
- (void)invalidateImage;
- (BOOL)isDocumentNavigableItem;
- (BOOL)isLeaf;
- (BOOL)isMajorGroup;
- (id)newImage;
@property(readonly) long long progress;
- (id)structureProvidingEditorDocument;
- (id)textColor;
- (void)updateImage;

@end

