/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEInspectorProperty.h>

@class IDEFileIdentityAndType, NSPopUpButton;

@interface IDEFileIdentityAndTypePopupController : IDEInspectorProperty
{
    NSPopUpButton *_popup;
}

+ (id)keyPathsForValuesAffectingFileTypeValue;
- (BOOL)_canSelectFileTypeDirectory;
- (BOOL)_canSelectFileTypeFile;
- (id)_multipleValuesValue;
- (id)_nullValue;
- (void)_populatePopup;
- (void)_restorePopup;
- (void)_selectFileTypeMenuItem:(id)arg1;
- (void)_updateDefaultItemTitle;
- (void)_updateMenuforMultipleValuesItem;
- (void)_updateSelection;
- (id)bindAndConfigure;
- (id)displayedGroups;
- (id)fileTypeValue;
- (id)initWithPropertyDefinition:(id)arg1 andController:(id)arg2;
@property(retain) IDEFileIdentityAndType *inspectorController;
- (id)nibBundle;
- (void)setFileTypeValue:(id)arg1;

@end

