/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEFileNavigableItem.h>

@class DVTFileDataType, NSColor, NSString, NSURL;

@interface IDEFileReferenceNavigableItem : IDEFileNavigableItem
{
    NSURL *_fileURL;
    DVTFileDataType *_fileDataType;
    NSString *_name;
    NSString *_scmCurrentRevision;
    NSString *_scmLocalStatus;
    NSString *_scmServerStatus;
    struct {
        unsigned int _needUpdateForFileURL:1;
        unsigned int _reserved:31;
    } _ideFileRefNavItemflags;
}

+ (id)_createExtraInfoObject;
+ (void)editorDocumentDirtyStatusDidChange:(id)arg1;
+ (void)initialize;
+ (id)keyPathsForValuesAffectingToolTip;
- (unsigned long long)conflictStateForUpdateOrMerge;
- (id)contentDocumentLocation;
- (id)documentType;
- (id)fileReference;
- (id)fileURL;
- (id)initWithRepresentedObject:(id)arg1;
- (id)name;
- (id)newImage;
- (id)sourceControlCurrentRevision;
- (id)sourceControlLocalStatus;
- (int)sourceControlLocalStatusFlag;
- (id)sourceControlServerStatus;
- (int)sourceControlServerStatusFlag;
@property(readonly) NSColor *textColor;
- (id)toolTip;
- (void)updateAttributes;
- (void)updateChildRepresentedObjects;

@end

