/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEMediaRepository.h>

@class IDEContainer, IDEFileReferenceContainerObserver, NSMapTable, NSSet, NSTimer;

@interface IDEFileMediaRepository : IDEMediaRepository
{
    id <DVTObservingToken> _kvoContainerValidToken;
    IDEFileReferenceContainerObserver *_observer;
    id <DVTInvalidation> _observingToken;
    NSMapTable *_resourcesByPath;
    NSTimer *_discardTimer;
    BOOL _wasDiscarded;
}

+ (void)discardMediaRepositoryForContainerObserver:(id)arg1;
+ (id)mediaRepositoryForContainer:(id)arg1 types:(id)arg2;
+ (id)mediaRepositoryForContainerObserver:(id)arg1;
+ (id)staticContainerObserverToRepositoryMap;
- (id)addObserverWithBlock:(id)arg1;
@property(readonly) IDEContainer *container;
- (void)discard;
- (id)initWithContainerObserver:(id)arg1;
- (void)removeObserver:(id)arg1;
- (id)resources;
- (void)startDiscardTimer;
- (void)stopDiscardTimer;
@property(readonly) NSSet *types;

@end

