/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSTableView.h"

@class NSColor;

@interface IDEFontAndColorCategoriesTableView : NSTableView
{
    NSColor *_selectionColor;
}

- (id)_highlightColorForCell:(id)arg1;
@property(copy) NSColor *selectionColor; // @synthesize selectionColor=_selectionColor;

@end

