/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTBorderedView.h"

@class DVTSearchField, NSMenu, NSString;

@interface IDEFilterControlBar : DVTBorderedView
{
    DVTSearchField *_searchField;
    id <IDEFilterControlBarTarget> _filterTarget;
    id _filterLeftButton;
    NSString *_filterDefinitionIdentifier;
}

- (void)_didSetFilterTarget;
- (void)_updateSearchButtonCell;
- (void)_willSetFilterTarget;
- (id)filterDefinitionExtension;
@property(copy) NSString *filterDefinitionIdentifier; // @synthesize filterDefinitionIdentifier=_filterDefinitionIdentifier;
@property id <IDEFilterControlBarTarget> filterTarget; // @synthesize filterTarget=_filterTarget;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)newToggleButtonWithParameters:(id)arg1;
@property DVTSearchField *searchField; // @synthesize searchField=_searchField;
@property(copy) NSMenu *searchMenuTemplate;
- (void)setUpFilterControls;

@end

