/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "NSTableViewDelegate-Protocol.h"

@class DVTReplacementView, DVTTabChooserView, NSArray, NSArrayController, NSBox, NSColor, NSFont, NSObjectController, NSTableView, NSView;

@interface IDEFontAndColorPrefsPaneController : IDEViewController <NSTableViewDelegate>
{
    DVTReplacementView *preferenceSetReplacementView;
    DVTTabChooserView *_tabChooserView;
    NSTableView *_fontAndColorItemTable;
    NSArrayController *_categoriesArrayController;
    NSObjectController *_currentThemeObjectController;
    NSBox *_generalBox;
    NSView *_sourceEditorGeneralView;
    NSView *_consoleGeneralView;
    NSArray *_fontAndColorItems;
    id <DVTObservingToken> _selectedTabObserver;
    id <DVTObservingToken> _backgroundColorObserver;
    id <DVTObservingToken> _selectionIndexesObserver;
}

+ (void)initialize;
- (void)_handleTabChanged;
- (void)_initTabChooserView;
- (void)_sourceTextColorsChanged:(id)arg1;
- (id)_theme;
- (void)_updateBindingsBasedOnSelectedTab;
- (void)_updateFontPickerAndColorWell;
@property(readonly) NSArrayController *categoriesArrayController; // @synthesize categoriesArrayController=_categoriesArrayController;
- (void)changeFont:(id)arg1;
- (void)chooseFont:(id)arg1;
@property(copy) NSColor *combinedSyntaxColor;
@property(copy) NSFont *combinedSyntaxFont;
@property NSArray *fontAndColorItems; // @synthesize fontAndColorItems=_fontAndColorItems;
- (void)loadView;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;

@end

