/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDENavigableItem.h>

@class NSArray, NSString;

@interface IDEGroupNavigableItem : IDENavigableItem
{
    NSString *_name;
    NSArray *_subitems;
    NSString *_scmLocalStatus;
    NSString *_scmServerStatus;
}

+ (id)_createExtraInfoObject;
+ (id)keyPathsForValuesAffectingToolTip;
- (id)_group;
- (id)childRepresentedObjects;
- (unsigned long long)conflictStateForUpdateOrMerge;
- (id)contentDocumentLocation;
- (id)documentType;
- (id)fileReference;
- (id)identifierForChildItem:(id)arg1;
- (id)image;
- (unsigned long long)indexOfChildItemForIdentifier:(id)arg1;
- (id)initWithRepresentedObject:(id)arg1;
- (BOOL)isLeaf;
- (BOOL)isMajorGroup;
- (id)name;
- (id)sourceControlLocalStatus;
- (int)sourceControlLocalStatusFlag;
- (id)sourceControlServerStatus;
- (int)sourceControlServerStatusFlag;
- (id)toolTip;
- (void)updateAttributes;
- (void)updateChildRepresentedObjects;

@end

