/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTAutoLayoutView.h"

@class NSArray;

@interface IDEInspectorResizableMatrix : DVTAutoLayoutView
{
    NSArray *buttonRows;
}

- (id)buttonRows;
- (void)clearState;
- (void)layoutTopDown;
- (void)setButtonRows:(id)arg1;
- (void)setOnStateForValue:(long long)arg1;

@end

