/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IDEInspectorChooserCategory, NSImage, NSMenuItem, NSString, NSView;

@interface IDEInspectorChooserChoice : NSObject
{
    id viewInitializingBlock;
    IDEInspectorChooserCategory *category;
    NSMenuItem *menuItem;
    id <NSCopying> value;
    NSString *title;
    NSImage *image;
    NSView *view;
    BOOL separator;
}

+ (id)separatorChoice;
@property IDEInspectorChooserCategory *category; // @synthesize category;
@property(readonly) NSImage *image; // @synthesize image;
- (id)initWithTitle:(id)arg1 image:(id)arg2 value:(id)arg3 andView:(id)arg4;
- (id)initWithTitle:(id)arg1 image:(id)arg2 value:(id)arg3 sliceXML:(id)arg4 inspectorController:(id)arg5;
@property(getter=isSeparator) BOOL separator; // @synthesize separator;
@property NSMenuItem *menuItem; // @synthesize menuItem;
@property(readonly) NSString *title; // @synthesize title;
@property(readonly) id <NSCopying> value; // @synthesize value;
@property(readonly) NSView *view; // @synthesize view;

@end

