/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "IDEBindableDeclarativeInspectorController-Protocol.h"
#import "NSUserInterfaceValidations-Protocol.h"

@class DVTDelayedValidator, IDEInspectorCategoryController, IDEUtilityArea, NSArray, NSArrayController, NSBundle, NSDictionary, NSMutableDictionary, NSView<DVTIssueDisplayingView>;

@interface IDEInspectorViewController : IDEViewController <NSUserInterfaceValidations, IDEBindableDeclarativeInspectorController>
{
    NSArrayController *_inspectedDocumentsController;
    NSArrayController *_inspectedObjectsController;
    NSArray *_content;
    NSArray *_inspectedDocuments;
    id _selectionProxy;
    id _selectedDocumentsProxy;
    NSDictionary *_issueInfoDictionary;
    NSView<DVTIssueDisplayingView> *_issueDisplayingView;
    IDEInspectorCategoryController *_categoryController;
    IDEUtilityArea *_utilityArea;
    NSMutableDictionary *_keyPathTriggeringReloadObservers;
    DVTDelayedValidator *_reloadInspectorDelayedValidator;
}

+ (id)inspectorConfiguredDisclosureView;
+ (id)keyPathsForValuesAffectingInspectedObject;
+ (id)keyPathsForValuesAffectingInspectedObjects;
- (BOOL)_tracksDocuments;
@property(readonly) BOOL availableForAllVersionsOfMacOSX;
@property(readonly) BOOL availableForMacOSX1060AndEarlier;
@property(readonly) BOOL availableForMacOSX1070AndLater;
@property(readonly) NSBundle *bundle;
@property IDEInspectorCategoryController *categoryController; // @synthesize categoryController=_categoryController;
- (BOOL)commitEditingForAction:(int)arg1 errors:(id)arg2;
@property(copy) NSArray *content; // @synthesize content=_content;
- (void)discardEditing;
- (id)dvtExtraBindings;
- (void)editorDocumentShouldCommitEditing:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(readonly) NSArray *inspectedDocuments; // @synthesize inspectedDocuments=_inspectedDocuments;
@property(readonly) id <IDEInspectorContentController> inspectedDocumentsController; // @synthesize inspectedDocumentsController=_inspectedDocumentsController;
@property(readonly) id inspectedObject;
@property(readonly) NSArray *inspectedObjects;
@property(readonly) id <IDEInspectorContentController> inspectedObjectsController; // @synthesize inspectedObjectsController=_inspectedObjectsController;
- (void)invalidate;
@property NSView<DVTIssueDisplayingView> *issueDisplayingView; // @synthesize issueDisplayingView=_issueDisplayingView;
@property(copy) NSDictionary *issueInfoDictionary; // @synthesize issueInfoDictionary=_issueInfoDictionary;
- (void)loadView;
- (void)redo:(id)arg1;
- (void)reloadInspectorFromFileWhenKeyPathChanges:(id)arg1;
- (id)selectedDocuments;
- (id)selection;
@property IDEUtilityArea *utilityArea; // @synthesize utilityArea=_utilityArea;
- (BOOL)supportsDocumentUndo;
- (void)undo:(id)arg1;
- (id)undoManager;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)viewDidInstall;
- (void)viewWillUninstall;

@end

