/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IDEIndexSymbol;

@interface IDEIndexGeniusResult : NSObject
{
    IDEIndexSymbol *_indexSymbol;
}

- (id)description;
- (unsigned long long)hash;
- (id)ideModelObjectTypeIdentifier;
- (id)initWithIndexSymbol:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)navigableItem_contentDocumentLocation;
- (id)navigableItem_documentType;
- (id)navigableItem_image;
- (id)navigableItem_name;

@end

