/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEIssueFileGroup.h"

@class NSImage, NSString;

@interface IDEIssueFileGroup (IDEKitAdditions)
+ (void)editorDocumentDirtyStatusDidChange:(id)arg1;
+ (id)imageForFileGroupWithURL:(id)arg1 issueType:(int)arg2;
+ (void)initialize;
- (void)_noteDocumentEditedStateChanged;
- (void)_observeFilePathIfNecessary;
@property(readonly) NSString *displayName;
@property(readonly) NSImage *image;
- (id)navigableItem_name;
- (id)textColor;
@end

