/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTAutoLayoutView.h"

@class IDEInspectorChooserChoice, NSArray, NSDictionary, NSMenuItem, NSPopUpButton, NSTextField, NSView;

@interface IDEInspectorChooserView : DVTAutoLayoutView
{
    NSArray *categories;
    NSPopUpButton *choicePopUp;
    NSDictionary *choicesByValue;
    IDEInspectorChooserChoice *defaultChoice;
    IDEInspectorChooserChoice *selectedChoice;
    IDEInspectorChooserChoice *nilChoice;
    NSView *selectedChoiceView;
    NSView *emptyChoiceView;
    NSMenuItem *defaultSeperator;
    NSMenuItem *specialMarkMenuItem;
    id selectedPrimitiveValue;
    NSTextField *labelView;
    BOOL disableWhenNil;
}

+ (id)categoryForXMLElement:(id)arg1 choiceType:(id)arg2 owner:(id)arg3;
+ (id)choiceForXMLElement:(id)arg1 choiceType:(id)arg2 owner:(id)arg3;
+ (id)choiceValueForElement:(id)arg1 type:(id)arg2;
+ (id)chooserForXMLElement:(id)arg1 boundTo:(id)arg2;
+ (void)initialize;
- (void)_selectedChoiceViewFrameDidChange:(id)arg1;
- (id)categoryTitleAttributes;
- (void)configureAccessibilityForUIElement:(id)arg1 forAttribute:(id)arg2 keyPath:(id)arg3 withAppendedString:(id)arg4;
- (id)dvtExtraBindings;
- (id)humanReadableNameForInspectorKeyPath:(id)arg1;
- (id)initWithTitle:(id)arg1 categories:(id)arg2 defaultChoice:(id)arg3 nilChoice:(id)arg4 disableWhenNil:(BOOL)arg5 keyPath:(id)arg6;
- (BOOL)isFlipped;
- (void)layoutBottomUp;
- (void)layoutTopDown;
@property NSView *selectedChoiceView; // @synthesize selectedChoiceView;
- (void)updateBoundValue;
- (void)updateMenu;
- (void)userMadeSelection:(id)arg1;
- (id)viewForSelectedChoice;

@end

