/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEInspectorPropertyContainingView.h>

@class IDEInspectorProperty, NSView;

@interface IDEInspectorCombinedPropertyView : IDEInspectorPropertyContainingView
{
    NSView *leftView;
    NSView *rightView;
    IDEInspectorProperty *leftProperty;
    IDEInspectorProperty *rightProperty;
}

- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithLeftProperty:(id)arg1 rightProperty:(id)arg2;
- (void)layoutBottomUp;
- (void)layoutTopDown;
@property IDEInspectorProperty *leftProperty; // @synthesize leftProperty;
@property NSView *leftView; // @synthesize leftView;
- (id)orderedInspectorProperties;
@property IDEInspectorProperty *rightProperty; // @synthesize rightProperty;
@property NSView *rightView; // @synthesize rightView;

@end

