/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEUtilityArea.h>

@class NSMutableDictionary;

@interface IDEInspectorArea : IDEUtilityArea
{
    NSMutableDictionary *_categoryControllers;
}

- (id)_descendentsAcceptingKeyView:(id)arg1;
- (void)bindReplacementView:(id)arg1 forSliceExtension:(id)arg2 inCategory:(id)arg3;
- (id)categoryControllerForCategory:(id)arg1;
- (id)categoryIdentifiersForEditorExtension:(id)arg1;
- (BOOL)categorySupportsMultipleSlices:(id)arg1;
- (BOOL)delegateFirstResponder;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;
- (id)navigableItemsForInputNavigableItems:(id)arg1 inCategory:(id)arg2;
- (id)placeholderStringForInputNavigableItems:(id)arg1 derivedItems:(id)arg2 inCategory:(id)arg3;
- (id)preferredCategoriesPersistenceKey;
- (id)sliceExtensionsForNavigableItems:(id)arg1 inCategory:(id)arg2 withWorkspaceDocument:(id)arg3;
- (id)titleForSliceExtension:(id)arg1;
- (id)titleKeyPathForSliceExtension:(id)arg1;
- (void)unbindReplacementView:(id)arg1 forSliceExtension:(id)arg2 inCategory:(id)arg3;
- (void)viewDidInstall;

@end

