/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEInspectorProperty.h>

@class NSNumber;

@interface IDEInspectorEnumerationProperty : IDEInspectorProperty
{
    NSNumber *unusedEnumerationValue;
}

+ (Class)propertyClassForPropertyDefinition:(id)arg1;
- (long long)unusedEnumerationValue;

@end

