/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEInspectorBasicStringProperty.h>

@interface IDEInspectorPathFieldProperty : IDEInspectorBasicStringProperty
{
}

+ (Class)propertyClassForPropertyDefinition:(id)arg1;
- (void)DVTFilePathFieldCell:(id)arg1 chooserSelectedPath:(id)arg2;
- (id)bindAndConfigure;
- (id)filePathField;

@end

