/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSView.h"

@class NSAttributedString, NSBezierPath, NSString;

@interface IDEInspectorCapsuleAddLozengeButton : NSView
{
    NSAttributedString *_cachedAttributedTitle;
    NSBezierPath *_cachedBackgroundPath;
    NSBezierPath *_cachedPlusPath;
    id _clickHandler;
    NSString *_title;
    BOOL _pressed;
}

- (id)cachedAttributedTitle;
- (id)cachedBackgroundPath;
@property(copy) id clickHandler; // @synthesize clickHandler=_clickHandler;
- (void)drawRect:(struct CGRect)arg1;
@property(getter=isPressed) BOOL pressed; // @synthesize pressed=_pressed;
- (void)mouseDown:(id)arg1;
- (void)mouseUp:(id)arg1;
- (id)pressedGradient;
- (id)pressedInnerShadow;
- (void)setFrame:(struct CGRect)arg1;
@property(copy) NSString *title; // @synthesize title=_title;
- (id)titleAttributes;
- (id)titleShadow;
- (id)unpressedGradient;

@end

