/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEInspectorProperty.h>

@class NSButton, NSNumber, NSStepper, NSTextField;

@interface IDEInspectorNumberProperty : IDEInspectorProperty
{
    NSTextField *textField;
    NSStepper *stepper;
    NSTextField *label;
    NSButton *checkbox;
    NSNumber *reflectedValue;
}

- (BOOL)allowsFloats:(id)arg1;
- (BOOL)allowsNilValues;
- (double)baseline;
- (id)bindAndConfigure;
- (id)bindEditableKeyPathToControl:(id)arg1;
- (id)bindEnabledKeyPathToControl:(id)arg1;
- (BOOL)canTileIntoColumnsWithWidth:(double)arg1;
- (double)increment;
- (BOOL)isEditable;
- (BOOL)isEnabled;
- (BOOL)isIncremental;
- (id)nibName;
- (BOOL)nilValueControlIsOffWhenNil;
- (long long)nilValueControlStateForNil;
- (long long)nilValueControlStateForNonNil;
- (id)reflectedValue;
- (void)setInitialCheckboxValue;
- (void)setReflectedValue:(id)arg1;
- (BOOL)showsNilValueControl;
- (void)toggleNilValue:(id)arg1;

@end

