/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEKeyDrivenNavigableItem.h>

@interface IDEIssueFileGroupNavigableItem : IDEKeyDrivenNavigableItem
{
}

+ (id)keyPathsForValuesAffectingImage;
- (id)contentDocumentLocation;
- (id)documentType;
- (id)image;
- (id)name;
- (id)representedIssueFileGroup;

@end

