/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEInspectorEnumerationProperty.h>

@class IDEInspectorResizableSegmentedControlView, NSSegmentedControl, NSTextField;

@interface IDEInspectorImageEnumerationProperty : IDEInspectorEnumerationProperty
{
    IDEInspectorResizableSegmentedControlView *resizableSegmentedControlView;
    NSSegmentedControl *segmentedControl;
    NSTextField *label;
}

- (double)baseline;
- (id)bindAndConfigure;
- (void)configureAccessibility;
- (void)configureEnumeratedOptions;
- (id)nibName;

@end

