/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEIssue.h"

@class NSImage;

@interface IDEIssue (IDEKitAdditions)
+ (id)_largeImageMapTable;
+ (id)defaultImageForIssueType:(int)arg1 size:(int)arg2;
+ (BOOL)isCandidateAnnotationRepresentedObject:(id)arg1;
@property(readonly) id annotationRepresentedObject;
- (id)childExplorableItems;
@property(readonly) id exploreAnnotationRepresentedObject;
- (id)exploredIssue;
@property(readonly) NSImage *fixItImage;
@property(readonly) NSImage *image;
- (BOOL)isNoteSeverity;
- (id)locations;
- (id)navigableItem_contentDocumentLocation;
- (id)navigableItem_documentType;
- (id)navigableItem_image;
- (id)navigableItem_name;
- (id)navigableItem_subtitle;
- (id)parentExplorableItem;
- (id)title;
@end

