/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTAutoLayoutView.h"

@class NSView;

@interface IDEInspectorCenteringView : DVTAutoLayoutView
{
    NSView *centeredView;
}

- (void)awakeFromNib;
- (void)centeredViewFrameDidChange:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutBottomUp;
- (void)layoutTopDown;

@end

