/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEIndexGeniusResultsFinder.h>

@interface IDEIncludesGeniusResultsFinder : IDEIndexGeniusResultsFinder
{
}

+ (id)_documentLocationFromCharacterRange:(struct _NSRange)arg1 textStorage:(id)arg2 fileURL:(id)arg3;
- (BOOL)_getUpdateGeniusResultsPhaseOneBlock:(id *)arg1 phaseTwoBlock:(void)arg2 phaseThreeBlock:(id *)arg3;

@end

