/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSView.h"

@class NSSegmentedControl;

@interface IDEInspectorResizableSegmentedControlView : NSView
{
    NSSegmentedControl *segmentedControl;
}

- (double)autosizedSegmentWidthForSegment:(long long)arg1;
- (void)awakeFromNib;
- (void)optimallySizeSegments;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)sizeSegmentedControlToFit;

@end

