/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEInspectorProperty.h>

@class NSDatePicker;

@interface IDEInspectorDateProperty : IDEInspectorProperty
{
    NSDatePicker *datePicker;
}

- (double)baseline;
- (id)bindAndConfigure;
- (void)setMaxDate:(id)arg1;
- (void)setMinDate:(id)arg1;

@end

