/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEInspectorProperty.h>

#import "NSTableViewDataSource-Protocol.h"

@class NSArray, NSButton, NSString, NSTableView;

@interface IDEInspectorArrayProperty : IDEInspectorProperty <NSTableViewDataSource>
{
    NSTableView *itemsTableView;
    NSButton *removeRowButton;
    NSButton *addRowButton;
    NSArray *reflectedValues;
    NSString *placeholder;
}

- (void)addRow:(id)arg1;
- (double)baseline;
- (id)bindAndConfigure;
- (BOOL)canRemoveRow;
- (id)cellReflectedValues;
- (long long)numberOfRowsInTableView:(id)arg1;
- (id)reflectedValues;
- (void)removeRow:(id)arg1;
- (void)setCellReflectedValues:(id)arg1;
- (void)setReflectedValues:(id)arg1;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (void)tableView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;

@end

