/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEIndexSymbol.h"

@interface IDEIndexSymbol (IDEKitExtensions)
- (id)completionText;
- (id)descriptionText;
- (id)displayText;
- (id)displayType;
- (id)icon;
- (BOOL)notRecommended;
- (long long)priority;
- (void)setPriority:(long long)arg1;
@end

