/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSXMLElement;

@interface IDEInspectorCapsule : NSObject
{
    unsigned long long matchType;
    NSXMLElement *inspectorXMLElement;
    id matchValue;
}

- (id)initWithXMLElement:(id)arg1 matchType:(unsigned long long)arg2 matchValue:(id)arg3;
@property(readonly) NSXMLElement *inspectorXMLElement; // @synthesize inspectorXMLElement;
@property(readonly) unsigned long long matchType; // @synthesize matchType;
@property(readonly) id matchValue; // @synthesize matchValue;

@end

