/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTAutoLayoutView.h"

@class IDEInspectorCapsuleRoundedRectView, NSView;

@interface IDEInspectorCapsuleView : DVTAutoLayoutView
{
    IDEInspectorCapsuleRoundedRectView *roundedRectView;
    NSView *view;
}

- (id)initWithView:(id)arg1;
- (void)layoutBottomUp;
- (void)layoutTopDown;
@property(readonly) NSView *view; // @synthesize view;

@end

