/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTAutoLayoutView.h"

#import <IDEKit/IDEInspectorPropertyContainingView-Protocol.h>

@class NSArray;

@interface IDEInspectorPropertyContainingView : DVTAutoLayoutView <IDEInspectorPropertyContainingView>
{
    BOOL isInstalled;
}

@property(readonly) NSArray *orderedInspectorProperties;
- (void)propertiesDidInstall;
- (void)propertiesWillUninstall;
- (void)viewDidMoveToSuperview;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)viewWillMoveToWindow:(id)arg1;

@end

