/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEInspectorProperty.h>

@class NSScrollView, NSTextView;

@interface IDEInspectorAttributedStringProperty : IDEInspectorProperty
{
    NSTextView *textView;
    NSScrollView *scrollView;
}

- (double)baseline;
- (id)bindAndConfigure;
- (void)textDidChange:(id)arg1;

@end

