/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDEBindableDeclarativeInspectorController-Protocol.h"

@class NSArray, NSBundle, NSObject<IDEBindableDeclarativeInspectorController>;

@interface IDEInspectorCapsuleController : NSObject <IDEBindableDeclarativeInspectorController>
{
    NSObject<IDEBindableDeclarativeInspectorController> *parentInspectorController;
    id representedObject;
}

@property(readonly) NSBundle *bundle;
- (id)initWithRepresentedObject:(id)arg1 parentInspectorController:(id)arg2;
@property(readonly) id inspectedObject;
@property(readonly) NSArray *inspectedObjects;
@property(readonly) NSObject<IDEBindableDeclarativeInspectorController> *parentInspectorController; // @synthesize parentInspectorController;
- (void)reloadInspectorFromFileWhenKeyPathChanges:(id)arg1;
@property(readonly) id representedObject; // @synthesize representedObject;

@end

