/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "DVTOutlineViewDelegate-Protocol.h"
#import "IDEFilterControlBarTarget-Protocol.h"
#import "IDEKeyBindingFieldCellDelegate-Protocol.h"

@class DVTBorderedView, DVTOutlineView, DVTPreferenceSetManager, DVTReplacementView, IDEFilterControlBar, NSArray, NSButton, NSMenu, NSString, NSTextField, NSTreeController;

@interface IDEKeyBindingsPrefsPaneController : IDEViewController <DVTOutlineViewDelegate, IDEKeyBindingFieldCellDelegate, IDEFilterControlBarTarget>
{
    NSArray *_keyBindingItems;
    NSString *_searchString;
    int _displayScope;
    int _searchScope;
    NSString *_statusText;
    NSArray *_conflictStatusItemCells;
    NSArray *_conflictWithHotKeyStatusItemCells;
    id <DVTObservingToken> _currentPreferenceSetObservingToken;
    id <DVTObservingToken> _contentNeedsSavingObservingToken;
    unsigned long long _lastLockedModifierMask;
    unsigned long long _lastUnlockedModifierMask;
    id _windowDidBecomeMainNotificationObserver;
    id _activeTabControllerNotificationObserver;
    NSButton *_displayAllScopeButton;
    NSButton *_displayMenuScopeButton;
    NSButton *_displayTextScopeButton;
    NSButton *_displayModifiedScopeButton;
    NSButton *_displayConflictsScopeButton;
    IDEFilterControlBar *_filterControlBar;
    NSMenu *_searchFieldMenu;
    DVTBorderedView *_scopeBarBorderedView;
    DVTReplacementView *_preferenceSetReplacementView;
    DVTOutlineView *_keyBindingsOutlineView;
    NSTreeController *_keyBindingsController;
    NSTextField *_statusTextField;
}

- (void)_conflictStatusButtonCellAction:(id)arg1;
- (void)_displayScopeButtonAction:(id)arg1;
- (id)_searchFilterPredicateWithSearchString:(id)arg1 scope:(int)arg2;
- (void)_searchScopeMenuItemAction:(id)arg1;
- (void)_showConflictedKeyBindings;
- (void)_showConflictedKeyBindingsStatusForKeyBinding:(id)arg1;
- (id)_subtitleForKeyBindingItem:(id)arg1;
- (void)_updateAlternateKeyBindingsForKeyBinding:(id)arg1;
- (void)_updateScopeButtons;
@property int displayScope; // @synthesize displayScope=_displayScope;
- (id)filterButtonMenu;
- (id)filterDefinitionIdentifier;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)keyBindingCellFieldDidEndEditing:(id)arg1;
- (id)keyBindingFieldCell:(id)arg1 alternateKeyBindingsForKeyBinding:(id)arg2;
- (BOOL)keyBindingFieldCell:(id)arg1 keyboardShortcutIsPrefix:(id)arg2;
- (id)keyBindingFieldCell:(id)arg1 validatedKeyboardShortcut:(id)arg2;
- (BOOL)keyBindingFieldCellAllowsMultipleKeyboardShortcut:(id)arg1;
- (void)keyBindingFieldCellWillRemoveKeyboardShortcut:(id)arg1;
@property(copy) NSArray *keyBindingItems; // @synthesize keyBindingItems=_keyBindingItems;
- (void)loadView;
- (BOOL)outlineView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (BOOL)outlineView:(id)arg1 isGroupItem:(id)arg2;
- (id)outlineView:(id)arg1 selectionIndexesForProposedSelection:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldEditTableColumn:(id)arg2 item:(id)arg3;
- (BOOL)outlineView:(id)arg1 shouldShowOutlineCellForItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldTrackCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (void)outlineView:(id)arg1 sortDescriptorsDidChange:(id)arg2;
- (id)outlineView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 item:(id)arg5 mouseLocation:(struct CGPoint)arg6;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (void)outlineViewSelectionDidChange:(id)arg1;
@property(readonly) DVTPreferenceSetManager *preferenceSetManager;
@property int searchScope; // @synthesize searchScope=_searchScope;
@property(copy) NSString *searchString; // @synthesize searchString=_searchString;
@property(copy) NSString *statusText; // @synthesize statusText=_statusText;
- (void)updateKeyBindingsItems;
- (BOOL)validateMenuItem:(id)arg1;
- (void)viewDidInstall;
- (void)viewWillUninstall;

@end

