/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSTextView.h"

#import "IDEApplicationEventDelegate-Protocol.h"

@class IDEKeyBindingFieldCell, NSButton, NSColor;

@interface IDEKeyBindingFieldEditor : NSTextView <IDEApplicationEventDelegate>
{
    unsigned int _savedHotKeyOperatingMode;
    BOOL _needsToRestoreSavedHotKeyOperatingMode;
    id <DVTObservingToken> _windowDidBecomeKeyObserverToken;
    id <DVTObservingToken> _windowDidResignKeyObserverToken;
    IDEKeyBindingFieldCell *_editingCell;
    NSButton *_addKeyboardShortcutButton;
    NSButton *_deleteKeyboardShortcutButton;
    NSColor *_borderColor;
    struct CGSize _buttonOffset;
}

- (void)_disableHotKeyOperationMode;
- (void)_restoreHotKeyOperationMode;
- (void)_setSelectionFromEvent:(id)arg1;
- (void)_syncDisplay;
- (id)acceptableDragTypes;
- (void)addKeyboardShortcut:(id)arg1;
- (BOOL)application:(id)arg1 shouldSendEvent:(id)arg2;
- (void)beginEditingKeyboardShortcutForCell:(id)arg1;
@property(retain, nonatomic) NSColor *borderColor; // @synthesize borderColor=_borderColor;
@property(nonatomic) struct CGSize buttonOffet; // @synthesize buttonOffet=_buttonOffset;
- (void)deleteKeyboardShortcut:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
@property(readonly) IDEKeyBindingFieldCell *editingCell; // @synthesize editingCell=_editingCell;
- (void)endEditingKeyboardShortcut;
- (void)mouseDown:(id)arg1;
- (id)readablePasteboardTypes;
- (void)resetCursorRects;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)viewDidMoveToWindow;
- (id)writablePasteboardTypes;

@end

