/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTPreferenceSet-Protocol.h"

@class DVTCustomDataSpecifier, IDEMenuKeyBindingSet, IDETextKeyBindingSet, NSArray, NSImage, NSMutableArray, NSString, NSURL;

@interface IDEKeyBindingPreferenceSet : NSObject <DVTPreferenceSet>
{
    NSString *_name;
    NSString *_localizedName;
    NSURL *_dataURL;
    NSImage *_image;
    DVTCustomDataSpecifier *_customDataSpecifier;
    BOOL _builtIn;
    BOOL _contentNeedsSaving;
    BOOL _isDataLoaded;
    long long _disableActivateCount;
    IDEMenuKeyBindingSet *_menuKeyBindingSet;
    IDETextKeyBindingSet *_textKeyBindingSet;
    NSArray *_cachedAllKeyBindings;
    NSMutableArray *_cachedModifiedKeyBindings;
    NSMutableArray *_cachedHotKeyboardShortcuts;
    NSMutableArray *_cachedConflictedKeyBindings;
    unsigned long long _numConflictedKeyBindings;
    unsigned long long _numConflictedHotKeyBindings;
    id <DVTObservingToken> _menuKeyBindingsObservingToken;
    id <DVTObservingToken> _textKeyBindingsObservingToken;
}

+ (id)_defaultKeyBindingsDictionary;
+ (id)builtInPreferenceSetsDirectoryURL;
+ (id)defaultKeyForCurrentPreferenceSet;
+ (id)defaultKeyForExcludedBuiltInPreferenceSets;
+ (id)keyPathsForValuesAffectingAllKeyBindings;
+ (id)keyPathsForValuesAffectingConflictedKeyBindings;
+ (id)preferenceSetGroupingName;
+ (id)preferenceSetsFileExtension;
+ (id)preferenceSetsListHeader;
+ (id)preferenceSetsManager;
+ (id)systemPreferenceSet;
+ (id)titleForNewPreferenceSetFromTemplate;
- (id)_cachedHotKeyboardShortcuts;
- (id)_conflictedKeyBindingsWithKeyBinding:(id)arg1 keyboardShortcut:(id)arg2 menuKeyBindingSet:(id)arg3 textKeyBindingSet:(id)arg4;
- (long long)_disableActivateCount;
- (unsigned long long)_numberOfConflictedHotKeyBindings;
- (unsigned long long)_numberOfConflictedKeyBindigns;
- (void)_resolveConflictWithMenuKeyBindingSet:(id)arg1 textKeyBindingSet:(id)arg2;
- (void)_symbolicHotKeyDidChange;
- (void)_updateConflictedKeyBindings;
- (void)activate;
@property(readonly) NSArray *allKeyBindings;
- (id)alternateKeyBindingsForKeyBinding:(id)arg1;
@property(readonly) NSArray *conflictedKeyBindings;
- (id)conflictedKeyBindingsWithKeyBinding:(id)arg1 keyboardShortcut:(id)arg2;
@property BOOL contentNeedsSaving; // @synthesize contentNeedsSaving=_contentNeedsSaving;
@property DVTCustomDataSpecifier *customDataSpecifier; // @synthesize customDataSpecifier=_customDataSpecifier;
- (id)dataRepresentationWithError:(id *)arg1;
@property(readonly) NSURL *dataURL; // @synthesize dataURL=_dataURL;
@property NSImage *image; // @synthesize image=_image;
- (id)initWithCustomDataSpecifier:(id)arg1 basePreferenceSet:(id)arg2;
- (id)initWithName:(id)arg1 dataURL:(id)arg2;
@property(readonly, getter=isBuiltIn) BOOL builtIn; // @synthesize builtIn=_builtIn;
- (void)loadData;
@property(readonly) NSString *localizedName; // @synthesize localizedName=_localizedName;
@property IDEMenuKeyBindingSet *menuKeyBindingSet;
@property(readonly) NSArray *modifiedKeyBindings;
@property(readonly) NSString *name; // @synthesize name=_name;
@property IDETextKeyBindingSet *textKeyBindingSet;

@end

