/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "DVTFilePathFieldCellDelegate-Protocol.h"
#import "IDEBuildFolderLocationPrefsSheetControllerDelegate-Protocol.h"

@class DVTFilePathField, NSAttributedString, NSString, NSTextField;

@interface IDELocationsPrefsPaneController : IDEViewController <DVTFilePathFieldCellDelegate, IDEBuildFolderLocationPrefsSheetControllerDelegate>
{
    BOOL _useCustomDerivedDataLocation;
    BOOL _useCustomSnapshotsLocation;
    BOOL _useCustomDistributionArchivesLocation;
    NSString *_customDerivedDataLocation;
    NSString *_customSnapshotsLocation;
    NSString *_customDistributionArchivesLocation;
    int _derivedDataLocationStyle;
    int _snapshotsLocationStyle;
    int _distributionArchivesLocationStyle;
    int _buildFolderLocationStyle;
    int _buildSubfolderStyle;
    NSString *_customBuildSubfolderName;
    DVTFilePathField *_derivedDataFilePathField;
    NSTextField *_derivedDataRelativePathField;
    DVTFilePathField *_snapshotsFilePathField;
    DVTFilePathField *_distributionArchivesFilePathField;
    DVTFilePathField *_derivedDataPathLabel;
    DVTFilePathField *_snapshotsPathLabel;
    DVTFilePathField *_distributionArchivesPathLabel;
    NSTextField *_derivedDataRelativePathLabel;
}

+ (id)keyPathsForValuesAffectingCustomWorkspaceRelativeDerivedDataLocation;
+ (id)keyPathsForValuesAffectingUseCustomDerivedDataLocation;
+ (id)keyPathsForValuesAffectingUseCustomDistributionArchivesLocation;
+ (id)keyPathsForValuesAffectingUseCustomSnapshotsLocation;
- (id)DVTFilePathFieldCell:(id)arg1 resolvedPathForPath:(id)arg2;
- (void)_saveLocationsPreferences;
- (void)_updateCustomLocationFieldsForPathTypes;
- (void)_updateDerivedDataCustomLocationFieldForPathType;
- (void)_updateDerivedDataPathLabelForSelectedLocationStyle;
- (void)_updateDistributionArchivesCustomLocationFieldForPathType;
- (void)_updateDistributionArchivesPathLabelForSelectedLocationStyle;
- (void)_updatePathLabelsForSelectedLocationStyles;
- (void)_updateSnapshotsCustomLocationFieldForPathType;
- (void)_updateSnapshotsPathLabelForSelectedLocationStyle;
- (void)_windowDidResignMain:(id)arg1;
- (void)buildFolderLocationSheetDidEndWithBuildFolderLocationStyle:(int)arg1 buildSubfolderStyle:(int)arg2 customBuildSubfolderName:(id)arg3;
@property int buildFolderLocationStyle; // @synthesize buildFolderLocationStyle=_buildFolderLocationStyle;
@property int buildSubfolderStyle; // @synthesize buildSubfolderStyle=_buildSubfolderStyle;
@property(copy) NSString *customBuildSubfolderName; // @synthesize customBuildSubfolderName=_customBuildSubfolderName;
@property(copy) NSString *customDerivedDataLocation; // @synthesize customDerivedDataLocation=_customDerivedDataLocation;
@property(copy) NSString *customDistributionArchivesLocation; // @synthesize customDistributionArchivesLocation=_customDistributionArchivesLocation;
@property(copy) NSString *customSnapshotsLocation; // @synthesize customSnapshotsLocation=_customSnapshotsLocation;
@property(readonly) NSAttributedString *customWorkspaceRelativeDerivedDataLocation;
@property(readonly) NSString *defaultDerivedDataLocation;
@property(readonly) NSString *defaultDistributionArchivesLocation;
@property(readonly) NSString *defaultSnapshotsLocation;
@property int derivedDataLocationStyle; // @synthesize derivedDataLocationStyle=_derivedDataLocationStyle;
@property int distributionArchivesLocationStyle; // @synthesize distributionArchivesLocationStyle=_distributionArchivesLocationStyle;
- (void)loadView;
@property int snapshotsLocationStyle; // @synthesize snapshotsLocationStyle=_snapshotsLocationStyle;
- (void)showBuildFolderLocationSheet:(id)arg1;
@property(readonly) BOOL useCustomDerivedDataLocation;
@property(readonly) BOOL useCustomDistributionArchivesLocation;
@property(readonly) BOOL useCustomSnapshotsLocation;
- (BOOL)validateCustomDerivedDataLocation:(id *)arg1 error:(id *)arg2;
- (BOOL)validateCustomDistributionArchivesLocation:(id *)arg1 error:(id *)arg2;
- (BOOL)validateCustomSnapshotsLocation:(id *)arg1 error:(id *)arg2;
- (void)viewWillUninstall;

@end

