/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "IDECapsuleListViewDataSource-Protocol.h"

@class DVTBorderedView, DVTChoice, DVTFilePathFieldCell, DVTStackView, DVTTabChooserView, IDEArgumentsCapsuleSheetController, IDECapsuleListView, IDEDebuggerSpecifier, IDEEnvironmentVariablesCapsuleSheetController, IDELaunchSchemeAction, IDEManualSymbolLoadingCapsuleSheetController, IDEScheme, IDEWorkspace, NSArray, NSButtonCell, NSColor, NSMatrix, NSPopUpButton, NSView;

@interface IDELaunchRunPhaseSheetController : IDEViewController <IDECapsuleListViewDataSource>
{
    DVTTabChooserView *_tabChooser;
    IDECapsuleListView *_capsuleListView;
    DVTBorderedView *_capsuleListEnclosingBorderedView;
    NSPopUpButton *_runnablePopUp;
    NSPopUpButton *_debuggerSelectionControl;
    NSMatrix *_launchStyleMatrix;
    NSButtonCell *_waitForAppToLaunchButtonCell;
    DVTFilePathFieldCell *_workingDirectoryTextFieldCell;
    NSView *_infoTabViewContentView;
    NSView *_diagnosticsTabViewContentView;
    NSPopUpButton *_macroExpansionRunnableBuildablesPopUp;
    NSPopUpButton *_deviceAppDataPackagesPopUp;
    NSPopUpButton *_locationSimulationPopUp;
    DVTStackView *_optionsStackView;
    NSView *_locationsOptionView;
    NSView *_applicationDataOptionView;
    NSView *_resumeOptionView;
    NSView *_debugDocumentVersioningOptionView;
    NSView *_workingDirectoryOptionView;
    NSView *_OpenGLESOptionsView;
    DVTChoice *_infoChoice;
    DVTChoice *_conditionsChoice;
    DVTChoice *_optionsChoice;
    DVTChoice *_diagnosticsChoice;
    DVTChoice *_debuggingChoice;
    BOOL _exectutableHasBeenSelected;
    BOOL _debuggerHasBeenSelected;
    NSColor *_descriptionTextColor;
    IDEScheme *_runContext;
    IDEWorkspace *_workspace;
    IDELaunchSchemeAction *_runPhase;
    int _launchStyleWhenDebuggerSetToNil;
    BOOL _isSupportedApplicationData;
    BOOL _optionsUpdatedInCurrentRunLoop;
    id <DVTObservingToken> _runDestinationObservingToken;
    id <DVTObservingToken> _runnableBuildableProductsObservingToken;
    id <DVTObservingToken> _runContextRunnableObservingToken;
    IDEArgumentsCapsuleSheetController *_argumentsViewController;
    IDEEnvironmentVariablesCapsuleSheetController *_environmentVariablesViewController;
    IDEManualSymbolLoadingCapsuleSheetController *_manualSymbolLoadingViewController;
    NSArray *_debuggerSpecifiers;
    unsigned long long _runnablePopUpRunnableBuildableProductsCount;
    BOOL _runnablePopUpHasCustomRunnable;
}

+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (void)initialize;
- (void)DVTFilePathFieldCell:(id)arg1 chooserSelectedPath:(id)arg2;
- (id)DVTFilePathFieldCell:(id)arg1 resolvedPathForPath:(id)arg2;
- (void)_collaspeManualSymbolLoadingCapsuleIfItExists;
- (id)_iconForBuildable:(id)arg1;
- (void)_macroExpansionRunnableBuildableSelected:(id)arg1;
- (void)_resetOptionsUpdatedFlag;
- (void)_runDestinationChanged;
- (void)_runPhaseRunnableChanged;
- (void)_runnableBuildableProductsDidChange;
- (void)_runnableDidUpdate;
- (void)_selectDeviceAppDataPackage:(id)arg1;
- (void)_selectMenuItemForDeviceApplicationPackage;
- (void)_selectedSchemeChanged:(id)arg1;
- (void)_updateDebuggerPopUp:(id)arg1;
- (void)_updateDeviceAppDataUI;
- (void)_updateLocationSimulationUI;
- (void)_updateMacroExpansionRunnablePopUp;
- (void)_updateMacroExpansionRunnablePopUpSelection;
- (void)_updateRunnablePopUp;
- (void)_updateSupportedOptions;
- (id)capsuleListView:(id)arg1 viewControllerForRow:(long long)arg2;
@property BOOL debuggerHasBeenSelected; // @synthesize debuggerHasBeenSelected=_debuggerHasBeenSelected;
@property(readonly) NSArray *debuggerSpecifiers;
@property(copy) NSColor *descriptionTextColor; // @synthesize descriptionTextColor=_descriptionTextColor;
- (id)dvtExtraBindings;
@property BOOL exectutableHasBeenSelected; // @synthesize exectutableHasBeenSelected=_exectutableHasBeenSelected;
- (void)invalidate;
- (void)loadView;
- (long long)numberOfObjectsInCapsuleListView:(id)arg1;
@property IDEScheme *runContext; // @synthesize runContext=_runContext;
@property IDELaunchSchemeAction *runPhase; // @synthesize runPhase=_runPhase;
- (void)runnablePopUpAction:(id)arg1;
@property IDEDebuggerSpecifier *selectedDebuggerSpecifier;
@property DVTTabChooserView *tabChooser; // @synthesize tabChooser=_tabChooser;
- (void)updateBoundContent;
- (void)updateBoundIDERunContextBinding;
@property(readonly) IDEWorkspace *workspace;

@end

