/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

@class DVTReplacementView, NSTabView;

@interface IDELocationCategoryPrefsPaneController : IDEViewController
{
    DVTReplacementView *replacementView;
    NSTabView *tabView;
}

+ (id)cachedExtensions;
+ (id)cachedExtensionsByIdentifier;
- (void)loadView;
@property DVTReplacementView *replacementView; // @synthesize replacementView;
@property NSTabView *tabView; // @synthesize tabView;
- (void)tabView:(id)arg1 didSelectTabViewItem:(id)arg2;

@end

