/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEBreakpointAction.h"

#import "NSSpeechSynthesizerDelegate-Protocol.h"

@class NSString;

@interface IDELogBreakpointAction : IDEBreakpointAction <NSSpeechSynthesizerDelegate>
{
    int _conveyanceType;
    NSString *_message;
}

+ (id)propertiesAffectingPersistenceState;
- (void)_handleMessageChanged;
- (void)_logActionCommonInit;
@property int conveyanceType; // @synthesize conveyanceType=_conveyanceType;
- (void)dvt_awakeFromXMLUnarchiver:(id)arg1;
- (void)dvt_encodeAttributesWithXMLArchiver:(id)arg1;
- (id)init;
- (id)initFromXMLUnarchiver:(id)arg1 archiveVersion:(float)arg2;
@property(copy) NSString *message; // @synthesize message=_message;
- (void)performActionUsingConsole:(id)arg1 andBreakpoint:(id)arg2;
- (void)speechSynthesizer:(id)arg1 didFinishSpeaking:(BOOL)arg2;

@end

