/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEUtilityArea.h>

@class NSMutableDictionary;

@interface IDELibraryArea : IDEUtilityArea
{
    NSMutableDictionary *_previousLibraries;
    NSMutableDictionary *_libraryExtensions;
}

+ (id)defaultViewNibName;
+ (double)extraHeight;
+ (double)tileHeight;
- (id)_enclosingSplitView;
- (id)_libraryExtensionForIdentifier:(id)arg1;
- (void)activateFilterFieldForFocus;
- (void)activateFilterFieldForFocusFromMenuItem:(id)arg1;
- (id)categoryIdentifiersForEditorExtension:(id)arg1;
- (BOOL)categorySupportsMultipleSlices:(id)arg1;
- (void)chooserView:(id)arg1 userDidSelectChoices:(id)arg2;
- (BOOL)delegateFirstResponder;
- (void)hideLibraryArea;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(readonly, getter=isCollapsed) BOOL collapsed;
- (id)libraryControllerForExtension:(id)arg1;
- (void)loadView;
- (id)preferredCategoriesPersistenceKey;
- (void)showLibraryArea;
- (id)sliceExtensionsForNavigableItems:(id)arg1 inCategory:(id)arg2 withWorkspaceDocument:(id)arg3;
- (void)viewDidInstall;
- (id)willReplaceSliceViewControllers:(SEL)arg1;

@end

