/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTLibraryController.h"

@interface IDELibraryController : DVTLibraryController
{
    id <DVTObservingToken> _activeEditorKVOToken;
}

- (void)activeEditorDidChange:(id)arg1;
- (void)startObservingActiveEditor;
- (void)stopObservingActiveEditor;
- (void)viewDidInstall;
- (void)viewWillUninstall;
- (id)workspaceWindowController;

@end

