/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEMediaRepository.h>

@class NSMutableSet;

@interface IDEMutableMediaRepository : IDEMediaRepository
{
    NSMutableSet *_resources;
}

- (void)addResource:(id)arg1;
- (id)initWithResources:(id)arg1;
- (void)removeResource:(id)arg1;
- (id)resources;

@end

