/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTGenericButtonViewController.h"

@interface IDEMiniDebuggerToolbarConsoleViewController : DVTGenericButtonViewController
{
    id <DVTObservingToken> _debugSessionStateObserverToken;
    id <DVTObservingToken> _debuggingWindowBehaviorObservingToken;
}

- (void)_updateForDebuggingKVOChange:(id)arg1;
- (id)initWithButton:(id)arg1 actionBlock:(id)arg2 itemIdentifier:(void)arg3 window:(id)arg4;

@end

