/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDENavigationHUDAbstractWorkspaceWindowLayer.h>

#import "IDENavigationHUDSelectionDrivenLayer-Protocol.h"

@class CAScrollLayer, IDENavigationHUDSelection, IDENavigationHUDTabBarLayer, IDEWorkspaceWindowController, NSArray, NSDictionary, NSMapTable;

@interface IDENavigationHUDWorkspaceWindowLayer : IDENavigationHUDAbstractWorkspaceWindowLayer <IDENavigationHUDSelectionDrivenLayer>
{
    NSMapTable *_strongWorkspaceTabControllerToStrongTabLayerMap;
    IDEWorkspaceWindowController *_workspaceWindowController;
    NSMapTable *_strongDividerLayerToLastKnownBoundsMap;
    NSMapTable *_strongTabLayerToStrongDividerLayerMap;
    IDENavigationHUDTabBarLayer *_tabBarLayer;
    IDENavigationHUDSelection *_selection;
    CAScrollLayer *_mainTabScrollLayer;
    NSArray *_orderedTabLayers;
    NSDictionary *_options;
}

@property(readonly) BOOL canCreateNewTab;
- (void)dispose;
- (id)dividerLayerForTabLayer:(id)arg1;
- (id)initWithNavigationHUDController:(id)arg1 workspaceWindowController:(id)arg2 initialSelection:(id)arg3 options:(id)arg4;
- (struct CGRect)lastKnownBoundsForDividerLayer:(id)arg1;
- (void)layoutSublayersOfLayer:(id)arg1;
- (id)representativeSelection;
- (void)scrollSelectedTabVisible;
- (id)selectedTabLayer;
@property(copy) IDENavigationHUDSelection *selection; // @synthesize selection=_selection;
- (id)selectionForNavigatingDown;
- (id)selectionForNavigatingLeft;
- (id)selectionForNavigatingLeftOneTab;
- (id)selectionForNavigatingRight;
- (id)selectionForNavigatingRightOneTab;
- (id)selectionForNavigatingUp;
- (void)setLastKnownBounds:(struct CGRect)arg1 forDividerLayer:(id)arg2;
@property(readonly) BOOL shouldOnlySelectInitialTab;
@property(readonly) BOOL shouldShowTabBar;
- (id)tabLayerForWorkspaceTabController:(id)arg1;
@property(readonly) IDEWorkspaceWindowController *workspaceWindowController; // @synthesize workspaceWindowController=_workspaceWindowController;

@end

