/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTOutlineView.h"

@class DVTDelayedValidator, NSArray, NSHashTable, NSPredicate, NSString;

@interface IDENavigatorOutlineView : DVTOutlineView
{
    double _groupHeaderRowHeight;
    long long _batchRowUpdateCount;
    id _itemBeingFullyReloaded;
    NSHashTable *_unfilteredRootItems;
    NSPredicate *_filterPredicate;
    DVTDelayedValidator *_delayedValidator;
    NSString *_emptyContentStringCopy;
    SEL _keyAction;
    id <IDENavigatorOutlineViewLoadingDelegate> _loadingDelegate;
    struct _IDEOutlineViewGroupInfo *_groupInfo;
    struct {
        unsigned int _needsToPushRowSelection:1;
        unsigned int _needsToRefreshBoundSelectedObjects:1;
        unsigned int _needsToRefreshBoundExpandedItems:1;
        unsigned int _suspendRowHeightInvalidation:1;
        unsigned int _doingBatchExpand:1;
        unsigned int _filteringEnabled:1;
        unsigned int _filteringActive:1;
        unsigned int _scrollSelectionToVisibleAfterRefreshingSelection:1;
        unsigned int _hasContent:1;
        unsigned int _didDrawContent:1;
        unsigned int _resettingRootItems:1;
        unsigned int _reloadingItems:1;
        unsigned int _didRecieveKeyDownEvent:1;
        unsigned int _didPublishSelectedObjects:1;
        unsigned int _extraFlags:18;
    } _idenovFlags;
}

+ (void)initialize;
- (void)_clearGroupingInfo;
- (void)_computeGroupsToDraw:(id)arg1 groupInfoByGroup:(id)arg2 forRowsInRange:(struct _NSRange)arg3;
- (void)_expandAncestorsForItem:(id)arg1;
- (void)_ide_commonInit;
- (double)_indentationForRow:(long long)arg1 withLevel:(long long)arg2 isSourceListGroupRow:(BOOL)arg3;
- (void)_refreshBoundExpandedAndSelectedItems:(id)arg1;
- (void)_refreshDisplayForItem:(id)arg1;
- (void)_setNeedsDisplayInSelectedRows;
- (void)_updateBoundContentArrayOrSet;
- (void)_updateEmptyContentString;
- (void)_updateRootItems:(id)arg1 sortDescriptors:(id)arg2;
- (void)accessibilitySetSelectedRowsAttribute:(id)arg1;
- (struct CGRect)adjustRect:(struct CGRect)arg1 forItem:(id)arg2 row:(long long)arg3 inGroupRange:(struct _NSRange)arg4;
- (void)beginBatchRowUpdates;
- (void)collapseItem:(id)arg1;
- (void)collapseItem:(id)arg1 collapseChildren:(BOOL)arg2;
- (void)concludeBatchRowUpdates;
- (void)drawBackgroundInClipRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)dvtExtraBindings;
- (BOOL)dvt_highlightColorDependsOnWindowState;
- (id)emptyContentString;
- (struct _IDEOutlineViewGroupInfo *)enclosingGroupInfoForRow:(long long)arg1;
- (id)enclosingGroupItemForItem:(id)arg1;
- (void)expandAncestorsForItem:(id)arg1;
- (void)expandItem:(id)arg1;
- (void)expandItem:(id)arg1 expandChildren:(BOOL)arg2;
@property(copy) NSPredicate *filterPredicate; // @synthesize filterPredicate=_filterPredicate;
- (long long)filterProgress;
- (BOOL)filteringEnabled;
- (struct CGRect)frameOfCellAtColumn:(long long)arg1 row:(long long)arg2;
- (struct CGRect)frameOfOutlineCellAtRow:(long long)arg1;
@property double groupHeaderRowHeight; // @synthesize groupHeaderRowHeight=_groupHeaderRowHeight;
- (BOOL)groupWithRangeShouldDrawLeftDivider:(struct _NSRange)arg1;
- (BOOL)groupWithRangeShouldDrawTopDivider:(struct _NSRange)arg1;
- (struct CGRect)headerRectForGroupRange:(struct _NSRange)arg1;
- (void)highlightSelectionInClipRect:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct _NSRange)initialSelectionRangeForCell:(id)arg1 proposedRange:(struct _NSRange)arg2;
@property(readonly, getter=isFilteringActive) BOOL filteringActive;
@property(readonly, getter=isReloadingItems) BOOL reloadingItems;
- (BOOL)isRootItem:(id)arg1;
- (void)item:(id)arg1 expandedAddingRows:(long long)arg2;
- (BOOL)item:(id)arg1 isDescendantOfItem:(id)arg2;
- (id)itemBeingFullyReloaded;
- (id)itemsAtIndexes:(id)arg1;
@property SEL keyAction; // @synthesize keyAction=_keyAction;
- (void)keyDown:(id)arg1;
- (void)keyUp:(id)arg1;
@property id <IDENavigatorOutlineViewLoadingDelegate> loadingDelegate; // @synthesize loadingDelegate=_loadingDelegate;
- (void)mouseDown:(id)arg1;
- (void)noteAllRowHeightsMayHaveChanged;
- (void)printGroupInfo;
- (void)publishBoundSelectedObjects;
@property(readonly) id realDataSource;
@property(readonly) id realDelegate;
- (void)refreshBoundExpandedItems;
- (void)refreshBoundSelectedObjects;
- (void)registerGroupHeaderItem:(id)arg1 atRow:(unsigned long long)arg2;
- (void)reloadData;
- (void)reloadItem:(id)arg1 reloadChildren:(BOOL)arg2;
@property(copy) NSArray *rootItems;
- (struct _NSRange)rowRangeForEnclosingGroupOfItem:(id)arg1;
- (struct _NSRange)rowRangeForEnclosingGroupOfTreeNode:(id)arg1;
- (BOOL)scrollRectToVisible:(struct CGRect)arg1;
- (void)scrollSelectionToVisible;
- (BOOL)sendAction:(SEL)arg1 to:(id)arg2;
- (void)setDataSource:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setEmptyContentString:(id)arg1;
- (void)setFilteringActive:(BOOL)arg1;
- (void)setFilteringEnabled:(BOOL)arg1;
- (void)setShouldSuspendPublishBoundSelectedObjects:(BOOL)arg1;
- (void)setShouldSuspendRowHeightInvalidation:(BOOL)arg1;
- (void)setSortDescriptors:(id)arg1;
- (BOOL)shouldSuspendPublishBoundSelectedObjects;
- (BOOL)shouldSuspendRowHeightInvalidation;
- (void)updateBoundContentArray;
- (void)updateBoundContentSet;
- (void)updateBoundExpandedItems;
- (void)updateBoundSelectedObjects;

@end

