/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTLayerHostingView.h"

#import "DVTInvalidation-Protocol.h"

@class CALayer, CAScrollLayer, DVTDelayedValidator, DVTImageAndTextLayer, DVTStackBacktrace, NSArray, NSMapTable;

@interface IDENavigationHUDSelectionView : DVTLayerHostingView <DVTInvalidation>
{
    id <IDENavigationHUDSelectionViewDelegate> _delegate;
    DVTDelayedValidator *_fileProxyValidator;
    DVTDelayedValidator *_coverFlowValidator;
    DVTDelayedValidator *_textAreaValidator;
    DVTImageAndTextLayer *_fileProxyLayer;
    DVTImageAndTextLayer *_textLayer;
    NSMapTable *_wrappingLayerToRealLayerMap;
    NSMapTable *_realLayerToWrappingLayerMap;
    unsigned long long _selectedCoverFlowLayerIndex;
    CAScrollLayer *_coverFlowScrollLayer;
    NSArray *_coverFlowLayers;
    DVTStackBacktrace *_invalidationBacktrace;
    BOOL _isInvalidated;
}

+ (id)keyPathsForValuesAffectingSelectedCoverFlowLayer;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)arg1;
- (BOOL)accessibilityIsIgnored;
- (void)addCoverFlowLayer:(id)arg1;
@property id <IDENavigationHUDSelectionViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)existingWrappingLayerForLayer:(id)arg1;
@property(readonly) struct CGSize fileProxyImageSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)invalidate;
- (void)invalidateCoverFlow;
- (void)invalidateFileProxy;
- (void)invalidateTextArea;
@property(readonly) DVTStackBacktrace *invalidationBacktrace; // @synthesize invalidationBacktrace=_invalidationBacktrace;
@property(readonly, getter=isValid) BOOL valid;
- (void)layoutSublayersOfLayer:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseUp:(id)arg1;
- (id)realLayerForWrappingLayer:(id)arg1;
- (void)refreshCoverFlow;
- (void)refreshFileProxy;
- (void)refreshTextArea;
- (void)removeCoverFlowLayer:(id)arg1;
- (BOOL)requireOptimumPerformance;
@property CALayer *selectedCoverFlowLayer;
@property unsigned long long selectedCoverFlowLayerIndex; // @synthesize selectedCoverFlowLayerIndex=_selectedCoverFlowLayerIndex;
- (void)selectionViewCommonInit;
- (void)setCoverFlowNeedsLayout;
- (id)wrappingLayerForLayerCreatingIfNecessary:(id)arg1;

@end

