/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDENavigationHUDBorderedGradientLayer.h>

#import "IDENavigationHUDDisposableLayer-Protocol.h"
#import "IDENavigationHUDSelectableLayer-Protocol.h"

@class CAGradientLayer, CALayer, IDENavigationHUDSelection, IDENavigationHUDTabLayer, IDEWorkspaceWindowController;

@interface IDENavigationHUDTabLayoutLayer : IDENavigationHUDBorderedGradientLayer <IDENavigationHUDSelectableLayer, IDENavigationHUDDisposableLayer>
{
    IDEWorkspaceWindowController *_workspaceWindowController;
    IDENavigationHUDTabLayer *_workspaceTabLayer;
    unsigned long long _state;
    CAGradientLayer *_overlayLayer;
    CALayer *_imageLayer;
}

- (void)dispose;
- (struct CGSize)imageSize;
- (id)init;
- (id)initWithWorkspaceWindowController:(id)arg1 workspaceTabLayer:(id)arg2 image:(id)arg3;
- (void)layoutSublayers;
@property(readonly) IDENavigationHUDSelection *representativeSelection;
@property(readonly) BOOL representativeSelectionIsFinalForSingleMouseUp;
@property unsigned long long state; // @synthesize state=_state;
- (id)workspaceTabController;
@property(readonly) IDENavigationHUDTabLayer *workspaceTabLayer; // @synthesize workspaceTabLayer=_workspaceTabLayer;
@property(readonly) IDEWorkspaceWindowController *workspaceWindowController; // @synthesize workspaceWindowController=_workspaceWindowController;

@end

