/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

@class CALayer<IDENavigationHUDSelectableLayer>, IDENavigationHUDAbstractWorkspaceWindowLayer, IDENavigationHUDNewWorkspaceWindowLayer, IDENavigationHUDSelection, IDENavigationHUDSelectionView, IDEWorkspaceDocument, NSArray, NSDictionary, NSMapTable, NSSet, NSURL;

@interface IDENavigationHUDController : IDEViewController
{
    IDENavigationHUDSelectionView *_selectionView;
    CALayer<IDENavigationHUDSelectableLayer> *_currentClickedLayer;
    NSMapTable *_workspaceWindowControllerToWorkspaceWindowLayerMap;
    id _completionBlock;
    IDENavigationHUDNewWorkspaceWindowLayer *_newWindowLayer;
    NSMapTable *_workspaceTabToLayoutTreeMap;
    IDEWorkspaceDocument *_workspaceDocument;
    IDENavigationHUDSelection *_selection;
    NSArray *_workspaceWindowControllers;
    NSSet *_workspaceObservingTokens;
    NSArray *_workspaceWindowLayers;
    id _hudLocalEventHandler;
    NSDictionary *_options;
    NSURL *_URL;
}

@property(readonly) NSURL *URL; // @synthesize URL=_URL;
- (BOOL)canCreateNewWindow;
- (void)chooseSelection:(id)arg1;
- (id)coverFlowLayersForSelectionView:(id)arg1;
- (id)defaultPrimaryEditorContextLayoutTreeNodeForWorkspaceTabController:(id)arg1;
- (id)existingWorkspaceWindowLayerForWorkspaceWindowController:(id)arg1;
- (id)filePathForSelectionViewFileProxy:(id)arg1;
- (id)fileProxyImageForSelectionView:(id)arg1;
- (id)fileProxyTitleForSelectionView:(id)arg1;
- (void)generateWorkspaceWindowLayers;
- (id)initWithInitialSelection:(id)arg1 options:(id)arg2 completionBlock:(id)arg3;
- (id)initWithURL:(id)arg1 initialSelection:(id)arg2 options:(id)arg3 completionBlock:(id)arg4;
- (void)invalidate;
- (id)layoutTreeForWorkspaceTabController:(id)arg1;
- (void)loadView;
- (void)navigateDown;
- (void)navigateLeft;
- (void)navigateLeftOneTab;
- (void)navigateLeftOneWindow;
- (void)navigateRight;
- (void)navigateRightOneTab;
- (void)navigateRightOneWindow;
- (void)navigateUp;
@property(readonly) IDENavigationHUDNewWorkspaceWindowLayer *newWindowLayer; // @synthesize newWindowLayer=_newWindowLayer;
- (void)respondToSelection;
- (unsigned long long)role;
- (id)selectableLayerForMouseEvent:(id)arg1;
@property(readonly) IDENavigationHUDAbstractWorkspaceWindowLayer *selectedWorkspaceWindowLayer;
@property IDENavigationHUDSelection *selection; // @synthesize selection=_selection;
- (void)selectionView:(id)arg1 didDoubleClickWithEvent:(id)arg2;
- (void)selectionView:(id)arg1 didReceiveMouseDown:(id)arg2;
- (void)selectionView:(id)arg1 didReceiveMouseUp:(id)arg2;
- (void)selectionViewDidStartDraggingFileProxy:(id)arg1;
@property IDEWorkspaceDocument *workspaceDocument; // @synthesize workspaceDocument=_workspaceDocument;
- (BOOL)shouldOnlySelectInitialWindow;
- (void)startListeningToEvents;
- (void)startListeningToWindowControllers;
- (void)stopListeningToEvents;
- (void)stopListeningToWindowControllers;
- (id)textForSelectionView:(id)arg1;
- (void)viewDidInstall;
- (void)viewWillUninstall;
@property(readonly) NSArray *workspaceWindowControllers;
- (id)workspaceWindowLayerForWorkspaceWindowController:(id)arg1;

@end

