/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDENavigableItem.h>

@class NSHashTable, NSMutableSet, NSPredicate;

@interface IDENICFilterProxy : IDENavigableItem
{
    NSHashTable *_itemsToFilterAfterDelay;
    NSHashTable *_rootItems;
    NSHashTable *_itemsWithComputedArrangedChildItems;
    NSMutableSet *_pendingItems;
    NSPredicate *_proxyFilterPredicate;
    double _filterStartTime;
    BOOL _isInvalidated;
    BOOL _isFiltering;
    BOOL _isSuspended;
}

- (id)_childItems;
- (void)_delayedComputeArrangedChildItems;
- (id)_itemsWithComputedArrangedChildItems;
- (void)addPendingItem:(id)arg1;
- (id)arrangeItems:(id)arg1;
- (BOOL)canUseIncrementalFilteringBasedOnPredicate:(id)arg1;
- (id)childItems;
- (void)computeArrangedChildItemsForItem:(id)arg1;
- (id)description;
- (void)dispose;
- (id)filterPredicate;
- (void)handleObjectGraphUpdateNotification:(id)arg1;
- (id)initWithRepresentedObject:(id)arg1;
@property(getter=isFiltering) BOOL filtering;
- (BOOL)isLeaf;
- (id)parentForItem:(id)arg1;
- (void)resumeFiltering;
@property(readonly) NSHashTable *rootItems; // @synthesize rootItems=_rootItems;
- (void)setFilterPredicate:(id)arg1;
- (void)setItems:(id)arg1;
- (BOOL)shouldFilterChildItemsOfItem:(id)arg1;
- (void)suspendFiltering;
- (void)updateArrangedChildItemsForItem:(id)arg1;

@end

