/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDENavigationHUDBorderedGradientLayer.h>

#import "IDENavigationHUDDisposableLayer-Protocol.h"
#import "IDENavigationHUDSelectableLayer-Protocol.h"

@class CALayer, IDENavigationHUDSelection, IDENavigationHUDTabBarLayer, IDEWorkspaceTabController;

@interface IDENavigationHUDTabBarTabLayer : IDENavigationHUDBorderedGradientLayer <IDENavigationHUDSelectableLayer, IDENavigationHUDDisposableLayer>
{
    IDEWorkspaceTabController *_workspaceTabController;
    IDENavigationHUDTabBarLayer *_tabBarLayer;
    unsigned long long _tabState;
    struct CGSize _lastKnownOverlaySize;
    CALayer *_overlayLayer;
}

- (void)dispose;
- (id)initWithTabBarLayer:(id)arg1;
- (id)initWithWorkspaceTabController:(id)arg1 tabBarLayer:(id)arg2;
- (void)layoutSublayers;
- (id)navigationHUDController;
@property(readonly) IDENavigationHUDSelection *representativeSelection;
@property(readonly) BOOL representativeSelectionIsFinalForSingleMouseUp;
@property unsigned long long tabState; // @synthesize tabState=_tabState;
@property(readonly) IDENavigationHUDTabBarLayer *tabBarLayer; // @synthesize tabBarLayer=_tabBarLayer;
@property(readonly) IDEWorkspaceTabController *workspaceTabController; // @synthesize workspaceTabController=_workspaceTabController;

@end

