/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEExplorationContext.h>

@interface IDENoteExplorationContext : IDEExplorationContext
{
    id <IDENoteAnnotationExplorableItem> _note;
}

- (int)explorationType;
- (id)initWithNote:(id)arg1;
@property(readonly) id <IDENoteAnnotationExplorableItem> note; // @synthesize note=_note;

@end

