/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEOpenQuicklyMatch.h>

@class IDEIndexSymbol;

@interface IDEOpenQuicklyIndexSymbolMatch : IDEOpenQuicklyMatch
{
    IDEIndexSymbol *_indexSymbol;
}

- (id)image;
- (id)initWithIndexSymbol:(id)arg1;
- (BOOL)isEqualToOpenQuicklyMatch:(id)arg1;
- (BOOL)isEqualToOpenQuicklySymbolMatch:(id)arg1;
- (id)locationGivenMatchContext:(id)arg1;
- (int)matchTypeGivenMatchContext:(id)arg1;
- (double)scoreGivenMatchContext:(id)arg1;
- (double)symbolTypeScoreCoefficient;

@end

