/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEOpenQuicklyPattern.h>

@class NSCharacterSet;

@interface IDEOpenQuicklySingleCharacterPattern : IDEOpenQuicklyPattern
{
    NSCharacterSet *eitherCaseSet;
    NSCharacterSet *exactCaseSet;
    unsigned short lowercasePattern;
}

- (id)initWithPattern:(id)arg1;
- (id)matchedRanges:(id)arg1;
- (BOOL)matchesCandidate:(id)arg1;
- (double)scoreCandidate:(id)arg1;

@end

