/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTTableView.h"

@interface IDEOpenQuicklyTableView : DVTTableView
{
    id _becomeKeyNotificationObserver;
    id _resignKeyNotificationObserver;
}

- (BOOL)acceptsFirstResponder;
- (void)highlightSelectionInClipRect:(struct CGRect)arg1;
- (void)viewWillMoveToWindow:(id)arg1;

@end

