/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IDEOpenQuicklyPattern, NSString;

@interface IDEOpenQuicklyMatchContext : NSObject
{
    NSString *_workspacePath;
    NSString *_input;
    NSString *_line;
    IDEOpenQuicklyPattern *_pattern;
}

- (id)description;
- (id)initWithWorkspacePath:(id)arg1 input:(id)arg2 line:(id)arg3;
@property(readonly) NSString *line; // @synthesize line=_line;
@property(readonly) IDEOpenQuicklyPattern *pattern; // @synthesize pattern=_pattern;
@property(readonly) NSString *workspacePath; // @synthesize workspacePath=_workspacePath;

@end

