/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSWindow.h"

@interface IDEOrganizerWindow : NSWindow
{
    BOOL _firstResponderLocked;
}

@property BOOL firstResponderLocked; // @synthesize firstResponderLocked=_firstResponderLocked;
- (BOOL)makeFirstResponder:(id)arg1;

@end

