/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDENavigator.h>

@class IDENavigatorOutlineView, NSArray, NSIndexSet, NSMutableArray;

@interface IDEOutlineBasedNavigator : IDENavigator
{
    id _rootItemObservingToken;
    IDENavigatorOutlineView *_outlineView;
    NSArray *_objects;
    NSArray *_selectedObjects;
    id <IDEOpenRequest> _lastOpenRequest;
}

+ (void)initialize;
- (void)_clearRootNavigableItemObserving;
- (void)_openNavigableItem:(id)arg1 eventType:(unsigned long long)arg2;
- (void)_setupRootNavigableItemObserving;
@property(readonly) NSIndexSet *clickedRowIndexes;
@property(readonly) NSIndexSet *contextMenuSelectedRowIndexes;
- (id)contextMenuSelection;
- (BOOL)delegateFirstResponder;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)invalidate;
- (id)itemsForNameArrays:(id)arg1;
@property id <IDEOpenRequest> lastOpenRequest; // @synthesize lastOpenRequest=_lastOpenRequest;
- (void)loadView;
- (id)nameArraysForItems:(id)arg1;
- (id)navigableItemWithName:(id)arg1 inArray:(id)arg2;
@property NSArray *objects; // @synthesize objects=_objects;
- (void)openClickedNavigableItemAction:(id)arg1;
- (void)openDoubleClickedNavigableItemsAction:(id)arg1;
- (void)openSelectedNavigableItemsKeyAction:(id)arg1;
- (id)openSpecifierForNavigableItem:(id)arg1 error:(id *)arg2;
@property IDENavigatorOutlineView *outlineView; // @synthesize outlineView=_outlineView;
- (BOOL)shouldOpenNavigableItem:(id)arg1;
- (void)updateBoundContent;
- (void)updateOutlineViewContents;

// Remaining properties
@property(readonly) NSMutableArray *mutableSelectedObjects; // @dynamic mutableSelectedObjects;
@property NSArray *selectedObjects; // @dynamic selectedObjects;

@end

