/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSWindowController.h"

#import "DVTReplacementViewDelegate-Protocol.h"
#import "DVTStateRepositoryDelegate-Protocol.h"
#import "DVTStatefulObject-Protocol.h"
#import "IDEEditorAreaContainer-Protocol.h"
#import "NSToolbarDelegate-Protocol.h"
#import "NSWindowDelegate-Protocol.h"
#import "NSWindowRestoration-Protocol.h"

@class DVTDelayedValidator, DVTExtension, DVTReplacementView, DVTStateRepository, DVTStateToken, IDEEditorArea, NSArray, NSDictionary;

@interface IDEOrganizerWindowController : NSWindowController <NSWindowRestoration, NSToolbarDelegate, NSWindowDelegate, IDEEditorAreaContainer, DVTStatefulObject, DVTStateRepositoryDelegate, DVTReplacementViewDelegate>
{
    DVTReplacementView *_contentReplacementView;
    NSArray *_sources;
    NSArray *_organizerSourceExtensions;
    NSArray *_organizerSourceExtensionIdentifiers;
    NSDictionary *_organizerSourceExtensionsForIdentifier;
    DVTExtension *_currentExtension;
    DVTStateToken *_stateToken;
    DVTStateRepository *_stateRepository;
    DVTDelayedValidator *_stateSavingValidator;
}

+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (void)restoreWindowWithIdentifier:(id)arg1 state:(id)arg2 completionHandler:(id)arg3;
+ (id)sharedOrganizerWindowController;
- (void)_cacheOrganizerSourceExtensions;
- (BOOL)_loadStateData:(id *)arg1;
- (BOOL)_saveStateData:(id *)arg1;
- (void)_selectToolbarItem:(id)arg1;
- (id)_selectableToolbarItems;
- (void)_setWindowTitleWithExtension:(id)arg1;
- (id)_stateRepositoryFilePath;
- (void)commitStateToDictionary:(id)arg1;
@property DVTExtension *currentExtension; // @synthesize currentExtension=_currentExtension;
- (id)currentOrganizerSource;
@property(readonly) IDEEditorArea *editorArea;
- (id)init;
- (void)replacementView:(id)arg1 didInstallViewController:(id)arg2;
- (void)replacementView:(id)arg1 willCloseViewController:(id)arg2;
- (void)revertStateWithDictionary:(id)arg1;
- (void)selectNextTab:(id)arg1;
- (void)selectNextTabForwards:(BOOL)arg1;
- (void)selectPreviousTab:(id)arg1;
@property(copy) NSArray *sources; // @synthesize sources=_sources;
@property DVTStateToken *stateToken; // @synthesize stateToken=_stateToken;
- (void)showOrganizerSourceWithIdentifier:(id)arg1;
- (void)showWindow:(id)arg1;
@property(readonly) DVTStateRepository *stateRepository; // @synthesize stateRepository=_stateRepository;
- (void)stateRepositoryDidChange:(id)arg1;
@property(readonly) DVTDelayedValidator *stateSavingValidator; // @synthesize stateSavingValidator=_stateSavingValidator;
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;
- (id)toolbarSelectableItemIdentifiers:(id)arg1;
- (void)windowDidLoad;
- (void)windowDidResize:(id)arg1;

@end

