/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDESourceCodeGenerator.h>

@interface IDEObjectiveCSourceCodeGenerator : IDESourceCodeGenerator
{
}

+ (id)allTeardownCounterparts;
+ (BOOL)isTeardownCounterpart:(id)arg1;
+ (id)teardownMethodNameForCounterpart:(id)arg1;
- (id)baseSourceCodeForMethodDeclaratorWithName:(id)arg1 options:(id)arg2;
- (id)documentLocationForCounterpartBlockForClassSymbol:(SEL)arg1 options:(id)arg2;
- (id)effectiveOptionsForTeardownCounterpart:(id)arg1 originalOptions:(id)arg2;
- (id)generateSourceCodeForCategoryDeclarationForClassNamed:(id)arg1 categoryName:(id)arg2 options:(id)arg3;
- (id)generateSourceCodeForCategoryDefinitionForClassNamed:(id)arg1 categoryName:(id)arg2 options:(id)arg3;
- (id)generateSourceCodeForClassMethodDeclarationWithName:(id)arg1 options:(id)arg2;
- (id)generateSourceCodeForClassMethodDefinitionWithName:(id)arg1 options:(id)arg2;
- (id)generateSourceCodeForInstanceMethodDeclarationWithName:(id)arg1 options:(id)arg2;
- (id)generateSourceCodeForInstanceMethodDefinitionWithName:(id)arg1 options:(id)arg2;
- (id)generateSourceCodeForInstanceVariableDeclarationWithName:(id)arg1 type:(id)arg2 options:(id)arg3;
- (id)generateSourceCodeForMessageSendWithOptions:(id)arg1;
- (id)generateSourceCodeForPropertyAtSynthesizeWithName:(id)arg1 options:(id)arg2;
- (id)generateSourceCodeForPropertyDeclarationWithName:(id)arg1 type:(id)arg2 options:(id)arg3;
- (id)generateSourceCodeForPropertyGetterWithName:(id)arg1 options:(id)arg2;
- (id)generateSourceCodeForPropertySetterWithName:(id)arg1 options:(id)arg2;
- (id)generatedLanguage;
- (id)inferInstanceVariableNameFromSurroundings:(id)arg1 classSymbol:(id)arg2;
- (BOOL)isInsertionLocationForCounterpart:(id)arg1 equivalentToInsertionLocationForRepresentativeCounterpart:(id)arg2;
- (BOOL)preferUnderbarPrefixForInferredInstanceVariableNames;
- (id)prepareToAddClassMethodWithName:(id)arg1 inClassNamed:(id)arg2 options:(id)arg3 error:(id *)arg4;
- (id)prepareToAddInstanceMethodWithName:(id)arg1 inClassNamed:(id)arg2 options:(id)arg3 error:(id *)arg4;
- (id)prepareToAddInstanceVariableWithName:(id)arg1 type:(id)arg2 inClassNamed:(id)arg3 options:(id)arg4 error:(id *)arg5;
- (id)prepareToAddPropertyWithName:(id)arg1 type:(id)arg2 inClassNamed:(id)arg3 options:(id)arg4 error:(id *)arg5;
- (id)primitiveAddMethodWithName:(id)arg1 inClassNamed:(id)arg2 options:(id)arg3 instanceMethod:(BOOL)arg4 error:(id *)arg5;
- (id)typeString:(id)arg1 concatenatedWithNameString:(id)arg2;

@end

