/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "NSMenuDelegate-Protocol.h"
#import "NSTableViewDataSource-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"

@class DVTBorderedView, DVTGradientImageButton, DVTGradientImagePopUpButton, DVTImageAndTextColumn, DVTPreferenceSetManager, IDEControlGroup, NSArray, NSArrayController, NSMapTable, NSMenuItem, NSTableView;

@interface IDEPreferenceSetViewController : IDEViewController <NSTableViewDelegate, NSTableViewDataSource, NSMenuDelegate>
{
    NSMenuItem *_duplicateSelectedThemeMenuItem;
    NSMenuItem *_newThemeFromTemplateMenuItem;
    DVTImageAndTextColumn *_tableColumn;
    NSTableView *_tableView;
    DVTGradientImagePopUpButton *_addPopUpButton;
    DVTGradientImageButton *_removeButton;
    IDEControlGroup *_controlGroup;
    DVTBorderedView *_controlGroupBorderedView;
    NSArrayController *_prefSetsArrayController;
    DVTPreferenceSetManager *_preferenceSetManager;
    NSMapTable *_observerTokensForPreferenceSetsMapTable;
    id <DVTObservingToken> _currentPreferenceSetObserver;
    BOOL _hasBeenSetup;
}

+ (id)keyPathsForValuesAffectingCanDeleteActivePreferenceSet;
- (void)_addObserversForPreferenceSet:(id)arg1;
- (void)_duplicatePreferenceSet:(id)arg1;
- (void)_removeObserversForPreferenceSet:(id)arg1;
- (id)_selectedPreferenceSet;
- (BOOL)canDeleteActivePreferenceSet;
- (void)deleteActivePreferenceSet:(id)arg1;
- (void)duplicateActivePreferenceSet:(id)arg1;
- (void)duplicateSelectedDefaultThemeFromMenu:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;
- (void)menuNeedsUpdate:(id)arg1;
@property DVTPreferenceSetManager *preferenceSetManager; // @synthesize preferenceSetManager=_preferenceSetManager;
@property(readonly) NSTableView *preferenceSetTableView; // @synthesize preferenceSetTableView=_tableView;
@property(readonly) NSArray *preferenceSetsSortDescriptors;
- (void)setupWithPreferenceSetManager:(id)arg1;
- (id)tableView:(id)arg1 selectionIndexesForProposedSelection:(id)arg2;
- (void)tableView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)tableViewSelectionDidChange:(id)arg1;

@end

