/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "IDECapsuleListViewDataSource-Protocol.h"

@class DVTBorderedView, DVTChoice, DVTFilePathFieldCell, DVTStackView, DVTTabChooserView, IDEArgumentsCapsuleSheetController, IDECapsuleListView, IDEEnvironmentVariablesCapsuleSheetController, IDEProfileSchemeAction, IDEScheme, IDEWorkspace, NSBox, NSMutableArray, NSPopUpButton, NSView;

@interface IDEProfileActionSheetController : IDEViewController <IDECapsuleListViewDataSource>
{
    DVTTabChooserView *_tabChooser;
    IDECapsuleListView *_capsuleListView;
    DVTBorderedView *_capsuleListEnclosingBorderedView;
    NSPopUpButton *_runnablePopUp;
    NSPopUpButton *_analysisToolsPopUp;
    DVTFilePathFieldCell *_workingDirectoryTextFieldCell;
    NSView *_infoTabViewContentView;
    NSPopUpButton *_macroExpansionRunnableBuildablesPopUp;
    NSBox *_dividerLine;
    DVTStackView *_optionsStackView;
    NSView *_resumeOptionView;
    NSView *_debugDocumentVersioningOptionView;
    NSView *_workingDirectoryOptionView;
    DVTChoice *_infoChoice;
    DVTChoice *_conditionsChoice;
    DVTChoice *_optionsChoice;
    IDEScheme *_runContext;
    IDEProfileSchemeAction *_runPhase;
    BOOL _optionsUpdatedInCurrentRunLoop;
    IDEArgumentsCapsuleSheetController *_argumentsViewController;
    IDEEnvironmentVariablesCapsuleSheetController *_environmentVariablesViewController;
    id <DVTObservingToken> _runnableBuildableProductsObservingToken;
    id <DVTObservingToken> _runContextRunnableObservingToken;
    id <DVTObservingToken> _launchActionArgsEnvLinkObservingToken;
    NSMutableArray *_observationTokens;
    unsigned long long _runnablePopUpRunnableBuildableProductsCount;
    BOOL _runnablePopUpHasCustomRunnable;
}

+ (id)defaultViewNibName;
+ (void)initialize;
- (void)DVTFilePathFieldCell:(id)arg1 chooserSelectedPath:(id)arg2;
- (id)DVTFilePathFieldCell:(id)arg1 resolvedPathForPath:(id)arg2;
- (void)_addMenuItemForAnalysisTool:(id)arg1;
- (void)_addMenuItemForAnalysisTools:(id)arg1;
- (void)_analysisToolSelected:(id)arg1;
- (id)_iconForBuildable:(id)arg1;
- (unsigned long long)_indexOfDebuggerFromScheme;
- (void)_macroExpansionRunnableBuildableSelected:(id)arg1;
- (void)_resetOptionsUpdatedFlag;
- (void)_runnableBuildableProductsDidChange;
- (void)_runnableDidUpdate;
- (void)_selectedSchemeChanged:(id)arg1;
- (void)_updateAnalysisToolsPopUp;
- (void)_updateMacroExpansionRunnablePopUp;
- (void)_updateMacroExpansionRunnablePopUpEnablement;
- (void)_updateMacroExpansionRunnablePopUpSelection;
- (void)_updateRunnablePopUp;
- (void)_updateSupportedOptions;
- (id)capsuleListView:(id)arg1 viewControllerForRow:(long long)arg2;
- (id)dvtExtraBindings;
- (void)invalidate;
- (void)loadView;
- (long long)numberOfObjectsInCapsuleListView:(id)arg1;
@property IDEScheme *runContext; // @synthesize runContext=_runContext;
@property IDEProfileSchemeAction *runPhase; // @synthesize runPhase=_runPhase;
- (void)runnablePopUpAction:(id)arg1;
@property DVTTabChooserView *tabChooser; // @synthesize tabChooser=_tabChooser;
- (void)updateBoundContent;
- (void)updateBoundIDERunContextBinding;
@property(readonly) IDEWorkspace *workspace;

@end

