/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSPathCell.h"

#import "DVTFilteringMenuDelegate-Protocol.h"
#import "NSMenuDelegate-Protocol.h"

@class DVTDelayedValidator, IDEPathCellNavigableItemObserver, IDEPathComponentCell, NSMenu, NSMutableArray, NSMutableSet;

@interface IDEPathCell : NSPathCell <DVTFilteringMenuDelegate, NSMenuDelegate>
{
    NSMenu *_trackingMenu;
    IDEPathComponentCell *_clickedIDEPathComponentCell;
    IDEPathCellNavigableItemObserver *_itemObserver;
    NSMutableArray *_itemsObservedForChildItems;
    NSMutableSet *_cellsWithDirtyImages;
    NSMutableSet *_cellsWithDirtyNames;
    DVTDelayedValidator *_dirtyCellValidator;
    int _borderSides;
    int _gradientStyle;
    struct {
        unsigned int _lastComponentFillsWidth:1;
        unsigned int _delegateRespondsToShouldSeparateDisplayOfChildItemsForItem:1;
        unsigned int _delegateRespondsToChildItemsForItem:1;
        unsigned int _delegateRespondsToShouldPopUpMenuForPathComponentCell:1;
        unsigned int _delegateProvidesMenuItems:1;
        unsigned int _delegateProvidesAccessibilityDescriptions:1;
        unsigned int _delegateProvidesToolTips:1;
    } _idePathCellFlags;
    BOOL _needsToUpdateComponentCells;
}

+ (unsigned long long)defaultFocusRingType;
- (void)_IDEPathCellCommonInit;
- (id)_componentCellWithRepresentedObject:(id)arg1 title:(id)arg2 image:(id)arg3;
- (id)_componentCellsFromItems:(id)arg1;
- (BOOL)_delegate_shouldSeparateDisplayOfChildItemsForItem:(id)arg1;
- (void)_handleClickInComponentCell:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3;
- (id)_menuItemWithNavigableItem:(id)arg1 additionalItems:(id *)arg2 currentGroupIdentifier:(id *)arg3;
- (id)_noSelectionComponentCell;
- (void)_selectItem:(id)arg1;
- (void)_setupSubmenuForMenuItem:(id)arg1;
- (void)_updateComponentCells;
- (void)_updateDirtyCells:(id)arg1;
- (BOOL)acceptsFirstResponder;
- (id)accessibilityActionNames;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (id)backgroundColor;
@property int borderSides; // @synthesize borderSides=_borderSides;
- (void)cancelMenuTracking;
- (id)childItemsForItem:(id)arg1;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)filterItems:(id)arg1 inMenu:(id)arg2 forSearchString:(id)arg3;
- (struct CGRect)grabRectInView:(id)arg1;
@property int gradientStyle; // @synthesize gradientStyle=_gradientStyle;
- (id)ide_accessibilityChildMenuForChild:(id)arg1;
- (id)ide_accessibilityObjectForComponentCell:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)ide_accessibilityPerformPressForChild:(id)arg1;
- (id)ide_accessibilityPopUpMenuParent:(id)arg1;
- (id)ide_accessibilityPositionOfChild:(id)arg1;
- (struct CGRect)ide_accessibilityScreenRectForPathComponent:(id)arg1;
- (id)ide_accessibilitySizeOfChild:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)invalidateComponentCells;
- (void)invalidateImageForPathComponentCell:(id)arg1;
- (void)invalidateNameForPathComponentCell:(id)arg1;
@property BOOL lastComponentFillsWidth;
- (id)lineageForNavigableItem:(id)arg1 rootItems:(id)arg2;
- (void)menuNeedsUpdate:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)pathComponentCellAtPoint:(struct CGPoint)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (id)pathComponentCellForRepresentedObject:(id)arg1;
- (id)peerNavigableItemsForComponentCell:(id)arg1;
- (void)popUpMenuForComponentCell:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3;
- (void)populatePopUpMenu:(id)arg1 withItems:(id)arg2;
- (struct CGRect)rectOfPathComponentCell:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (void)reset;
- (void)setDelegate:(id)arg1;
- (void)setFont:(id)arg1;
- (void)setNeedsDisplayForCell:(id)arg1;
- (void)startObservingChildItemsOfMenuItems:(id)arg1;
- (void)stopObservingChildItemsOfAllItems;
- (id)toolTipManager:(id)arg1 toolTipForView:(id)arg2 location:(struct CGPoint)arg3 tipSourceRect:(struct CGRect *)arg4;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;

@end

