/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSPathComponentCell.h"

@interface IDEPathComponentCell : NSPathComponentCell
{
    int _gradientStyle;
    BOOL _isLastItem;
    BOOL _isFirstItem;
}

+ (id)_textDrawingAttributes;
- (id)_attributedStringValue;
- (void)_drawChevronDividerInFrame:(struct CGRect)arg1;
- (void)_drawDividerForFrame:(struct CGRect)arg1 inControlView:(id)arg2;
- (double)_leftDividerWidth;
- (double)_rightDividerWidth;
- (void)_useChevronForLeftEdge:(char *)arg1 rightEdge:(char *)arg2;
- (struct CGSize)cellSizeForBounds:(struct CGRect)arg1;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
@property int gradientStyle; // @synthesize gradientStyle=_gradientStyle;
- (double)iconSize;
@property BOOL isFirstItem; // @synthesize isFirstItem=_isFirstItem;
@property BOOL isLastItem; // @synthesize isLastItem=_isLastItem;
- (id)shadow;

@end

