/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDETextSubstitutionTemplateInstantiationContext.h>

@class IDEWorkspace;

@interface IDERefactoringCreateSuperclassTemplateInstantiationContext : IDETextSubstitutionTemplateInstantiationContext
{
    IDEWorkspace *_workspace;
}

@property IDEWorkspace *workspace; // @synthesize workspace=_workspace;

@end

