/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDERefactoringInputValidator.h>

@class IDEIndex, NSString;

@interface IDERefactoringCreateSuperclassInputValidator : IDERefactoringInputValidator
{
    NSString *_subclassName;
    IDEIndex *_index;
}

- (id)_sameAsExistingClassLocalizedMessage;
- (id)_sameAsSubclassLocalizedMessage;
@property IDEIndex *index; // @synthesize index=_index;
- (BOOL)isStringValid:(id)arg1 otherStrings:(id)arg2 localizedMessage:(id *)arg3 invalidRange:(struct _NSRange *)arg4;
@property NSString *subclassName; // @synthesize subclassName=_subclassName;

@end

