/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTAutoLayoutView.h"

@class NSView;

@interface IDERefactoringRevealingView : DVTAutoLayoutView
{
    double _minimumHeight;
    NSView *_revealableView;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutTopDown;
@property NSView *revealableView; // @synthesize revealableView=_revealableView;

@end

