/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDERefactoringTransformationViewController.h>

@class NSString;

@interface IDERefactoringMoveDownViewController : IDERefactoringTransformationViewController
{
    NSString *_containerSymbolName;
}

@property(copy) NSString *containerSymbolName; // @synthesize containerSymbolName=_containerSymbolName;
- (id)nibName;
- (id)previewSummary;
- (void)setOriginalSymbol:(id)arg1;
- (void)setWindowController:(id)arg1;
- (id)userInput;

@end

