/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDERefactoringTransformationViewController.h>

@class IDERefactoringInputValidator, NSButtonCell, NSDictionary, NSMatrix, NSTextField;

@interface IDERefactoringExtractViewController : IDERefactoringTransformationViewController
{
    NSTextField *_newSignatureField;
    NSMatrix *_methodOrFunctionMatrix;
    NSButtonCell *_methodButton;
    NSButtonCell *_functionButton;
    BOOL _methodAllowed;
    IDERefactoringInputValidator *_methodValidator;
    IDERefactoringInputValidator *_functionValidator;
    IDERefactoringInputValidator *_currentValidator;
    struct _NSRange _functionNameRange;
    struct _NSRange _methodNameRange;
    NSDictionary *_transformationData;
}

- (void)allowUserInput:(BOOL)arg1;
- (void)controlTextDidChange:(id)arg1;
- (void)loadView;
- (id)nibName;
- (id)previewSummary;
- (void)selectFunctionOrMethod:(id)arg1;
- (void)setInitialData:(id)arg1;
- (void)setWindowController:(id)arg1;
- (id)userInput;

@end

