/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDERefactoring.h"

@interface IDERefactoring (IDERefactoringKitAdditions)
+ (id)currentExpressionSource;
- (BOOL)isRefactoringAllowedForSelectionValidationClass:(Class)arg1 sourceExpression:(id)arg2 error:(id *)arg3;
- (BOOL)isRefactoringAllowedPerIndexing:(id *)arg1;
- (id)mainFileForSelectionFilePath:(id)arg1 transformation:(id)arg2 buildSettings:(id *)arg3;
- (id)sessionWithTransformation:(id)arg1 sourceExpression:(id)arg2;
- (id)symbolFromSourceExpression:(id)arg1;
@end

