/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDERefactoringNibFileChange.h>

@interface IDERefactoringNibFileClassChange : IDERefactoringNibFileChange
{
}

+ (id)commandString;
- (id)destinationClass;
- (void)setDestinationClass:(id)arg1;
- (void)setSourceClass:(id)arg1;
- (id)sourceClass;

@end

