/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTDelayedMenuButton.h"

@class IDEWorkspaceWindowController, NSString, NSToolbarItem;

@interface IDERunPauseContinueToolbarButton : DVTDelayedMenuButton
{
    IDEWorkspaceWindowController *_windowController;
    id <DVTObservingToken> _toolbarIdleObservingToken;
    NSString *_label;
    NSString *_tooltip;
    NSToolbarItem *_toolbarItem;
    BOOL _isValidToolbarItem;
}

- (id)_newToolbarViewHitTest:(struct CGPoint)arg1;
- (void)_setButtonToAnalyzeStyle:(id)arg1 menuItem:(id)arg2;
- (void)_setButtonToBuildStyle:(id)arg1 menuItem:(id)arg2;
- (void)_setButtonToProfileStyle:(id)arg1 menuItem:(id)arg2;
- (void)_setButtonToRunStyle:(id)arg1 menuItem:(id)arg2;
- (void)_setButtonToTestStyle:(id)arg1 menuItem:(id)arg2;
- (void)_setToolbarItem:(id)arg1;
- (void)_swizzleToolbarViewHitTest;
- (id)_toolbarItem;
- (void)_updateEnablement;
- (void)_updateIcon;
- (void)_updateToolbarItem;
- (id)addAnalyzeButtonToMenu:(id)arg1;
- (id)addProfileButtonToMenu:(id)arg1;
- (id)addRunButtonToMenu:(id)arg1;
- (id)addTestButtonToMenu:(id)arg1;
- (id)initWithWindowController:(id)arg1;
@property BOOL isValidToolbarItem; // @synthesize isValidToolbarItem=_isValidToolbarItem;
- (BOOL)menuItemRepresentsBuildOnly:(id)arg1;
- (void)performAnalyzeAction:(id)arg1;
- (void)performProfileAction:(id)arg1;
- (void)performRunAction:(id)arg1;
- (void)performTestAction:(id)arg1;

@end

