/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDERefactoringResult-Protocol.h"

@class DVTFilePath, NSArray, NSMutableArray, NSString;

@interface IDERefactoringFileChangeSet : NSObject <IDERefactoringResult>
{
    DVTFilePath *_filePath;
    DVTFilePath *_tempFilePath;
    NSMutableArray *_changes;
    NSString *_newName;
}

+ (id)changeSetForFileAtPath:(id)arg1 transformation:(id)arg2 error:(id *)arg3;
- (void)addChange:(id)arg1;
- (BOOL)applyChangesWithError:(id *)arg1;
@property(readonly) NSArray *changes; // @synthesize changes=_changes;
- (id)description;
@property(readonly) DVTFilePath *filePath; // @synthesize filePath=_filePath;
- (id)initWithFilePath:(id)arg1;
- (BOOL)isEqualToFileChangeSet:(id)arg1;
- (id)newFilePath;
@property NSString *newName; // @synthesize newName=_newName;
- (long long)numberOfChanges;
- (id)resultFilePath;
- (BOOL)resultIsEditable;
- (id)resultNewFileName;
- (id)resultTempFilePath;
- (BOOL)willRenameFile;
- (void)writeTempResults;
- (BOOL)writesOwnTempResults;

@end

