/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDENavigator.h>

@class DVTBorderedView, DVTChooserView, DVTDocumentLocation, IDENavigatorFilterControlBar, IDENavigatorOutlineView, IDEReviewFilesButtonCell, IDEReviewFilesImageCell, IDESelection, NSArray, NSImage, NSIndexSet, NSMenu, NSMutableArray, NSMutableIndexSet, NSString, NSTabView;

@interface IDEReviewFilesNavigator : IDENavigator
{
    DVTChooserView *_chooserView;
    NSTabView *_tabView;
    IDENavigatorOutlineView *_workspaceOutlineView;
    IDENavigatorOutlineView *_fileSystemOutlineView;
    IDENavigatorOutlineView *_flatOutlineView;
    IDENavigatorOutlineView *_issuesOutlineView;
    DVTBorderedView *_outerBorderedView;
    IDEReviewFilesButtonCell *_checkboxCell;
    IDEReviewFilesImageCell *_imageCell;
    NSImage *_successImage;
    NSImage *_failureImage;
    NSMutableArray *_checkedFilePaths;
    NSMutableArray *_completedFilePaths;
    NSArray *_errorFilePaths;
    NSMutableArray *_disabledFilePaths;
    NSArray *_viewChoices;
    NSIndexSet *_selectedViewIndexes;
    NSString *_selectedChoiceWithWorkspaceKey;
    NSString *_selectedChoiceWithoutWorkspaceKey;
    NSArray *_selectedFilePaths;
    DVTDocumentLocation *_selectedDocumentLocation;
    id <IDEReviewFilesDataSource> _workspaceDataSource;
    id <IDEReviewFilesDataSource> _fileSystemDataSource;
    id <IDEReviewFilesDataSource> _flatDataSource;
    id <IDEReviewFilesDataSource> _issueDataSource;
    int _activity;
    NSMutableIndexSet *_lastSelectedIndexes;
    DVTBorderedView *_filterControlBarBorderedView;
    IDENavigatorFilterControlBar *_filterControlBar;
    NSString *_filterString;
    BOOL _showFilter;
    BOOL _showCheckboxes;
}

+ (void)initialize;
+ (id)keyPathsForValuesAffectingCheckedFilePaths;
+ (id)keyPathsForValuesAffectingFilterPredicate;
@property int activity; // @synthesize activity=_activity;
- (id)checkboxCell;
@property NSMutableArray *checkedFilePaths; // @synthesize checkedFilePaths=_checkedFilePaths;
@property NSMutableArray *completedFilePaths; // @synthesize completedFilePaths=_completedFilePaths;
@property NSMenu *contextMenu;
- (id)contextMenuSelectedRowIndex;
- (id)contextMenuSelectedRowIndexes;
@property(readonly) IDESelection *contextMenuSelection;
@property(readonly) IDENavigatorOutlineView *currentOutlineView;
@property NSMutableArray *disabledFilePaths; // @synthesize disabledFilePaths=_disabledFilePaths;
- (id)domainIdentifier;
@property(copy) NSArray *errorFilePaths; // @synthesize errorFilePaths=_errorFilePaths;
- (id)failureImage;
@property id <IDEReviewFilesDataSource> fileSystemDataSource; // @synthesize fileSystemDataSource=_fileSystemDataSource;
@property(readonly) IDENavigatorOutlineView *fileSystemOutlineView;
- (id)filterPredicate;
@property(copy) NSString *filterString; // @synthesize filterString=_filterString;
@property id <IDEReviewFilesDataSource> flatDataSource; // @synthesize flatDataSource=_flatDataSource;
@property(readonly) IDENavigatorOutlineView *flatOutlineView;
- (id)imageCell;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property id <IDEReviewFilesDataSource> issueDataSource; // @synthesize issueDataSource=_issueDataSource;
@property(readonly) IDENavigatorOutlineView *issuesOutlineView;
- (void)loadView;
- (id)navigableChildItemOfItem:(id)arg1 matchingFilePath:(id)arg2;
- (id)navigableItemsInOutlineView:(id)arg1 forFilePaths:(id)arg2;
- (id)outlineView:(id)arg1 childItemsForItem:(id)arg2;
- (id)outlineView:(id)arg1 dataCellForTableColumn:(id)arg2 item:(id)arg3;
- (BOOL)outlineView:(id)arg1 isGroupHeaderItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (id)outlineView:(id)arg1 selectionIndexesForProposedSelection:(id)arg2;
- (void)outlineView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 byItem:(id)arg4;
- (BOOL)outlineView:(id)arg1 shouldShowOutlineCellForItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldTrackCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (void)refreshItemsAtFilePaths:(id)arg1;
- (void)reloadAvailableNavigators;
@property(copy) NSString *selectedChoiceWithWorkspaceKey; // @synthesize selectedChoiceWithWorkspaceKey=_selectedChoiceWithWorkspaceKey;
@property(copy) NSString *selectedChoiceWithoutWorkspaceKey; // @synthesize selectedChoiceWithoutWorkspaceKey=_selectedChoiceWithoutWorkspaceKey;
@property(readonly) DVTDocumentLocation *selectedDocumentLocation; // @synthesize selectedDocumentLocation=_selectedDocumentLocation;
@property(retain) NSMutableArray *selectedFilePaths;
- (id)selectedFilePathsOfOutlineView:(id)arg1;
- (id)selectedNavigableItemsOfOutlineView:(id)arg1;
@property(copy) NSIndexSet *selectedViewIndexes; // @synthesize selectedViewIndexes=_selectedViewIndexes;
- (void)setSelectedFilePaths:(id)arg1 forOutlineView:(id)arg2;
- (void)setSelectedNavigableItems:(id)arg1 forOutlineView:(id)arg2;
@property BOOL showCheckboxes; // @synthesize showCheckboxes=_showCheckboxes;
@property BOOL showFilter; // @synthesize showFilter=_showFilter;
@property id <IDEReviewFilesDataSource> workspaceDataSource; // @synthesize workspaceDataSource=_workspaceDataSource;
- (void)setupViewChoices;
- (id)successImage;
- (void)uncheckItemsAtFilePaths:(id)arg1;
- (void)updateSelectedDocumentLocation;
@property(readonly) NSArray *viewChoices; // @synthesize viewChoices=_viewChoices;
- (void)viewDidInstall;
- (void)viewWillUninstall;
@property(readonly) IDENavigatorOutlineView *workspaceOutlineView;

@end

