/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSButton.h"

@interface IDERoundToolbarButton : NSButton
{
}

+ (id)toolbarButtonWithActiveImage:(id)arg1 inactiveImage:(id)arg2 pressedImage:(id)arg3 buttonType:(unsigned long long)arg4;
- (id)hitTest:(struct CGPoint)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)isFlipped;

@end

