/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDERefactoringNibFileChange.h>

@interface IDERefactoringNibFileActionChange : IDERefactoringNibFileChange
{
}

+ (id)commandString;
- (id)destinationActionClass;
- (id)destinationActionName;
- (id)destinationActionType;
- (id)initWithFileChangeSet:(id)arg1 fileLocation:(id)arg2;
- (void)setDestinationActionClass:(id)arg1;
- (void)setDestinationActionName:(id)arg1;
- (void)setDestinationActionType:(id)arg1;
- (void)setSourceActionClass:(id)arg1;
- (void)setSourceActionName:(id)arg1;
- (void)setSourceActionType:(id)arg1;
- (id)sourceActionClass;
- (id)sourceActionName;
- (id)sourceActionType;

@end

