/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDERefactoringFileChange.h>

@class NSMutableDictionary;

@interface IDERefactoringNibFileChange : IDERefactoringFileChange
{
    long long _objectID;
    NSMutableDictionary *_commands;
    NSMutableDictionary *_properties;
}

+ (id)commandString;
- (id)_commandForKey:(id)arg1;
- (id)_propertyForKey:(id)arg1;
- (void)_removeCommandForKey:(id)arg1;
- (void)_removePropertyForKey:(id)arg1;
- (void)_setCommand:(id)arg1 forKey:(id)arg2;
- (void)_setProperty:(id)arg1 forKey:(id)arg2;
- (BOOL)applyChange;
@property(readonly) NSMutableDictionary *commands; // @synthesize commands=_commands;
- (id)initWithFileChangeSet:(id)arg1 fileLocation:(id)arg2;
@property long long objectID; // @synthesize objectID=_objectID;
@property(readonly) NSMutableDictionary *properties; // @synthesize properties=_properties;

@end

