/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEReadOnlyItemsManager.h"

@interface IDEReadOnlyItemsManager (IDEKitAdditions)
- (void)_confirmShouldUnlockAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (BOOL)_shouldSkipWarningAboutUnlocking;
- (void)_tryToUnlockItems:(id)arg1 itemName:(id)arg2 inWorkspace:(id)arg3 completionBlock:(id)arg4;
- (void)_warnAboutEditingAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)startUnlockOperationForItems:(id)arg1 name:(id)arg2 inWorkspace:(id)arg3 window:(id)arg4 completionBlock:(id)arg5;
- (void)warnAboutEditingLockedItems:(id)arg1 name:(id)arg2 forChangedObject:(id)arg3 inWorkspace:(id)arg4 window:(id)arg5 timeout:(unsigned long long)arg6 completionBlock:(id)arg7;
@end

