/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSViewAnimation.h"

@class NSWindow;

@interface IDERefactoringRevealingAnimation : NSViewAnimation
{
    NSWindow *_window;
}

- (id)initWithWindow:(id)arg1 animations:(id)arg2;
- (void)setCurrentProgress:(float)arg1;

@end

