/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDERefactoringTransformationViewController.h>

@class NSButton, NSString;

@interface IDERefactoringMoveUpViewController : IDERefactoringTransformationViewController
{
    NSButton *_moveRelatedMethodsCheckbox;
    NSString *_oldSuperclassName;
    NSString *_newSuperclassName;
}

- (void)allowUserInput:(BOOL)arg1;
@property NSString *newSuperclassName; // @synthesize newSuperclassName=_newSuperclassName;
- (id)nibName;
@property NSString *oldSuperclassName; // @synthesize oldSuperclassName=_oldSuperclassName;
- (id)previewSummary;
- (void)setOriginalSymbol:(id)arg1;
- (void)setWindowController:(id)arg1;
- (id)userInput;

@end

