/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation-Protocol.h"

@class DVTStackBacktrace, IDEWorkspaceTabController;

@interface IDERunAlertMonitor : NSObject <DVTInvalidation>
{
    IDEWorkspaceTabController *_workspaceTabController;
    id _currentLaunchSessionStateNotificationObserver;
    id _currentLaunchSessionTargetOutputNotificationObserver;
    BOOL _targetOutputStateDetermined;
    BOOL _isInvalidated;
    DVTStackBacktrace *_invalidationBacktrace;
}

- (id)_createInternalHideIfNoOutputAlertForRunCompleteEvent:(id)arg1;
- (BOOL)_hasDoneExecutionStarted;
- (BOOL)_hasDoneExecutionStopped;
- (void)_runEvent:(id)arg1 inWorkspace:(id)arg2 modifyContext:(id)arg3;
- (void)_setHasDoneExecutionStarted;
- (void)_setHasDoneExecutionStopped;
- (void)_targetOutputStateChanged;
- (void)executionComplete;
- (void)executionStart;
- (id)initWithWorkspaceTabController:(id)arg1;
- (void)invalidate;
@property(readonly) DVTStackBacktrace *invalidationBacktrace; // @synthesize invalidationBacktrace=_invalidationBacktrace;
@property(readonly, getter=isValid) BOOL valid;

@end

