/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDERunSheetPhaseModel.h>

@interface IDERunSheetInstallPhaseModel : IDERunSheetPhaseModel
{
}

- (Class)detailViewControllerClass;
- (id)navigableItem_image;
- (Class)postActionsSubphaseModelClass;
- (Class)preActionsSubphaseModelClass;
- (id)runPhase;
- (id)schemeCommandTitle;
- (int)schemePhaseModelCommand;

@end

