/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDETemplateTextSubstitutionFactory.h>

@class NSString;

@interface IDERefactoringCreateSuperclassTemplateFactory : IDETemplateTextSubstitutionFactory
{
    NSString *_superclassName;
    NSString *_importFileName;
}

- (id)additionalMacrosForContext:(id)arg1;
@property(copy) NSString *importFileName; // @synthesize importFileName=_importFileName;
- (id)initWithSuperclassName:(id)arg1 importFileName:(id)arg2;
@property(copy) NSString *superclassName; // @synthesize superclassName=_superclassName;
- (BOOL)shouldAddCreatedDocumentsToVersionControl:(id)arg1;

@end

