/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDERefactoringFileChangeSet.h>

@class DVTFilePath, NSDictionary, NSMutableArray, NSMutableDictionary;

@interface IDERefactoringNibFileChangeSet : IDERefactoringFileChangeSet
{
    NSMutableArray *_commands;
    NSMutableDictionary *_properties;
    NSDictionary *_resultDictionary;
    BOOL _isWrapper;
    DVTFilePath *_filePathForWritableCheck;
}

+ (id)changeSetForFileAtPath:(id)arg1 transformation:(id)arg2 error:(id *)arg3;
- (void)addNibFileToolCommandDictionary:(id)arg1;
- (BOOL)applyChangesWithError:(id *)arg1;
- (id)initWithFilePath:(id)arg1;
- (id)nibFileToolCommandDictionaries;
- (void)removeNibFileToolCommandDictionary:(id)arg1;
- (void)removeNibFileToolPropertyDictionaryForKey:(id)arg1;
@property(readonly) NSDictionary *resultDictionary; // @synthesize resultDictionary=_resultDictionary;
- (BOOL)resultIsEditable;
- (void)setNibFileToolPropertyDictionary:(id)arg1 forKey:(id)arg2;
- (void)writeTempResults;
- (BOOL)writesOwnTempResults;

@end

