/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDEReviewFilesDataSource-Protocol.h"

@class IDENavigatorDataCell, IDEWorkspace, NSArray, NSPredicate, NSString;

@interface IDESourceControlReviewFilesDataSource : NSObject <IDEReviewFilesDataSource>
{
    IDENavigatorDataCell *_containerFileRefCell;
    IDENavigatorDataCell *_aggregateContainerFileRefCell;
    IDENavigatorDataCell *_fileReferenceCell;
    IDENavigatorDataCell *_groupCell;
    IDENavigatorDataCell *_plainObjectCell;
    IDENavigatorDataCell *_workingCopyTreeItemCell;
    IDENavigatorDataCell *_workingCopyTreeGroupCell;
    NSArray *_navigableItems;
    NSArray *_statusCategoryNames;
    NSString *_selectedRevisionIdentifier;
    NSPredicate *_filterPredicate;
    IDEWorkspace *_workspace;
}

+ (id)keyPathsForValuesAffectingFileSystemNavigableItems;
+ (id)keyPathsForValuesAffectingFlatNavigableItems;
+ (id)keyPathsForValuesAffectingWorkspaceNavigableItems;
- (id)aggregateContainerFileRefCell;
- (id)aggregateSourceControlCategoryStatusCellsWithRepresentedObject:(id)arg1;
- (id)containerFileRefCell;
- (id)fileReferenceCell;
@property(readonly) NSArray *fileSystemNavigableItems;
@property(copy) NSPredicate *filterPredicate; // @synthesize filterPredicate=_filterPredicate;
@property(readonly) NSArray *flatNavigableItems;
- (id)groupCell;
- (id)init;
- (id)issueNavigableItems;
@property(copy) NSArray *navigableItems; // @synthesize navigableItems=_navigableItems;
- (id)newBasicContainerFileRefCell;
- (id)plainObjectCell;
- (id)reviewFilesNavigator:(id)arg1 documentLocationForNavigableItem:(id)arg2;
- (id)reviewFilesNavigator:(id)arg1 importantFilePathsForNavigableItem:(id)arg2 excludingDisabledItems:(id)arg3;
- (id)reviewFilesNavigator:(id)arg1 outlineView:(id)arg2 dataCellForNavigableItem:(id)arg3;
- (void)reviewFilesNavigator:(id)arg1 outlineView:(id)arg2 willDisplayCell:(id)arg3 forNavigableItem:(id)arg4;
@property(copy) NSString *selectedRevisionIdentifier; // @synthesize selectedRevisionIdentifier=_selectedRevisionIdentifier;
@property(copy) NSArray *statusCategoryNames; // @synthesize statusCategoryNames=_statusCategoryNames;
@property IDEWorkspace *workspace; // @synthesize workspace=_workspace;
- (id)sourceControlCategoryStatusCellsWithRepresentedObject:(id)arg1;
- (id)statusCellsForCategoryName:(id)arg1 representedObject:(id)arg2;
- (id)workingCopyTreeGroupCell;
- (id)workingCopyTreeItemCell;
@property(readonly) NSArray *workspaceNavigableItems;

@end

