/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDESourceControlReviewFilesWindowController.h>

#import "IDENavigableItemCoordinatorDelegate-Protocol.h"
#import "NSMenuDelegate-Protocol.h"

@class DVTBorderedView, DVTTextViewWithPlaceholder, IDESourceControlReviewFilesDataSource, NSButton, NSImageView, NSSplitView, NSString, NSTextField;

@interface IDESourceControlCommitWindowController : IDESourceControlReviewFilesWindowController <IDENavigableItemCoordinatorDelegate, NSMenuDelegate>
{
    NSSplitView *_splitView;
    DVTTextViewWithPlaceholder *_commitMessageTextView;
    NSButton *_commitButton;
    NSButton *_cancelButton;
    DVTBorderedView *_reviewFilesView;
    DVTBorderedView *_contentView;
    DVTBorderedView *_textViewBorderedView;
    NSImageView *_commitCountImageView;
    NSTextField *_commitCountTextField;
    NSString *_commitMessage;
    IDESourceControlReviewFilesDataSource *_workspaceDataSource;
    IDESourceControlReviewFilesDataSource *_fileSystemDataSource;
    IDESourceControlReviewFilesDataSource *_flatDataSource;
    struct dispatch_semaphore_s *_multipleFileSaveWaiter;
}

+ (id)sourceControlCommitWindowLogAspect;
- (BOOL)_checkWorkingTreeItemStatusForDefaultCheckedPath:(id)arg1;
- (BOOL)_checkWorkingTreeItemStatusForDefaultDisabledPath:(id)arg1;
- (void)_commit;
- (void)beginSheetForWindow:(id)arg1;
- (void)beginStatusUpdate;
- (void)cancel:(id)arg1;
- (void)commit:(id)arg1;
@property(copy) NSString *commitMessage; // @synthesize commitMessage=_commitMessage;
- (BOOL)commitMessageRequiredForSourceTrees:(id)arg1;
- (unsigned long long)countOfCheckedItems;
- (unsigned long long)countOfItemsThatCanBeCommitted;
- (id)defaultCheckedFilePaths;
- (id)defaultDisabledFilePaths;
- (id)fileSystemDataSource;
- (id)flatDataSource;
- (void)handleErrors:(id)arg1 forRequestsOfType:(int)arg2;
- (id)initWithWindow:(id)arg1;
- (id)navigableItem:(id)arg1 childRepresentedObjectsForArray:(id)arg2;
- (void)saveFilesAtFilePaths:(id)arg1;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2;
- (BOOL)shouldEnableCommitButton;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (BOOL)splitView:(id)arg1 shouldAdjustSizeOfSubview:(id)arg2;
- (void)windowDidLoad;
- (id)windowNibName;
- (id)workingTreeItemFilterPredicate;
- (id)workingTreeWithLocation:(id)arg1;
- (id)workspaceDataSource;
- (id)workspaceItemFilterPredicate;

@end

