/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSFileWrapper;

@interface IDESourceControlConflictMergeData : NSObject
{
    NSFileWrapper *_fileWrapper;
    BOOL _dirty;
}

@property NSFileWrapper *fileWrapper; // @synthesize fileWrapper=_fileWrapper;
@property(getter=isDirty) BOOL dirty; // @synthesize dirty=_dirty;

@end

