/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDESourceControlWorkingTreeItem.h"

@interface IDESourceControlWorkingTreeItem (IDESourceControlDocumentLocationAdditions)
- (void)_doExportFileFromOriginalDocument:(id)arg1 tmpFilePath:(id)arg2 completionBlock:(id)arg3;
- (id)exportPrivateTemporaryDocumentForBranchName:(id)arg1 revisionName:(id)arg2 usingTemplateDocument:(id)arg3 completionBlock:(id)arg4;
@end

