/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDESourceControlReviewFilesWindowController.h>

#import "IDEWorkspaceDocumentProvider-Protocol.h"

@class DVTBorderedView, DVTDiffDescriptor, IDESourceControlMergeDataSource, IDEWorkspaceDocument, NSArray, NSButton, NSPopUpButton, NSSegmentedControl;

@interface IDESourceControlMergeWindowController : IDESourceControlReviewFilesWindowController <IDEWorkspaceDocumentProvider>
{
    NSButton *_mergeButton;
    DVTBorderedView *_reviewFilesView;
    NSButton *_deleteBranchCheckbox;
    NSSegmentedControl *_perDiffSegmentedControl;
    NSPopUpButton *_mergeStrategyPullDownMenu;
    NSArray *_operationInfo;
    IDESourceControlMergeDataSource *_workspaceDataSource;
    IDESourceControlMergeDataSource *_fileSystemDataSource;
    IDESourceControlMergeDataSource *_flatDataSource;
}

+ (id)keyPathsForValuesAffectingSelectedMergeDescriptor;
- (void)_merge;
- (void)beginSheetForWindow:(id)arg1;
- (void)cancel:(id)arg1;
- (id)fileSystemDataSource;
- (id)flatDataSource;
- (void)handleErrors:(id)arg1;
- (id)initWithWindow:(id)arg1;
- (id)itemsForWorkingTree:(id)arg1;
- (void)merge:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(copy) NSArray *operationInfo; // @synthesize operationInfo=_operationInfo;
- (id)operationInfoForWorkingTree:(id)arg1;
- (void)overwriteOriginalDocumentsWithMergeDocuments;
- (void)overwriteOriginalDocumentsWithMergeDocumentsForWorkingTree:(id)arg1;
- (void)selectMergeStrategyAllDiffs:(id)arg1;
- (void)selectMergeStrategyForSelectedDiff:(id)arg1;
@property(readonly) DVTDiffDescriptor *selectedMergeDescriptor;
- (void)setupConflictResolutionSupport;
- (void)setupMergeStrategyPullDown;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2;
- (BOOL)shouldEnableMergeButton;
- (unsigned long long)totalConflictCount;
- (void)updatePerDiffSegmentedControl;
- (void)windowDidLoad;
- (id)windowNibName;
- (id)workingTreeItemFilterPredicate;
- (id)workspaceDataSource;
@property(readonly) IDEWorkspaceDocument *workspaceDocument;
- (id)workspaceItemFilterPredicate;

@end

