/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSWindowController.h"

#import "NSURLConnectionDelegate-Protocol.h"

@class IDESourceControlRepository, NSProgressIndicator, NSSecureTextField, NSTextField, NSTimer, NSURLAuthenticationChallenge;

@interface IDESourceControlSSLAuthenticationWindowController : NSWindowController <NSURLConnectionDelegate>
{
    NSTextField *messageTextField;
    NSTextField *infoTextField;
    NSTextField *usernameTextField;
    NSTextField *statusTextField;
    NSSecureTextField *passwordTextField;
    NSProgressIndicator *progressIndicator;
    IDESourceControlRepository *_repository;
    id _completionBlock;
    NSURLAuthenticationChallenge *_challenge;
    NSTimer *_autodismissTimer;
    long long _count;
    BOOL _isCheckingPassword;
    BOOL _forceLoginPromptWhenSuccess;
}

- (id)_openWindowTerminationDisablingReason;
- (void)alertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)autodismiss;
- (void)beginAutodismissCountdown;
- (void)cancel:(id)arg1;
@property(copy) id completionBlock; // @synthesize completionBlock=_completionBlock;
- (BOOL)connection:(id)arg1 canAuthenticateAgainstProtectionSpace:(id)arg2;
- (void)connection:(id)arg1 didCancelAuthenticationChallenge:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (BOOL)connectionShouldUseCredentialStorage:(id)arg1;
- (void)dontAsk:(id)arg1;
- (void)finishAuthenticationSetup;
@property BOOL isCheckingPassword; // @synthesize isCheckingPassword=_isCheckingPassword;
- (void)ok:(id)arg1;
- (void)presentAuthenticationWindowForRepository:(id)arg1 forceLoginPromptWhenSuccess:(BOOL)arg2;
- (void)presentWindow;
- (BOOL)showCertificatePanelForError:(id)arg1;
- (void)testCredentialsWithCompletionBlock;
- (id)windowNibName;
- (void)windowWillClose:(id)arg1;

@end

