/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEBreakpointAction.h"

#import "NSSoundDelegate-Protocol.h"

@class NSString;

@interface IDESoundBreakpointAction : IDEBreakpointAction <NSSoundDelegate>
{
    NSString *_soundName;
}

+ (void)aquireSoundLock;
+ (id)propertiesAffectingPersistenceState;
+ (void)releaseSoundLock;
+ (id)soundNames;
- (void)_soundActionCommonInit;
- (void)dvt_encodeAttributesWithXMLArchiver:(id)arg1;
- (id)init;
- (id)initFromXMLUnarchiver:(id)arg1 archiveVersion:(float)arg2;
- (void)performActionUsingConsole:(id)arg1 andBreakpoint:(id)arg2;
@property(copy) NSString *soundName; // @synthesize soundName=_soundName;
- (void)sound:(id)arg1 didFinishPlaying:(BOOL)arg2;

@end

