/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTViewController.h"

#import "IDECompletionDestinationDelegate-Protocol.h"

@class IDECompletionDestinationManager, IDEGroup, IDESaveDestinationContext, NSPopUpButton, NSView;

@interface IDESaveDestinationController : DVTViewController <IDECompletionDestinationDelegate>
{
    NSPopUpButton *_destinationPopUp;
    NSPopUpButton *_formatPopUp;
    NSView *_formatView;
    IDESaveDestinationContext *_context;
    id _completionBlock;
    IDECompletionDestinationManager *_destinationManager;
    IDEGroup *_initialDestinationGroup;
}

+ (Class)assistantClassForContext:(id)arg1;
+ (id)assistantForContext:(id)arg1;
- (void)begin;
- (void)changeDestinationFormat:(id)arg1;
@property(copy) id completionBlock; // @synthesize completionBlock=_completionBlock;
- (id)configuredSavePanel;
@property IDESaveDestinationContext *context; // @synthesize context=_context;
- (BOOL)destinationManager:(id)arg1 shouldAddItemToMenu:(id)arg2;
- (void)destinationManagerGroupDidChange:(id)arg1;
@property NSPopUpButton *destinationPopUp; // @synthesize destinationPopUp=_destinationPopUp;
- (void)didFinishSaveSuccessfully:(BOOL)arg1;
@property NSPopUpButton *formatPopUp; // @synthesize formatPopUp=_formatPopUp;
@property NSView *formatView; // @synthesize formatView=_formatView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)save;

@end

