/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEKeyDrivenNavigableItem.h>

@interface IDESourceControlRepositoryNavigableItem : IDEKeyDrivenNavigableItem
{
}

+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingProgress;
+ (id)keyPathsForValuesAffectingReachable;
+ (id)keyPathsForValuesAffectingReachableImage;
+ (id)keyPathsForValuesAffectingURLString;
- (id)URLString;
- (void)invalidateChildItems;
- (id)name;
- (id)progress;
- (long long)reachable;
- (id)reachableImage;

@end

