/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDESourceControlWorkingTreeItem.h"

@class DVTDocumentLocation, DVTFileDataType, NSImage, NSNumber, NSString;

@interface IDESourceControlWorkingTreeItem (IDESourceControlTreeItemPropertyAdditions)
+ (id)keyPathsForValuesAffectingNavigableItem_name;
+ (id)keyPathsForValuesAffectingNavigableItem_sourceControlLocalStatus;
+ (id)keyPathsForValuesAffectingNavigableItem_sourceControlServerStatus;
+ (id)keyPathsForValuesAffectingProgress;
@property(readonly) unsigned long long navigableItem_conflictStateForUpdateOrMerge;
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) DVTFileDataType *navigableItem_documentType;
@property(readonly) NSImage *navigableItem_image;
@property(readonly) NSString *navigableItem_name;
@property(readonly) NSString *navigableItem_sourceControlLocalStatus;
@property(readonly) NSString *navigableItem_sourceControlServerStatus;
@property(readonly) NSNumber *progress;
@end

