/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDESourceControlRepositoryCreationStep.h>

#import "DVTReplacementViewDelegate-Protocol.h"

@class NSView;

@interface IDESourceControlNameTypeStepViewController : IDESourceControlRepositoryCreationStep <DVTReplacementViewDelegate>
{
    NSView *_nextKeyView;
}

+ (id)defaultViewNibName;
+ (id)keyPathsForValuesAffectingCanGoForward;
- (BOOL)canFinish;
- (BOOL)canGoBack;
- (BOOL)canGoForward;
- (id)extensions;
- (BOOL)hidePreviousButton;
- (id)identifier;
- (id)nextStepIdentifier;
- (void)replacementView:(id)arg1 didInstallViewController:(id)arg2;
- (void)replacementView:(id)arg1 willCloseViewController:(id)arg2;
- (void)replacementView:(id)arg1 willInstallViewController:(id)arg2;
- (void)viewDidInstall;

@end

