/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary, NSString;

@interface IDESpecialPasteboardHandler : NSObject
{
    NSString *_outputPasteboardType;
    NSDictionary *_context;
}

@property(readonly) NSDictionary *context; // @synthesize context=_context;
- (id)init;
- (id)initWithOutputPasteboardType:(id)arg1 context:(id)arg2;
@property(readonly) NSString *outputPasteboardType; // @synthesize outputPasteboardType=_outputPasteboardType;
- (id)specialPasteMenuItemTitleFromPasteboard:(id)arg1;
- (id)specialPasteboardDataFromPasteboard:(id)arg1 error:(id *)arg2;

@end

