/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEKeyDrivenNavigableItem.h>

@class NSMutableArray;

@interface IDESourceControlWorkingTreeNavigableItem : IDEKeyDrivenNavigableItem
{
    NSMutableArray *_computedChildItems;
}

+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingProgress;
+ (id)keyPathsForValuesAffectingReachable;
- (id)childRepresentedObjects;
- (void)idesc_setChildRepresentedObjects:(id)arg1;
- (BOOL)isLeaf;
- (id)name;
- (id)progress;
- (long long)reachable;

@end

