/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDESourceControlMultiChooserItem.h>

@class IDESourceControlBranch;

@interface IDESourceControlBranchChooserItem : IDESourceControlMultiChooserItem
{
    IDESourceControlBranch *_selectedBranch;
}

- (void)fetchBranchesWithCompletionBlock:(id)arg1;
@property IDESourceControlBranch *selectedBranch; // @synthesize selectedBranch=_selectedBranch;
- (void)setSelectedItem:(id)arg1;

@end

