/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface IDEStringWrapper : NSObject
{
    NSString *_value;
}

- (void)dvt_encodeAttributesWithXMLArchiver:(id)arg1;
- (id)initWithString:(id)arg1;
@property(copy) NSString *value; // @synthesize value=_value;

@end

