/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDESourceControlRepositoryCreationStep.h>

@class NSString, NSTextField;

@interface IDESourceControlURLValidationStep : IDESourceControlRepositoryCreationStep
{
    NSTextField *_locationTextField;
    NSString *_tempLocation;
}

+ (id)keyPathsForValuesAffectingLocation;
+ (id)keyPathsForValuesAffectingReachableImage;
+ (id)keyPathsForValuesAffectingValidatingText;
- (void)_setLocation:(id)arg1;
- (void)commitInformation;
@property(copy) NSString *location;
- (id)reachableImage;
- (void)setLocation:(id)arg1 afterDelay:(double)arg2;
- (id)validatingText;
- (void)viewWillInstall;
- (void)viewWillUninstall;

@end

