/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDESourceControlRepository.h"

@interface IDESourceControlRepository (UILevelActions)
+ (id)keyPathsForValuesAffectingReachableImage;
- (void)newBranchWithName:(id)arg1 source:(id)arg2 message:(id)arg3 autoSwitchToBranch:(BOOL)arg4 attachingToWindow:(id)arg5;
- (void)newRemoteWithName:(id)arg1 location:(id)arg2 attachingToWindow:(id)arg3 withCompletionBlock:(id)arg4;
- (id)reachableImage;
- (void)removeRemoteWithName:(id)arg1 attachingToWindow:(id)arg2;
- (BOOL)trackRemoteBranch:(id)arg1 withLocalBranchName:(id)arg2 autoSwitchToBranch:(BOOL)arg3 attachingToWindow:(id)arg4;
@end

