/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol IDESourceControlLogControllerDelegate <NSObject>
- (void)sourceControlLogViewController:(id)arg1 changeToRevision:(id)arg2;
- (void)sourceControlLogViewController:(id)arg1 compareRevisionToPreviousRevision:(id)arg2;
- (void)sourceControlLogViewController:(id)arg1 compareToRevision:(id)arg2;
- (void)sourceControlLogViewController:(id)arg1 diffWithRevision:(id)arg2;
@end

