/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDESourceControlWorkingTreeItem.h"

@interface IDESourceControlWorkingTreeItem (IDEBinaryConflictResolution)
- (id)exportTemporaryItemPreservingSCMInformationWithBranchName:(id)arg1 revisionIdentifier:(id)arg2 completionBlock:(id)arg3;
@end

