/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTFilePath, NSDate, NSString;

@interface IDESnapshotProjectItem : NSObject
{
    DVTFilePath *_projectLocation;
    int _projectStatus;
    NSDate *_lastOpenedDate;
    NSString *_projectTypeString;
    BOOL _isCurrentlyOpen;
    DVTFilePath *_workspaceArenaLocation;
    DVTFilePath *_snapshotsLocation;
}

+ (id)keyPathsForValueAffectingDetailedStatusString;
+ (id)keyPathsForValueAffectingLastOpenedDate;
+ (id)keyPathsForValueAffectingProjectStatus;
+ (id)keyPathsForValueAffectingStatusString;
- (id)description;
- (id)detailedStatusString;
- (unsigned long long)hash;
@property BOOL isCurrentlyOpen; // @synthesize isCurrentlyOpen=_isCurrentlyOpen;
- (BOOL)isEqual:(id)arg1;
@property(readonly) NSDate *lastOpenedDate; // @synthesize lastOpenedDate=_lastOpenedDate;
- (id)navigableItem_image;
- (id)navigableItem_name;
@property DVTFilePath *projectLocation; // @synthesize projectLocation=_projectLocation;
@property int projectStatus; // @synthesize projectStatus=_projectStatus;
@property(readonly) NSString *projectTypeString; // @synthesize projectTypeString=_projectTypeString;
@property DVTFilePath *snapshotsLocation; // @synthesize snapshotsLocation=_snapshotsLocation;
@property DVTFilePath *workspaceArenaLocation; // @synthesize workspaceArenaLocation=_workspaceArenaLocation;
- (id)statusString;

@end

