/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDESourceControlRevision.h"

@class NSString;

@interface IDESourceControlRevision (IDESourceControlRevisionPropertySupport)
+ (id)keyPathsForValuesAffectingNavigableItem_name;
- (id)navigableItem_image;
@property(readonly) NSString *navigableItem_name;
@end

