/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTGradientImageButton.h"

#import "DVTInvalidation-Protocol.h"

@class DVTStackBacktrace, NSImage;

@interface IDEStepGradientImageButton : DVTGradientImageButton <DVTInvalidation>
{
    id _optionMonitor;
    DVTStackBacktrace *_invalidationBacktrace;
    BOOL _onlyAllowAllStepByInstructionBehavior;
    NSImage *_stepImage;
    NSImage *_stepSuspendingOtherThreadsImage;
    NSImage *_stepByInstructionImage;
    SEL _stepAction;
    SEL _stepSuspendingOtherThreadsAction;
    SEL _stepByInstructionAction;
}

+ (BOOL)_areOnlyControlShiftKeysPressed:(id)arg1;
+ (BOOL)_isOnlyTheControlKeyPressed:(id)arg1;
- (void)_changeToStepButton;
- (void)_changeToStepByInstructionButton;
- (void)_changeToStepSuspendingOtherThreadsButton;
- (void)_handleEvent:(id)arg1;
- (void)_onlyAllowAllStepByInstructionBehavior:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)invalidate;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly, getter=isValid) BOOL valid;
@property SEL stepAction; // @synthesize stepAction=_stepAction;
@property SEL stepByInstructionAction; // @synthesize stepByInstructionAction=_stepByInstructionAction;
@property(copy) NSImage *stepByInstructionImage; // @synthesize stepByInstructionImage=_stepByInstructionImage;
@property(copy) NSImage *stepImage; // @synthesize stepImage=_stepImage;
@property SEL stepSuspendingOtherThreadsAction; // @synthesize stepSuspendingOtherThreadsAction=_stepSuspendingOtherThreadsAction;
@property(copy) NSImage *stepSuspendingOtherThreadsImage; // @synthesize stepSuspendingOtherThreadsImage=_stepSuspendingOtherThreadsImage;

@end

