/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "IDEReviewFilesViewControllerDelegate-Protocol.h"

@class DVTBorderedView, DVTFilePath, IDENavigableItemCoordinator, IDEReviewFilesViewController, IDESnapshotItem, IDESnapshotPreviewNavigatorDataSource, NSArray, NSButton, NSWindow;

@interface IDESnapshotPreviewController : IDEViewController <IDEReviewFilesViewControllerDelegate>
{
    IDESnapshotItem *_selectedSnapshot;
    IDESnapshotItem *_previousSnapshot;
    DVTFilePath *_repositoryLocation;
    NSWindow *_previewSheet;
    DVTBorderedView *_borderedView;
    NSButton *_actionButton;
    NSButton *_cancelButton;
    IDEReviewFilesViewController *_reviewFilesViewController;
    IDENavigableItemCoordinator *_coordinator;
    IDESnapshotPreviewNavigatorDataSource *_navigatorDataSource;
    NSArray *_modifiedFiles;
    id <DVTObservingToken> _comparisonEditorObservingToken;
    id _previewRestoreCompletionBlock;
    BOOL _showProgress;
}

+ (id)defaultViewNibName;
+ (void)runPreviewSheetForWindow:(id)arg1 comparingSnapshot:(id)arg2 againstSnapshot:(id)arg3 snapshotsLocation:(id)arg4;
- (void)_changeActionAndCancelButtonEnabledStateTo:(BOOL)arg1;
- (id)_configureDataSources;
- (void)_runOpenSavePanelForWindow:(id)arg1;
- (void)_runPreviewSheetForWindow:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)cancelRestoreAction:(id)arg1;
- (id)checkedFilePaths;
- (void)exportAction:(id)arg1;
- (void)exportConfirmationAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)invalidate;
@property(copy) NSArray *modifiedFiles; // @synthesize modifiedFiles=_modifiedFiles;
- (void)previewSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)previewSheetForRestoreDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
@property IDESnapshotItem *previousSnapshot; // @synthesize previousSnapshot=_previousSnapshot;
@property DVTFilePath *repositoryLocation; // @synthesize repositoryLocation=_repositoryLocation;
- (void)restoreAction:(id)arg1;
- (id)reviewFilesViewController;
- (void)runPreviewSheetToRestoreFiles:(id)arg1 comparePath:(id)arg2 restoreRootPath:(id)arg3 forWindow:(id)arg4 sheetDelegate:(id)arg5 completionBlock:(id)arg6;
@property IDESnapshotItem *selectedSnapshot; // @synthesize selectedSnapshot=_selectedSnapshot;
- (void)setInitialSelectionForNavigatorOutlineView:(id)arg1;
- (void)setPreviewToRestoreFiles:(id)arg1 comparePath:(id)arg2 restoreRootPath:(id)arg3;
@property BOOL showProgress; // @synthesize showProgress=_showProgress;
- (void)setWindowSizeWithHostWindow:(id)arg1;
- (id)uncheckedFilePaths;
- (void)willOpenDocumentLocation:(id)arg1 completionBlock:(id)arg2;

@end

