/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDESourceControlReviewFilesWindowController.h>

@class DVTBorderedView, DVTDiffDescriptor, IDESourceControlUpdateDataSource, NSArray, NSButton, NSPopUpButton, NSSegmentedControl;

@interface IDESourceControlUpdateWindowController : IDESourceControlReviewFilesWindowController
{
    NSButton *_updateButton;
    NSButton *_cancelButton;
    DVTBorderedView *_reviewFilesView;
    NSSegmentedControl *_perDiffSegmentedControl;
    NSPopUpButton *_mergeStrategyPullDownMenu;
    NSArray *_operationInfo;
    IDESourceControlUpdateDataSource *_workspaceDataSource;
    IDESourceControlUpdateDataSource *_fileSystemDataSource;
    IDESourceControlUpdateDataSource *_flatDataSource;
}

+ (id)keyPathsForValuesAffectingSelectedMergeDescriptor;
- (void)_update;
- (void)beginSheetForWindow:(id)arg1;
- (void)cancel:(id)arg1;
- (id)defaultCheckedFilePaths;
- (id)defaultDisabledFilePaths;
- (id)fileSystemDataSource;
- (id)flatDataSource;
- (void)handleErrors:(id)arg1;
- (id)initWithWindow:(id)arg1;
- (id)itemsForWorkingTree:(id)arg1;
@property(copy) NSArray *operationInfo; // @synthesize operationInfo=_operationInfo;
- (id)operationInfoForWorkingTree:(id)arg1;
- (void)overwriteOriginalDocumentsWithMergeDocuments;
- (void)overwriteOriginalDocumentsWithMergeDocumentsForWorkingTree:(id)arg1;
- (void)selectMergeStrategyAllDiffs:(id)arg1;
- (void)selectMergeStrategyForSelectedDiff:(id)arg1;
@property(readonly) DVTDiffDescriptor *selectedMergeDescriptor;
- (void)setupConflictResolutionSupport;
- (void)setupMergeStrategyPullDown;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2;
- (int)statusForWorkingTreeItem:(id)arg1;
- (unsigned long long)totalConflictCount;
- (void)update:(id)arg1;
- (void)updateButtonTitle;
- (void)updatePerDiffSegmentedControl;
- (void)windowDidLoad;
- (id)windowNibName;
- (id)workingTreeItemFilterPredicate;
- (id)workspaceDataSource;
- (id)workspaceItemFilterPredicate;

@end

