/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation-Protocol.h"

@class DVTOperation, DVTStackBacktrace, IDESourceControlOperationInfo, IDESourceControlRequest, NSError, NSMenu, NSMenuItem;

@interface IDESourceControlMultiChooserItem : NSObject <DVTInvalidation>
{
    IDESourceControlRequest *_currentRequest;
    DVTOperation *_currentOperation;
    IDESourceControlOperationInfo *_info;
    int _requestType;
    NSMenu *_menu;
    NSMenuItem *_selectedItem;
    NSError *_error;
    BOOL _selected;
    BOOL _enabled;
    BOOL _isInvalidated;
    DVTStackBacktrace *_invalidationBacktrace;
}

@property BOOL enabled; // @synthesize enabled=_enabled;
@property(copy) NSError *error; // @synthesize error=_error;
- (id)initWithOperationInfo:(id)arg1;
- (void)invalidate;
@property(readonly) DVTStackBacktrace *invalidationBacktrace; // @synthesize invalidationBacktrace=_invalidationBacktrace;
@property(readonly, getter=isValid) BOOL valid;
@property(copy) NSMenu *menu; // @synthesize menu=_menu;
@property(readonly) IDESourceControlOperationInfo *operationInfo; // @synthesize operationInfo=_info;
@property int requestType; // @synthesize requestType=_requestType;
@property BOOL selected; // @synthesize selected=_selected;
@property NSMenuItem *selectedItem; // @synthesize selectedItem=_selectedItem;

@end

