/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEAlertViewController.h>

@class NSMutableArray, NSPopUpButton, NSSound;

@interface IDESoundAlertViewController : IDEAlertViewController
{
    NSPopUpButton *_soundPopUpButton;
    NSMutableArray *_recentSounds;
    NSSound *_playingSound;
}

- (void)addPathToRecentSounds:(id)arg1;
- (void)awakeFromNib;
- (void)chooseSound:(id)arg1;
- (void)populatePopUpButton;
- (void)selectSound:(id)arg1;
- (void)setAlert:(id)arg1;
@property(retain) NSPopUpButton *soundPopUpButton; // @synthesize soundPopUpButton=_soundPopUpButton;

@end

