/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDESourceControlURLValidationStep.h>

@class DVTBorderedView;

@interface IDESourceControlURLStepViewController : IDESourceControlURLValidationStep
{
    DVTBorderedView *_borderedView;
}

+ (id)defaultViewNibName;
+ (id)keyPathsForValuesAffectingCanFinish;
+ (id)keyPathsForValuesAffectingCanGoForward;
- (BOOL)canFinish;
- (BOOL)canGoBack;
- (BOOL)canGoForward;
- (id)extensions;
- (id)identifier;
- (id)nextStepIdentifier;
- (void)viewDidInstall;

@end

