/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDESourceControlTreeGroup.h"

@class NSImage, NSNumber, NSString;

@interface IDESourceControlTreeGroup (IDESourceControlTreeGroupPropertyAdditions)
+ (id)keyPathsForValuesAffectingNavigableItem_name;
+ (id)keyPathsForValuesAffectingProgress;
@property(readonly) NSImage *navigableItem_image;
- (BOOL)navigableItem_isMajorGroup;
@property(readonly) NSString *navigableItem_name;
@property(readonly) NSNumber *progress;
@end

