/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IDESourceControlRepository, NSError, NSString, NSURL;

@interface IDESourceControlRepositoryCreationContext : NSObject
{
    IDESourceControlRepository *_sourceTree;
    IDESourceControlRepository *_foundRepository;
    NSString *_wcName;
    NSURL *_workspaceURL;
    NSURL *_projectURL;
    NSError *_error;
    BOOL _defaultTrunkExists;
    BOOL _defaultBranchesExists;
    BOOL _defaultTagsExists;
}

@property BOOL defaultBranchesExists; // @synthesize defaultBranchesExists=_defaultBranchesExists;
@property BOOL defaultTagsExists; // @synthesize defaultTagsExists=_defaultTagsExists;
@property BOOL defaultTrunkExists; // @synthesize defaultTrunkExists=_defaultTrunkExists;
@property NSError *error; // @synthesize error=_error;
@property IDESourceControlRepository *foundRepository; // @synthesize foundRepository=_foundRepository;
- (id)init;
@property(copy) NSURL *projectURL; // @synthesize projectURL=_projectURL;
@property IDESourceControlRepository *sourceTree; // @synthesize sourceTree=_sourceTree;
@property(copy) NSString *wcName; // @synthesize wcName=_wcName;
@property(copy) NSURL *workspaceURL; // @synthesize workspaceURL=_workspaceURL;

@end

