/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSWindowController.h"

#import "IDENavigableItemCoordinatorDelegate-Protocol.h"
#import "NSMenuDelegate-Protocol.h"

@class IDENavigableItemCoordinator, IDEReviewFilesViewController, IDESourceControlRequest, IDEWorkspace, NSArray, NSMutableArray, NSWindow;

@interface IDESourceControlReviewFilesWindowController : NSWindowController <IDENavigableItemCoordinatorDelegate, NSMenuDelegate>
{
    IDEReviewFilesViewController *_reviewFilesViewController;
    IDEWorkspace *_workspace;
    NSArray *_workingTrees;
    NSArray *_files;
    NSMutableArray *_workingTreeItems;
    IDESourceControlRequest *_currentRequest;
    IDENavigableItemCoordinator *_navigableItemCoordinator;
    NSWindow *_parentWindow;
    BOOL _showIgnoredFiles;
}

+ (id)containerFileTypesBlacklistedFromOutlineViewCompression;
+ (id)sourceControlReviewFilesWindowControllerLogAspect;
- (void)beginReviewFiles;
- (void)beginSheetForWindow:(id)arg1;
- (void)checkAll:(id)arg1;
@property IDESourceControlRequest *currentRequest; // @synthesize currentRequest=_currentRequest;
- (id)defaultCheckedFilePaths;
- (id)defaultDisabledFilePaths;
- (void)displayError:(id)arg1;
- (void)endSheet;
- (void)endSheetWithReturnCode:(long long)arg1;
- (id)fileSystemDataSource;
@property(copy) NSArray *files; // @synthesize files=_files;
- (id)filesPathsOfContextualMenuSelectedItems;
- (id)flatDataSource;
- (id)flatNavigableItems;
- (void)ignoreFile:(id)arg1;
- (void)initDataSources;
- (id)initWithWindow:(id)arg1;
- (id)itemsForWorkingTree:(id)arg1;
@property(readonly) IDENavigableItemCoordinator *navigableItemCoordinator;
- (void)reloadNavigableItemsIfNecessary;
- (void)revertChanges:(id)arg1;
- (void)revertChangesAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
@property(readonly) IDEReviewFilesViewController *reviewFilesViewController; // @synthesize reviewFilesViewController=_reviewFilesViewController;
- (id)selectedNavigableItemsofContextualMenu;
- (void)setInitialSelectionForNavigatorOutlineView:(id)arg1;
@property BOOL showIgnoredFiles; // @synthesize showIgnoredFiles=_showIgnoredFiles;
- (void)setWindowSize;
@property(copy) NSArray *workingTreeItems; // @synthesize workingTreeItems=_workingTreeItems;
@property(copy) NSArray *workingTrees; // @synthesize workingTrees=_workingTrees;
@property IDEWorkspace *workspace; // @synthesize workspace=_workspace;
- (void)setupContextMenu;
- (void)setupNavigableItemsForFileSystemDataSource;
- (void)setupNavigableItemsForFlatDataSource;
- (void)setupNavigableItemsForWorkspaceDataSource;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)toggleIgnoredFiles:(id)arg1;
- (void)uncheckAll:(id)arg1;
- (void)unignoreFile:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (id)windowNibName;
- (id)workingTreeItemFilterPredicate;
- (id)workingTreeNavigableItems;
- (id)workspaceDataSource;
- (id)workspaceItemFilterPredicate;
- (id)workspaceNavigableItems;

@end

