/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDESourceControlCheckoutStepViewController.h>

@class DVTOperationGroup, NSMutableDictionary;

@interface IDESourceControlBackendSetupStepViewController : IDESourceControlCheckoutStepViewController
{
    DVTOperationGroup *_backendOperationGroup;
    NSMutableDictionary *_backendSetupData;
    BOOL _canGoForward;
}

- (BOOL)canGoBack;
@property BOOL canGoForward; // @synthesize canGoForward=_canGoForward;
- (id)checkoutString;
- (void)giveUp:(id)arg1;
- (id)identifier;
- (id)nextStepIdentifier;
- (void)performBackendSetupWithCompletionBlock:(id)arg1;
- (void)viewDidInstall;
- (void)viewWillUninstall;

@end

