/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation-Protocol.h"

@class DVTFilePath, DVTStackBacktrace;

@interface IDESourceControlConflictResolutionController : NSObject <DVTInvalidation>
{
    BOOL _isInvalidated;
    DVTStackBacktrace *_invalidationBacktrace;
    DVTFilePath *_mergeDataPath;
    BOOL _shouldDisableMergeSaving;
}

+ (int)binaryConflictMergeDirection:(id)arg1;
+ (void)copyItemAtFilePath:(id)arg1 toFilePath:(id)arg2;
+ (BOOL)isBinaryConflictResolutionMergeData:(id)arg1;
+ (id)mergeDataDictionary:(id)arg1;
+ (void)moveItemAtFilePath:(id)arg1 toFilePath:(id)arg2;
- (void)_validateMergeData:(id)arg1;
- (void)completeConflictResolution;
- (void)invalidate;
@property(readonly) DVTStackBacktrace *invalidationBacktrace; // @synthesize invalidationBacktrace=_invalidationBacktrace;
@property(readonly, getter=isValid) BOOL valid;
- (id)mergeDataForTreeItem:(id)arg1;
@property(readonly) DVTFilePath *mergeDataPath;
- (id)pathToFileWrapper:(id)arg1 inMergeData:(id)arg2;
- (void)removeMergeDataForTreeItem:(id)arg1;
- (void)setMergeData:(id)arg1 forTreeItem:(id)arg2;
@property BOOL shouldDisableMergeSaving; // @synthesize shouldDisableMergeSaving=_shouldDisableMergeSaving;

@end

