/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSWindowController.h"

@class IDEWorkspace, NSArray, NSButton, NSImage, NSImageView, NSMutableDictionary, NSOperationQueue, NSProgressIndicator, NSString, NSTableView, NSTextField, NSWindow;

@interface IDESourceControlMultiChooserWindowController : NSWindowController
{
    NSTableView *_tableView;
    NSButton *_chooseButton;
    NSTextField *_messageTextField;
    NSTextField *_infoTextField;
    NSTextField *_progressField;
    NSImageView *_errorImageView;
    NSProgressIndicator *_progressIndicator;
    IDEWorkspace *_workspace;
    NSArray *_workingTrees;
    NSArray *_workingTreeItems;
    NSArray *_items;
    NSOperationQueue *_operationQueue;
    id _continuationBlock;
    int _requestType;
    NSMutableDictionary *_tokenDictionary;
    NSMutableDictionary *_dataCellDictionary;
    NSString *_messageText;
    NSString *_infoText;
    NSWindow *_parentWindow;
    NSImage *_successImage;
    NSImage *_errorImage;
    BOOL _inProgress;
    BOOL _canContinue;
    BOOL _willDismiss;
}

+ (id)keyPathsForValuesAffectingCanContinue;
- (id)_operationalItemsForWorkingTree:(id)arg1;
- (void)beginSheetForWindow:(id)arg1;
@property BOOL canContinue; // @synthesize canContinue=_canContinue;
- (void)cancel:(id)arg1;
- (void)cancelSheet;
- (void)choose:(id)arg1;
@property(copy) id continuationBlock; // @synthesize continuationBlock=_continuationBlock;
- (void)displayError:(id)arg1;
- (void)displayErrorAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)displayErrorAndCancel:(id)arg1;
- (void)endSheet;
@property BOOL inProgress; // @synthesize inProgress=_inProgress;
@property(copy) NSString *infoText; // @synthesize infoText=_infoText;
@property(readonly) NSArray *items; // @synthesize items=_items;
@property(copy) NSString *messageText; // @synthesize messageText=_messageText;
- (void)multiChooserSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property int requestType; // @synthesize requestType=_requestType;
- (void)selectRepository:(id)arg1;
- (id)selectedItems;
@property(copy) NSArray *workingTreeItems; // @synthesize workingTreeItems=_workingTreeItems;
@property(copy) NSArray *workingTrees; // @synthesize workingTrees=_workingTrees;
@property IDEWorkspace *workspace; // @synthesize workspace=_workspace;
- (void)setupItems;
- (void)setupPopUpMenuForItem:(id)arg1;
- (void)setupPopUpMenus;
- (void)setupText;
- (id)successImage;
- (id)tableView:(id)arg1 dataCellForTableColumn:(id)arg2 row:(long long)arg3;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (void)tableView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)tableViewSelectionDidChange:(id)arg1;
- (void)updateCanContinue;
- (BOOL)validateMenuItem:(id)arg1;
- (void)windowDidLoad;
- (id)windowNibName;
- (id)workingTreeForLocation:(id)arg1;

@end

