/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface IDETemplateOption : NSObject
{
    id <IDETemplateOptionParent> _parent;
    NSDictionary *_requiredOptions;
    NSString *_identifier;
    NSString *_name;
    NSString *_description;
    NSString *_type;
    NSString *_defaultValue;
    NSString *_emptyReplacement;
    NSString *_placeholder;
    NSString *_value;
    NSArray *_values;
    long long _sortOrder;
    BOOL _required;
    BOOL _notPersisted;
    BOOL _enabled;
}

+ (id)keyPathsForValuesAffectingBooleanValue;
+ (id)keyPathsForValuesAffectingDisplayValues;
+ (id)keyPathsForValuesAffectingHasValidValue;
- (void)addMacroToEngine:(id)arg1;
@property BOOL booleanValue;
@property(copy) NSString *defaultValue; // @synthesize defaultValue=_defaultValue;
@property(copy) NSString *description; // @synthesize description=_description;
@property(readonly) NSArray *displayValues;
@property(copy) NSString *emptyReplacement; // @synthesize emptyReplacement=_emptyReplacement;
@property BOOL enabled; // @synthesize enabled=_enabled;
@property(readonly) BOOL hasValidValue;
- (unsigned long long)hash;
@property(copy) NSString *identifier; // @synthesize identifier=_identifier;
- (id)init;
- (id)initWithOptionInfo:(id)arg1 filePath:(id)arg2;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isUsableWithOptions:(id)arg1;
@property(copy) NSString *name; // @synthesize name=_name;
@property id <IDETemplateOptionParent> parent; // @synthesize parent=_parent;
@property(copy) NSString *placeholder; // @synthesize placeholder=_placeholder;
@property(copy) NSDictionary *requiredOptions; // @synthesize requiredOptions=_requiredOptions;
@property long long sortOrder; // @synthesize sortOrder=_sortOrder;
@property(copy) NSString *type; // @synthesize type=_type;
@property(copy) NSString *value; // @synthesize value=_value;
@property(copy) NSArray *values; // @synthesize values=_values;
- (BOOL)shouldPersistValue;
- (id)staticValueWithOptions:(id)arg1;
- (id)uniqueIdentifier;
- (void)updateEnabledWithOptions:(id)arg1;
- (void)updateValueWithBuildables:(id)arg1;
- (void)updateValueWithOptions:(id)arg1;
- (BOOL)validateValue:(id *)arg1 forKey:(id)arg2 error:(id *)arg3;

@end

