/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDENavigableItemRepresentation-Protocol.h"

@class DVTDocumentLocation, DVTFileDataType, IDEFileReference, NSArray, NSImage, NSString;

@interface IDETestRunPhaseTestableProviderWrapper : NSObject <IDENavigableItemRepresentation>
{
    id <IDETestableProvider> _provider;
}

+ (id)keyPathsAffectingTestableWrappers;
- (id)initWithTestableProvider:(id)arg1;
@property(readonly) NSImage *navigableItem_image;
@property(readonly) NSString *navigableItem_name;
@property(readonly) id <IDETestableProvider> provider; // @synthesize provider=_provider;
@property(readonly) NSArray *testableWrappers;

// Remaining properties
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) DVTFileDataType *navigableItem_documentType;
@property(readonly) IDEFileReference *navigableItem_fileReference;
@property(readonly) NSString *navigableItem_groupIdentifier;
@property(readonly) BOOL navigableItem_isMajorGroup;

@end

