/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTPlatform, NSArray, NSMutableDictionary, NSString;

@interface IDETemplateSection : NSObject
{
    DVTPlatform *_platform;
    NSMutableDictionary *_templateCategoriesByName;
    NSArray *_categories;
}

+ (id)keyPathsForValuesAffectingWillChangeDeviceSoftwareVersion;
- (void)addTemplate:(id)arg1;
@property(readonly) NSArray *categories;
- (id)categoryWithName:(id)arg1;
- (id)init;
- (id)navigableItem_image;
- (BOOL)navigableItem_isMajorGroup;
- (id)navigableItem_name;
@property DVTPlatform *platform; // @synthesize platform=_platform;
@property(readonly) NSString *sectionIdentifier;
- (void)sortAllCategories;
@property(readonly) NSArray *templates;

@end

