/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEEditorDocument.h>

@interface IDETextDocumentFactoryDocument : IDEEditorDocument
{
}

+ (id)convertURLToPlainTextDataOrFile:(id)arg1 hintedFileDataType:(id *)arg2 editableFlag:(char *)arg3 error:(id *)arg4;
+ (BOOL)hasTextConversionProviderClassForDataType:(id)arg1;
+ (BOOL)isBlacklistedFile:(id)arg1;
+ (id)pathToKeyConflictResolutionFromInputFilePath:(id)arg1;
+ (Class)textConversionProviderClassForDataType:(id)arg1;
- (id)initForURL:(id)arg1 withContentsOfURL:(id)arg2 ofType:(id)arg3 error:(id *)arg4;
- (id)initWithContentsOfURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;

@end

