/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface IDETemplateFactory : NSObject
{
}

- (BOOL)_isHiddenFilePath:(id)arg1;
- (BOOL)canInstantiateTemplateForContext:(id)arg1;
- (void)instantiateTemplateForContext:(id)arg1 options:(id)arg2 whenDone:(id)arg3;
- (id)mainFileNameForContext:(id)arg1;
- (id)proposedFilePathsForContext:(id)arg1 options:(id)arg2 error:(id *)arg3;
- (BOOL)shouldProcessPath:(id)arg1 inTemplate:(id)arg2;

@end

