/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDETemplateInstantiationAssistant.h>

#import "DVTTileViewDelegate-Protocol.h"

@class DVTBorderedView, DVTImageAndTextCell, DVTSplitView, DVTTileView, DVTTileViewItem, IDENavigableItemCoordinator, IDENavigatorOutlineView, NSArrayController, NSTextField, NSView;

@interface IDETemplateChooserAssistant : IDETemplateInstantiationAssistant <DVTTileViewDelegate>
{
    DVTSplitView *_innerSplitView;
    DVTBorderedView *_templateInfoView;
    IDENavigatorOutlineView *_outlineView;
    DVTImageAndTextCell *_sectionCell;
    NSArrayController *_arrayController;
    DVTTileView *_tileView;
    DVTTileViewItem *_prototypeItem;
    NSView *_itemSelectionView;
    NSTextField *_itemTextField;
    NSView *_sourceListView;
    IDENavigableItemCoordinator *_navigableItemCoordinator;
}

+ (id)defaultViewNibBundle;
+ (id)defaultViewNibName;
+ (id)keyPathsForValuesAffectingCanGoForward;
+ (id)keyPathsForValuesAffectingCollectionViewSelectionIndexes;
+ (id)supportedTemplateKind;
- (BOOL)canGoForward;
- (id)categoryDefaultsKey;
- (void)chooserTileViewShouldGoForward:(id)arg1;
- (id)collectionViewSelectionIndexes;
- (void)loadView;
@property IDENavigableItemCoordinator *navigableItemCoordinator; // @synthesize navigableItemCoordinator=_navigableItemCoordinator;
- (id)nextAssistantIdentifier;
- (id)outlineView:(id)arg1 dataCellForTableColumn:(id)arg2 item:(id)arg3;
- (BOOL)outlineView:(id)arg1 shouldShowOutlineCellForItem:(id)arg2;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (void)restoreSelectionFromContext;
- (void)restoreSelectionFromUserDefaults;
- (id)sectionCell;
- (id)sectionDefaultsKey;
- (void)setCollectionViewSelectionIndexes:(id)arg1;
@property NSView *sourceListView; // @synthesize sourceListView=_sourceListView;
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (id)templateNameDefaultsKey;
- (void)tileView:(id)arg1 didChangeContextClickedObjectFrom:(id)arg2;
- (id)tileView:(id)arg1 titleForContentObject:(id)arg2;
- (id)tileView:(id)arg1 typeCompletionStringForContentObject:(id)arg2;
- (void)userDidPressEscapeInTileView:(id)arg1;
- (void)userDidPressSpaceBarInTileView:(id)arg1;
- (void)viewDidInstall;
- (void)viewWillUninstall;
- (void)writeStateToUserDefaults;

@end

