/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface IDETemplateMacroEngine : NSObject
{
    NSMutableDictionary *_macroSubstitutions;
}

+ (id)fullUserName;
+ (id)multiSubstitutionsForSubstitution:(id)arg1 forMacro:(id)arg2;
+ (id)standardSubstitutionsForMacrosWithWorkspaceName:(id)arg1 projectName:(id)arg2 packageName:(id)arg3 targetName:(id)arg4 productName:(id)arg5 fileName:(id)arg6 organizationName:(id)arg7;
+ (id)substitutionsForMacrosWithWorkspaceName:(id)arg1 projectName:(id)arg2 packageName:(id)arg3 targetName:(id)arg4 productName:(id)arg5 fileName:(id)arg6;
- (id)allMacros;
- (BOOL)createFileAtURL:(id)arg1 usingEncoding:(unsigned long long)arg2 substitutingMacrosInFileAtURL:(id)arg3 error:(id *)arg4;
- (id)init;
- (void)setMultiSubstitution:(id)arg1 forMacro:(id)arg2;
- (void)setSubstitution:(id)arg1 forMacro:(id)arg2;
- (void)setSubstitutionsForMacros:(id)arg1;
- (id)stringBySubstitutingMacrosInString:(id)arg1;
- (id)substitutionForMacro:(id)arg1;

@end

