/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEKeyBindingSet.h>

@interface IDETextKeyBindingSet : IDEKeyBindingSet
{
}

+ (Class)_defaultTextKeyBindingSetClass;
+ (id)_rawDefaultSystemTextBindings;
+ (id)defaultKeyBindingSet;
+ (void)initialize;
- (void)_appendDictionaryRepresentationOfTextKeyBinding:(id)arg1 appendsEmptyKeyboardShortcuts:(BOOL)arg2 toDictionary:(id)arg3;
- (void)activate;
- (id)deltaDictionary;
- (id)initWithDictionary:(id)arg1;
- (void)updateDictionary;

@end

