/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTOperation.h"

@class DVTFilePath, NSArray;

@interface IDETemplateTextSubstitutionOperation : DVTOperation
{
    NSArray *_paths;
    DVTFilePath *_primaryPath;
}

@property(copy) NSArray *paths; // @synthesize paths=_paths;
@property(copy) DVTFilePath *primaryPath; // @synthesize primaryPath=_primaryPath;

@end

