/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSSavePanel.h"

@interface IDETemplateSavePanel : NSSavePanel
{
}

- (BOOL)_overwriteExistingFileCheck:(id)arg1;
- (void)overwriteAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(id)arg3;

@end

