/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSWindowController.h"

#import "NSTableViewDataSource-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"

@class DVTTableView, IDEContainer, IDENavigableItemCoordinator, IDENavigatorDataCell, IDEWorkspace, NSButton, NSImage, NSImageCell, NSMutableArray;

@interface IDEUpgradeTaskWindowController : NSWindowController <NSTableViewDataSource, NSTableViewDelegate>
{
    DVTTableView *_upgradeTable;
    NSButton *_closeButton;
    NSButton *_upgradeButton;
    NSButton *_skipButton;
    IDENavigatorDataCell *_groupCell;
    NSImageCell *_imageCell;
    IDENavigatorDataCell *_itemCell;
    NSMutableArray *_items;
    IDEWorkspace *_workspace;
    IDEContainer *_container;
    id <IDEBlueprintProvider> _blueprintProvider;
    BOOL _displayingResults;
    NSImage *_successImage;
    NSImage *_errorImage;
    IDENavigableItemCoordinator *_navigableItemCoordinator;
    id _completionBlock;
}

+ (id)_blueprintContextForExtension:(id)arg1 blueprint:(id)arg2;
+ (id)_containerContextForExtension:(id)arg1 container:(id)arg2;
+ (id)_nilUpgradeTask;
+ (id)_upgradeTasksProviderExtensionForContainer:(id)arg1;
- (BOOL)_canSelectTaskForRow:(long long)arg1;
- (void)_endSheetWithReturnCode:(id)arg1;
- (BOOL)_loadAllUpgradeTasks;
- (id)_navigableItemForNilUpgradeTask;
- (void)_sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)beginSheetForWindow:(id)arg1 completionBlock:(id)arg2;
- (void)cancelAction:(id)arg1;
@property(readonly) BOOL displayingResults; // @synthesize displayingResults=_displayingResults;
- (id)initWithWorkspace:(id)arg1 container:(id)arg2 blueprintProvider:(id)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)performChanges:(id)arg1;
- (void)skipChanges:(id)arg1;
- (id)tableView:(id)arg1 dataCellForTableColumn:(id)arg2 row:(long long)arg3;
- (BOOL)tableView:(id)arg1 isGroupRow:(long long)arg2;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (void)tableView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (BOOL)tableView:(id)arg1 shouldShowCellExpansionForTableColumn:(id)arg2 row:(long long)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)windowDidLoad;

@end

