/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "IDENavigableItemCoordinatorDelegate-Protocol.h"

@class DVTBorderedView, DVTChoice, DVTChooserView, DVTDelayedValidator, DVTDisclosureView, DVTExtension, DVTMutableOrderedSet, DVTStackView, IDEEditorDocument, IDENavigableItemCoordinator, IDESelection, IDEUtilityPlaceholderView, NSArray, NSMapTable, NSMutableSet, NSScrollView, NSSet;

@interface IDEUtilityArea : IDEViewController <IDENavigableItemCoordinatorDelegate>
{
    DVTChooserView *_chooserView;
    DVTBorderedView *_borderedView;
    DVTStackView *_stackView;
    NSScrollView *_scrollView;
    DVTDisclosureView *_lastDisclosureView;
    DVTChoice *_selectedCategoryChoice;
    NSMapTable *_categoriesToChoices;
    NSMapTable *_sliceExtensionsToReplacementViews;
    NSMapTable *_sliceExtensionsToWrappingViews;
    NSMapTable *_installedSliceExtensionsToReplacementViews;
    NSMutableSet *_invalidReplacementViewExtensions;
    NSArray *_builtinCategories;
    DVTMutableOrderedSet *_userPreferredCategories;
    NSSet *_displayedSliceViewControllers;
    DVTDelayedValidator *_validator;
    DVTExtension *_displayedCategory;
    IDESelection *_content;
    id <DVTObservingToken> _installToken;
    id <DVTObservingToken> _forgotItemsNotificationToken;
    NSArray *_contentNavigableItems;
    NSSet *_documentsObservedForClosing;
    IDENavigableItemCoordinator *_navigableItemCoordinator;
    IDEUtilityPlaceholderView *_placeholderView;
    IDEEditorDocument *_retainedDocument;
    id _retainedDocumentWillCloseNotificationToken;
    BOOL _forceInputSelectionToEmpty;
}

+ (id)defaultViewNibName;
+ (id)emptySelectionPlaceholder;
+ (id)notApplicablePlaceholder;
+ (id)utilityConfiguredDisclosureView;
- (id)_cachedReplacementViewForSliceExtension:(id)arg1 inCategory:(id)arg2;
- (id)_cachedSliceViewForSliceExtension:(id)arg1 inCategory:(id)arg2;
- (id)_categoriesForCategoryIdentifiers:(id)arg1;
- (id)_categoriesForNavigables:(id)arg1;
- (id)_categoryForCategoryIdentifier:(id)arg1;
- (id)_choiceForCategory:(id)arg1;
- (id)_choicesForCategories:(id)arg1;
- (id)_currentlyInstalledReplacementViewForSliceExtension:(id)arg1;
- (id)_disclosureViewForWrappingReplacementView:(id)arg1 fromSliceExtension:(id)arg2;
- (id)_editorContributedCategoryExtensionsForNavigable:(id)arg1;
- (void)_inputEditorDocumentWillClose:(id)arg1;
- (void)_navigableItemCoordinatorDidForgetItems:(id)arg1;
- (id)_preferredChoiceForChoices:(id)arg1;
- (void)_rebuildCategoriesAndStack;
- (void)_rebuildStackWithNavigableItems:(id)arg1;
- (void)_setDocumentsObservedForClosing:(id)arg1;
- (id)_sliceViewsForSliceExtensions:(id)arg1 inCategory:(id)arg2;
- (void)_stackClippingViewFrameChanged:(id)arg1;
- (void)_updateLastDisclosureViewBorderColor;
- (void)bindReplacementView:(id)arg1 forSliceExtension:(id)arg2 inCategory:(id)arg3;
@property(readonly) DVTBorderedView *borderedView; // @synthesize borderedView=_borderedView;
@property(copy) NSArray *builtinCategories; // @synthesize builtinCategories=_builtinCategories;
- (id)categoryIdentifiersForEditorExtension:(id)arg1;
- (BOOL)categorySupportsMultipleSlices:(id)arg1;
- (id)choiceMatchingExtensionIdentifier:(id)arg1;
@property(readonly) DVTChooserView *chooserView; // @synthesize chooserView=_chooserView;
- (void)chooserView:(id)arg1 userDidSelectChoices:(id)arg2;
- (BOOL)commitEditingForAction:(int)arg1 errors:(id)arg2;
@property(readonly) IDESelection *content;
@property(copy) NSArray *contentNavigableItems; // @synthesize contentNavigableItems=_contentNavigableItems;
- (id)defaultChoice;
- (void)discardEditing;
@property(readonly) NSSet *displayedSliceViewControllers; // @synthesize displayedSliceViewControllers=_displayedSliceViewControllers;
- (void)dropCachedViewsForExtension:(id)arg1;
- (void)dropRetainedDocument;
- (id)imageForCategoryExtension:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)invalidate;
- (void)invalidateStack;
- (void)loadView;
- (id)navigableItemCoordinator:(id)arg1 editorDocumentForNavigableItem:(id)arg2;
- (id)navigableItemsForInputNavigableItems:(id)arg1 inCategory:(id)arg2;
- (void)noteUserDidExplicitlyChooseChoice:(id)arg1;
- (id)placeholderStringForInputNavigableItems:(id)arg1 derivedItems:(id)arg2 inCategory:(id)arg3;
- (id)preferredCategoriesPersistenceKey;
- (id)selectedCategory;
@property(readonly) DVTChoice *selectedCategoryChoice;
- (id)selectedCategoryChoices;
- (void)setContent:(id)arg1;
- (void)setRepresentedObject:(id)arg1;
- (void)setSelectedCategoryChoices:(id)arg1;
- (id)sliceExtensionsForNavigableItems:(id)arg1 inCategory:(id)arg2 withWorkspaceDocument:(id)arg3;
@property(readonly) DVTStackView *stackView; // @synthesize stackView=_stackView;
- (id)titleForCategoryExtension:(id)arg1;
- (id)titleForSliceExtension:(id)arg1;
- (id)titleKeyPathForSliceExtension:(id)arg1;
- (id)toolTipForCategoryExtension:(id)arg1;
- (void)unbindReplacementView:(id)arg1 forSliceExtension:(id)arg2 inCategory:(id)arg3;
- (void)userSelectedCategoryChoiceFromMenu:(id)arg1;
- (void)validateIfNeeded;
- (id)viewControllerForExtension:(id)arg1;
- (void)viewDidInstall;
- (void)viewWillUninstall;
- (id)willReplaceSliceViewControllers:(SEL)arg1;
- (void)workspaceWindowIsClosing;

@end

