/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface IDEUtilitiesMenuDelegate : NSObject
{
}

+ (void)_addMenuItemsForUtilityArea:(id)arg1 toUtilityMenu:(id)arg2 withKeyBindingSet:(id)arg3;
+ (id)_inspectorCategoryExtensions;
+ (id)_libraryCategoryExtensions;
+ (id)defaultMenuKeyBindingsForGroup:(id)arg1;
+ (void)updateUtilitiesMenu:(id)arg1 withMenuItemsForInspectorArea:(id)arg2 andLibraryArea:(id)arg3;

@end

