/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTImageAndTextCell.h"

@class NSString, NSTextStorage;

@interface IDEVariablesViewSingleColumnCell : DVTImageAndTextCell
{
    NSTextStorage *_textStorage;
    NSString *_filterMatchString;
    BOOL _settingUpFieldEditor;
    BOOL _showsType;
    BOOL _showsFormattedSummary;
}

+ (id)keyPathsForValuesAffectingDataValue;
+ (id)keyPathsForValuesAffectingSummaryValue;
- (id)_attributedString:(id)arg1 withFont:(id)arg2 color:(id)arg3 changed:(BOOL)arg4 partName:(id)arg5;
- (void)_highlightMatchOfString:(id)arg1 onAttributedString:(id)arg2;
- (void)_recalculateAttributedStringValue;
- (struct CGRect)_rectForValueInFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)_setupCells;
- (id)attributedStringValue;
- (id)calculateFullAttributedString;
- (id)calculateNameString;
- (id)calculateSummaryAttributedString;
- (id)changedAttributes;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly) id <IDEDataValue> dataValue;
- (void)editWithFrame:(struct CGRect)arg1 inView:(id)arg2 editor:(id)arg3 delegate:(id)arg4 event:(id)arg5;
@property(copy) NSString *filterMatchString; // @synthesize filterMatchString=_filterMatchString;
- (id)init;
- (id)initImageCell:(id)arg1;
- (id)initTextCell:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)selectWithFrame:(struct CGRect)arg1 inView:(id)arg2 editor:(id)arg3 delegate:(id)arg4 start:(long long)arg5 length:(long long)arg6;
- (void)setRepresentedObject:(id)arg1;
@property BOOL showsFormattedSummary; // @synthesize showsFormattedSummary=_showsFormattedSummary;
@property BOOL showsType; // @synthesize showsType=_showsType;
- (id)summaryTextColor;
- (id)textColor;
- (id)typeString;
- (id)valueString;

@end

