/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol IDEVersionedFileManagerDelegate
- (BOOL)canMoveItemsAtFilePaths:(id)arg1 toFilePaths:(id)arg2 completionBlockDispatchQueue:(struct dispatch_queue_s **)arg3 completionBlock:(id *)arg4;
- (BOOL)canRemoveItemsAtFilePaths:(id)arg1 completionBlockDispatchQueue:(struct dispatch_queue_s **)arg2 completionBlock:(id *)arg3;
- (void)willRemoveItemsAtFilePaths:(id)arg1;
@end

