/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"
#import "NSPasteboardWriting-Protocol.h"

@class NSArray, NSPointerArray, NSPredicate, NSString;

@interface IDEVariablesViewNode : NSObject <NSPasteboardWriting, NSCopying>
{
    NSString *_name;
    id <IDEDataValue> _dataValue;
    IDEVariablesViewNode *_parent;
    id _childObserver;
    NSPointerArray *_children;
    NSArray *_filteredChildren;
    NSPredicate *_childFilter;
    unsigned long long _type;
    BOOL _expanded;
}

+ (id)keyPathsForValuesAffectingChildValuesCountValid;
+ (id)keyPathsForValuesAffectingFilteredChildren;
+ (id)pointerFunctions;
+ (id)rootWithChildren:(id)arg1;
- (void)_calculateAndSetFilteredChildren;
- (id)_childVariableNodeForChildDataValue:(id)arg1;
- (void)_formattedChildrenChanged:(id)arg1;
@property NSPredicate *childFilter; // @synthesize childFilter=_childFilter;
@property(readonly) BOOL childValuesCountValid;
@property(readonly) NSArray *children;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)countOfChildrenProxy;
@property id <IDEDataValue> dataValue; // @synthesize dataValue=_dataValue;
- (id)description;
@property BOOL expanded; // @synthesize expanded=_expanded;
@property(readonly) NSArray *filteredChildren;
@property(readonly) NSString *fullNamePath;
@property(readonly) BOOL hasChildren;
- (unsigned long long)hash;
- (id)initWithDataValue:(id)arg1 type:(unsigned long long)arg2;
- (BOOL)isEqual:(id)arg1;
@property(readonly) BOOL isTopLevelNode;
@property(readonly) NSString *name; // @synthesize name=_name;
- (id)objectInChildrenProxyAtIndex:(unsigned long long)arg1;
@property IDEVariablesViewNode *parent; // @synthesize parent=_parent;
- (id)pasteboardPropertyListForType:(id)arg1;
- (void)setChildren:(id)arg1;
- (BOOL)shouldShowAsFilteredChild;
@property(readonly) unsigned long long type; // @synthesize type=_type;
- (id)writableTypesForPasteboard:(id)arg1;

@end

