/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "DVTViewController.h"

#import "DVTInvalidation-Protocol.h"
#import "DVTStatefulObject-Protocol.h"
#import "IDESelectionSource-Protocol.h"

@class DVTStackBacktrace, DVTStateToken, IDESelection, IDEWorkspace, IDEWorkspaceDocument, IDEWorkspaceTabController;

@interface IDEViewController //: DVTViewController <IDESelectionSource, DVTStatefulObject, DVTInvalidation>
{
    IDEWorkspaceTabController *_workspaceTabController;
    //id <IDEWorkspaceDocumentProvider> _workspaceDocumentProvider;
    id _outputSelection;
    id _contextMenuSelection;
    id _commandForwarder;
    DVTStateToken *_stateToken;
    DVTStackBacktrace *_invalidationBacktrace;
    BOOL _isInvalidated;
}

+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (long long)version;
- (void)_invalidateSubViewControllersForView:(id)arg1;
- (BOOL)_knowsAboutInstalledState;
- (id)commandForwarder;
- (void)commitState;
- (void)commitStateToDictionary:(id)arg1;
@property(copy) IDESelection *contextMenuSelection; // @synthesize contextMenuSelection=_contextMenuSelection;
- (void)invalidate;
@property(readonly) DVTStackBacktrace *invalidationBacktrace; // @synthesize invalidationBacktrace=_invalidationBacktrace;
@property(readonly, getter=isValid) BOOL valid;
@property(copy) IDESelection *outputSelection; // @synthesize outputSelection=_outputSelection;
- (void)revertState;
- (void)revertStateWithDictionary:(id)arg1;
- (void)setNextResponder:(id)arg1;
- (void)setStateToken:(id)arg1;
//@property IDEWorkspaceTabController *workspaceTabController; // @synthesize workspaceTabController=_workspaceTabController;
//@property(readonly) DVTStateToken *stateToken; // @synthesize stateToken=_stateToken;
- (void)willCloseForever;
@property(readonly) IDEWorkspace *workspace;
@property(readonly) IDEWorkspaceDocument *workspaceDocument;
- (id)workspaceDocumentProvider;

@end

