/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTXMLUnarchiving-Protocol.h"

@class NSMutableSet, NSString;

@interface IDEVariablesViewContextState : NSObject <DVTXMLUnarchiving>
{
    NSString *_contextName;
    NSMutableSet *_expandedNodePaths;
    NSMutableSet *_persistentStrings;
}

- (void)_variablesViewContextStateCommonInit;
- (void)addPersistentStrings:(id)arg1 fromXMLUnarchiver:(id)arg2;
@property(readonly) NSString *contextName; // @synthesize contextName=_contextName;
- (void)dvt_encodeAttributesWithXMLArchiver:(id)arg1;
- (void)dvt_encodeRelationshipsWithXMLArchiver:(id)arg1;
- (id)initFromXMLUnarchiver:(id)arg1 archiveVersion:(float)arg2;
- (id)initWithContextName:(id)arg1;
@property(readonly) BOOL isEmpty;
- (BOOL)isNodeExpanded:(id)arg1;
- (void)nodeExpandedStateChanged:(id)arg1;
@property(readonly) NSMutableSet *persistentStrings; // @synthesize persistentStrings=_persistentStrings;

@end

