/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IDEWorkspace, NSMutableDictionary;

@interface IDEVariablesViewStateManager : NSObject
{
    IDEWorkspace *_workspace;
    NSMutableDictionary *_contextNamesToContextStates;
    BOOL _hasUnhandledArchiveData;
}

+ (id)_dataSpecifier;
- (id)_contextStateForContextName:(id)arg1;
- (id)_contextStateForContextNameCreatingIfNecessary:(id)arg1;
- (void)_readStateFromDisk;
- (void)_writeStateToDisk;
- (void)addContextStates:(id)arg1 fromXMLUnarchiver:(id)arg2;
- (void)addPersistentString:(id)arg1 forContextName:(id)arg2;
- (void)dvt_encodeRelationshipsWithXMLArchiver:(id)arg1;
- (id)initWithWorkspace:(id)arg1;
- (void)nodeExpandedStateChanged:(id)arg1 forContextName:(id)arg2;
- (id)persistentStringsForContextName:(id)arg1;
- (void)removePersistentString:(id)arg1 fromContextName:(id)arg2;
- (BOOL)shouldNodeBeExpanded:(id)arg1 forContextName:(id)arg2;

@end

