/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTDualProxyWindow.h"

@interface IDEWorkspaceWindow : DVTDualProxyWindow
{
}

+ (id)lastActiveWorkspaceWindow;
- (BOOL)_addCursorRect:(struct CGRect)arg1 cursor:(id)arg2 forView:(id)arg3;
- (struct CGRect)_adjustedFrameForSaving:(struct CGRect)arg1;
- (void)_invalidateCursorRectsForView:(id)arg1 force:(BOOL)arg2;
- (BOOL)_keyViewRedirectionDisabled;
- (void)_setCursorForMouseLocation:(struct CGPoint)arg1;
- (struct CGRect)adjustedFrameForCascade:(struct CGRect)arg1 fromWindow:(id)arg2;
- (void)becomeMainWindow;
- (BOOL)canBecomeKeyWindow;
- (BOOL)canBecomeMainWindow;
- (void)close;
- (void)recalculateKeyViewLoop;
- (void)setDelegate:(id)arg1;
- (void)setWindowController:(id)arg1;
- (void)toggleToolbarShown:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;

@end

