/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEActivityReporter.h>

@class IDEActivityReport;

@interface IDEWorkspaceActivityReporter : IDEActivityReporter
{
    id <DVTObservingToken> _activityObserverToken;
    id <DVTObservingToken> _workspaceNameObserverToken;
    IDEActivityReport *_activeReport;
}

+ (void)initialize;
- (id)_title;
- (id)initWithWorkspace:(id)arg1;
- (void)updateActivity;

@end

