/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSBundle.h"

@interface NSBundle (IBAppKitBundleAdditions)
- (void)IDE_IB_loadNibNamed:(id)arg1 owner:(id)arg2;
@end

