/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol NSPathControlDelegate <NSObject>

@optional
- (BOOL)pathControl:(id)arg1 acceptDrop:(id)arg2;
- (BOOL)pathControl:(id)arg1 shouldDragPathComponentCell:(id)arg2 withPasteboard:(id)arg3;
- (unsigned long long)pathControl:(id)arg1 validateDrop:(id)arg2;
- (void)pathControl:(id)arg1 willDisplayOpenPanel:(id)arg2;
- (void)pathControl:(id)arg1 willPopUpMenu:(id)arg2;
@end

