/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSURL.h"

@class NSImage;

@interface NSURL (IDEKitClassAdditions)
@property(readonly) NSImage *fileIcon;
- (BOOL)ide_isSameDocumentAsURL:(id)arg1;
@end

